### ISSUE TITLE
Remove selected default Hyrax metadata fields from the Work Form

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#106]
As we added our own DLP/Curate metadata fields to the Work Type, we still see a number of default Hyrax metadata fields which we don't want to present to users. 

For this ticket, we will remove them from the form. In a future ticket, we may also look at removing some of these from the attributes files also, but are not sure if this may negatively impact any Hyrax functionality.

Default Hyrax metadata fields to remove from the form:

- [x] Alternative title
- [x] Archivo checksum
- [x] Location
- [x] Contributor
- [x] Description
- [x] Identifier
- [x] Label
- [x] Related URL
- [x] Resource Type
- [x] Source

We may also want to remove Date Created since it will be redundant with Date Issued for this content, but I will submit another ticket if that is confirmed.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/110

**Comment by eporter23** [comment]
Tested and looks good @bwatson78
