### ISSUE TITLE
Characterization fails on uploaded FileSets in arch

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#113]
**Describe the bug**

We can now create new Works and upload filesets in the arch environment. The FileSet processing is not completing the characterization and thumbnail creation process, however, and it loops in Sidekiq retries.

**To Reproduce**
1. Create a new work, or edit an existing work
2. Click on the Files tab and select a file to upload (use a common image format such as JPG or PNG). 
3. Wait for the FileSet to be created and attached to the work.
4. Look at sidekiq for arch, and note an error message 

**Expected behavior**

- [x] Characterization details populates on the FileSet show page.

**Screenshots**

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmZPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d77bd0be4989fe2453fd6e8e1f91d26e60be0c56/Screenshot%202024-03-11%20at%204.27.54%E2%80%AFPM.png" alt="Screenshot 2024-03-11 at 4.27.54 PM.png" />

<img width="1018" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmpPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15b406aff3c879f51be348c549fce22c682fb76e/Screenshot%202024-03-11%20at%204.28.44%E2%80%AFPM.png" alt="Screenshot 2024-03-11 at 4.28.44 PM.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bwatson78** [comment]
@abelemlih Sorry for stepping on your toes here, but I set two ENVs in the production server and created a new Publication--no more error. But now we can confirm that derivatives are not being created.

**Comment by eporter23** [comment]
We now get characterization but not thumbnails.

**Comment by eporter23** [comment]
Thanks @bwatson78 ! I uploaded 2 new FileSets (.png and .docx) and both showed characterization details.
