### ISSUE TITLE
Resolve errors when trying to access objects through the Fedora 6 interface

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#116]
In some circumstances we encounter a 400 bad request error when trying to use the Fedora UI to access an individual resource.

To reproduce:
Go to https://fedora-depo-arch.libraries.emory.edu:8443/fcrepo/
Click on Rest endpoint
Click on production
See 400 error

**Comment by jcrompton42** [comment]
Added the following to /opt/tomcat/conf/server.xml:

        <Valve className="org.apache.catalina.valves.RemoteIpValve" 
                internalProxies="10\.65\.89\.150|10\.65\.89\.29" 
                remoteIpHeader="x-forwarded-for" 
                proxiesHeader="x-forwarded-by" 
                protocolHeader="x-forwarded-proto" />

Emily verified this solution.
