### ISSUE TITLE
Add sections and groupings for fields in deposit form: Intro section

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#118]
For this ticket, we will begin to break the Deposit Form into several sections with headings. Please see this [early mockup for the overall section flow](https://docs.google.com/drawings/d/1j2_g4mBrb4BGrp4VU9JFKBOMtinWM64k1C2UN-NVSDQ/edit).

- [x] At the top of the Descriptions tab, please add the following guidance text above the input fields:

> Please provide a description of your publication so that it can be properly cited by others. Next, click on the **Files** tab when you are ready to upload your content.
> The **Save Work** menu will indicate when you have completed all required elements for your submission.
> Please refer to our [Help](/) page for more guidance.

- [x] Move the content_genres field to display as the first input after the guidance text.

NOTE: in a separate ticket, we want the Content Genres (content_genres) field selection to drive the display of other fields in the Publication Information section of the form. This is noted in case it impacts future work. We will also likely adjust the display labels for some fields including this one.

**Comment by maxdmayhew** [comment]
<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDhLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c872162ad27269d9eb849524b21ba7e97f1d9d4/Screenshot%202024-03-25%20at%203.42.29%20PM.png" alt="Screenshot 2024-03-25 at 3.42.29 PM.png" />

PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/161

**Comment by eporter23** [comment]
Looks great!
