### ISSUE TITLE
Add sections and groupings in deposit form: Publication Information

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#120]
For this ticket, we will begin to break the Deposit Form into several sections with headings. Please see this [early mockup for the overall section flow](https://docs.google.com/drawings/d/1j2_g4mBrb4BGrp4VU9JFKBOMtinWM64k1C2UN-NVSDQ/edit).

Add a new heading for **Publication Information**
Move the following fields under this new heading, in this order: 

- [x] Title (title)
- [x] Creator (creator)
- [x] Primary Language 
- [x] Date Issued (date_issued)
- [x] Publisher (publisher)
- [x] Publisher version (publisher_version)
- [x] Rights statement (rights_statement)
- [x] License (license)
- [x] Final Published Versions (final_published_versions)
- [x] Title of Parent Work (parent_title)
- [x] Conference Name (conference_name)
- [x] ISSN (issn)
- [x] Series Title (series_title)
- [x] Edition (edition)
- [x] Volume (volume)
- [x] Issue (issue)
- [x] Start Page (page_range_start)
- [x] End Page (page_range_end)
- [x] Place of Production (place_of_production)
- [x] Sponsor (sponsor)
- [x] Grant Agencies (grant_agencies)
- [x] Grant Information (grant_information)
- [x] Related Datasets (related_datasets)

**Comment by maxdmayhew** [comment]
https://github.com/emory-libraries/dlp-selfdeposit/pull/157

@eporter23 I may have went a little overboard but I went ahead and set it up to see what it would look like set up as an accordion. 

<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWNFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e1b61d20c8ca1db72b5080b246a8ec98ced3565/Screenshot%202024-03-22%20at%206.15.32%20PM.png" alt="Screenshot 2024-03-22 at 6.15.32 PM.png" />

<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWdFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0dd78cb2c887677ad43cc02eb77c7493cc4b0559/Screenshot%202024-03-22%20at%206.15.38%20PM.png" alt="Screenshot 2024-03-22 at 6.15.38 PM.png" />

<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9FQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f647958d513dee5362f9852636469b4acba13611/Screenshot%202024-03-22%20at%206.15.41%20PM.png" alt="Screenshot 2024-03-22 at 6.15.41 PM.png" />

badge branding was taken from digital collection to help user experience.

<img width="1379" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7a26b34cd4ffa867c6a9a791b7f35ab7e08e7f9/Screenshot%202024-03-22%20at%206.19.34%20PM.png" alt="Screenshot 2024-03-22 at 6.19.34 PM.png" />


However, the styling and accordion is easy to remove if we feel this is too confusing!

**Comment by eporter23** [comment]
Thanks @maxdmayhew - looking forward to seeing it once it's deployed! I would recommend removing the "required" badge from the accordion because that implies all the fields in the section will be required and that won't always be the case for each section we build out.

**Comment by maxdmayhew** [comment]
<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTRJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6953cf4bf767cb9a09e09e44372bba68d38d3057/Screenshot%202024-03-25%20at%2010.54.18%20AM.png" alt="Screenshot 2024-03-25 at 10.54.18 AM.png" />

<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeThJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ada8294f551c481fa679a27c47c3d51a86bebee3/Screenshot%202024-03-25%20at%2010.54.18%20AM.png" alt="Screenshot 2024-03-25 at 10.54.18 AM.png" />

@eporter23 I replaced them with carets!

**Comment by eporter23** [comment]
Excited to see all this work, thanks @maxdmayhew !

**Comment by eporter23** [comment]
Looks great @maxdmayhew !
