### ISSUE TITLE
Add sections and groupings in deposit form: Additional Information

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#121]
For this ticket, we will begin to break the Deposit Form into several sections with headings. Please see this [early mockup for the overall section flow](https://docs.google.com/drawings/d/1j2_g4mBrb4BGrp4VU9JFKBOMtinWM64k1C2UN-NVSDQ/edit).

Add a new heading for **Additional Information**
Move the following fields under this new heading, in this order: 

- [x] Abstract (abstract)
- [x] Author Notes (author_notes)
- [x] Keywords (keywords)
- [x] Subject (subject)

**Comment by maxdmayhew** [comment]
keywords is not included at the moment @eporter23 but I included the rest. 

<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c7f8234ad1aa017f4a61d605441b984cc196a82/Screenshot%202024-03-25%20at%2011.08.57%20AM.png" alt="Screenshot 2024-03-25 at 11.08.57 AM.png" />

**Comment by maxdmayhew** [comment]
adding or moving fields around is really simple so this can be updated later as a cleanup ticket if that's okay with you.

**Comment by maxdmayhew** [comment]
<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMThJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--571697d683dec35af3e614a78a69311cb81afc59/Screenshot%202024-03-25%20at%2011.19.48%20AM.png" alt="Screenshot 2024-03-25 at 11.19.48 AM.png" />

PR https://github.com/emory-libraries/dlp-selfdeposit/pull/158

**Comment by bwatson78** [comment]
@maxdmayhew Keywords is in `emory_basic_metadata.yaml` as `keyword`.

**Comment by maxdmayhew** [comment]
https://github.com/emory-libraries/dlp-selfdeposit/pull/168 added keywords

**Comment by eporter23** [comment]
I'll wait to test this again because I don't think the keywords change has been deployed yet.
