### ISSUE TITLE
Add sections and groupings in deposit form: Administrative Metadata

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#122]
For this ticket, we will begin to break the Deposit Form into several sections with headings. Please see this [early mockup for the overall section flow](https://docs.google.com/drawings/d/1j2_g4mBrb4BGrp4VU9JFKBOMtinWM64k1C2UN-NVSDQ/edit).

Add a new heading for **Administrative Metadata**
Move the following fields under this new heading, in this order: 

- [x] Emory ARK
- [x] Copyright Statement
- [x] Internal Rights Note
- [x] Staff Note
- [x] Access Restrictions
- [x] System of Record ID
- [x] Format
- [x] Library
- [x] Institution
- [x] Data Classifications
- [x] Date Created
- [x] Deduplication Key

If this ticket is being worked on before other sections have been created, we can leave the other fields as ungrouped in the middle of the form. Administrative Metadata will be the last section of the form visually.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/147

**Comment by bwatson78** [comment]
Once PR above is approved and merged, Backend has completed their side of this ticket.

**Comment by eporter23** [comment]
@bwatson78 apologies but I omitted deduplication_key from my original list of fields. can we move that field into the Administrative Metadata section also?

**Comment by bwatson78** [comment]
<img width="623" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFlQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a59faab92320b9c7605d6e04a278520fe867c10a/Screenshot_20240326_103439.png" alt="Screenshot_20240326_103439.png" />

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/167

**Comment by eporter23** [comment]
@bwatson78 looks great! Sorry that I didn't specify the attribute names in this ticket, but the Copyright Statement field noted above in the description is the free-text `rights_notes` aka `emory_rights_statements` from Curate and not the controlled terms one.
