### ISSUE TITLE
Spike: Cannot access "roles" from Hyrax on arch (Routing Error)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#124]
While we seem to be able to create groups/roles in the UI in the Sirenia docker image, trying to access them from the deployed instance of Self Deposit returns an error:

> Routing Error
No route matches [GET] "/roles"
Rails.root: /opt/dlp-selfdeposit/releases/20240318195952

For this ticket, we should investigate what is missing in order to manage groups/roles in our deployed environment using the Hyrax UI. 

As a reference, the Roles UI is accessible in Curate-test at this path:
https://curate-test.library.emory.edu/roles

**Comment by bwatson78** [comment]
@eporter23 That didn't take any time at all. Per `rails routes`, `/roles` is a route introduced by by `Hydra::RoleManagement::Engine`. Since this took me just a little bit of time, do you want me to draft a new ticket and treat that as my next task?

**Comment by eporter23** [comment]
Yes please!
