### ISSUE TITLE
Use S3 as storage root for Fedora 6 in arch

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#126]
For this ticket, we want to configure and test Fedora 6 backed by S3 storage.

See prior work ticket for configuring Fedora 6 to use S3:
https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/103

As the primary storage bucket, we should use the one already configured for the arch environment: 
fedora-depo-binaries-arch

To test this ticket, we should:
Upload a new file through Hyrax
Check the S3 bucket to ensure the file has been transferred over

**Comment by eporter23** [comment]
@jcrompton42 I am not sure if this is ready to test or not but I did create a new work and upload a file with no issues. I have also hunted and pecked for the associated file in the S3 bucket and did find it, but I have broader questions for the team about how to interpret the pair tree folder structure and ID scheme being generated for S3.

**Comment by jcrompton42** [comment]
@eporter23 Definitely test, thanks! I am not sure how to interpret the file system structure either...

**Comment by eporter23** [comment]
Thanks @jcrompton42 ! I will close this ticket out soon and will spend some time trying to formulate a question about the S3/OCFL structure which I'll probably have to ask the Fedora folks about.

**Comment by eporter23** [comment]
Closing this! I have also written up a new investigation ticket for which I'll probably start asking questions in Fedora slack. #174
