### ISSUE TITLE
Create new EFS instance to serve as staging area for OpenEmory files in migration

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#127]
For this ticket, we want to provision a new EFS instance in the Self Deposit arch environment which is separate from the one used by Curate.

This EFS instance will serve as a staging area for files exported from Fedora 3 so that they can be packaged and used by Bulkrax for bulk-imports during the migration.

After migration, we plan to sunset this EFS space.

For the name of this EFS instance, we can use whatever best practices Middleware has in place, but we may want to include "openemory" or "selfdeposit" for context.

We should setup separate folders for QA fedora exports vs. production fedora exports.

**Comment by jcrompton42** [comment]
We now have an OE24 EFS share that currently has 2 folders on it: qa and prod. the qa folder is mounted on the hyrax arch instance at /mnt/efs/
