### ISSUE TITLE
Request attributes for Shibboleth SP

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#128]
For this ticket, we want to submit the request to use the attributes documented in #96.

**Comment by kbowaterskelly** [comment]
Good news - I found documentation about this and it looks like our initial surmise was largely correct, in that anything listed here ( https://login.emory.edu/client-config/attribute-map.xml ) is available to us. I don't think anything else will be, but I've submitted a ticket asking for clarification: INC04243432

If, for some reason, these attributes listed in the attribute map are not immediately made available to us, the process for getting that corrected is outlined in SN KB01436 - but this would be a process followed after the Shibboleth SP is already configured and functioning generally.

For reference, the documentation for that is in SN KB01317

The remaining work, then, would seem to be to reframe this from general terms to specific ones, i.e. mapping the desired types of stuff to the relevant attributes in the map.. which sounds confusing, but it shouldn't be too hard. Either I or @eporter23 could probably take care of it. I think we should wait to hear back if there are potentially other attributes available not listed in the map, but it does not necessarily behoove us to do so if what is in the map is sufficient.

Either way, let's touch base at the next meeting and discuss our next steps, I will update with the answer from OIT when I get it.

**Comment by eporter23** [comment]
From Slack conversation, we are leaning toward trying to do a basic SP install and then interpreting the attributes that seem to be readily available in the attribute map for public directory data. We have not been able to get additional information so far regarding these attributes, but the ID mgt team seems to indicate that everything in the previously identified attribute map are available.
