### ISSUE TITLE
Deleting works results in a Tombstone error

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#131]
From @bwatson78:  attempting to delete Works produces a Tombstone related error

**Comment by bwatson78** [comment]
This error is present in Sirenia. I will create a ticket in Samvera's Hyrax repository and reference that here.

**Comment by bwatson78** [comment]
https://github.com/samvera/hyrax/issues/6740

**Comment by eporter23** [comment]
This seems to be a Valkyrie-Fedora persistence issue but may not be specific to Fedora 6. Postgres has a different method for querying related objects when an item is deleted.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/255

**Comment by eporter23** [comment]
Thank you, seems to be working! I deleted some existing works and created a brand new one and deleted it. Note for posterity: I did have to clear my cache first but hopefully that's a temporary thing.
