### ISSUE TITLE
Collection banner and thumbnail images

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#138]
When create a new Collection instance of the OpenEmory Collection Type, I am able to upload a banner through the form, but when trying to save the change, 

Steps to reproduce:

- Login as Admin
- Go to Collections > Create new Collection
- Select "Library Collection" as the Collection Type
- Fill out required metadata
- Go to the Branding tab
- Upload an image for the Banner option
- See that your file has been selected
- Save changes
- Once you receive the confirmation message that changes have been applied, click Cancel
- Click on the Public View of Collection and observe that there is a space for the image, but it is not displayed

The path to the banner image appears to be /branding, so we should confirm if these files actually exist in that location. If this is a configuration we need to change, we should ensure we change it for the test and prod environments also.

**Comment by eporter23** [comment]
Note: this may be related to issues we are having with thumbnails not being saved. See slack discussions on 3/19/24.

**Comment by bwatson78** [comment]
This is currently fixed and will be fixed for future deployments when the following issue is resolved: https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/284

**Comment by eporter23** [comment]
Thanks @bwatson78 - I was able to replace the banner image on the OE collection in test just now.
