### ISSUE TITLE
Implement `Hydra::RoleManagement` into SelfDeposit

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/dlp-selfdeposit#148]

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/149

**Comment by eporter23** [comment]
Thanks @bwatson78 - I've been able to recreate the OE collection-level groups and assign our default Hyrax users to them. I'll keep an eye on this to see if our changes are retained throughout deployments.
