### ISSUE TITLE
Indexing for Preservation Metadata

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#150]
For this ticket, we want to ensure that our custom properties for preservation metadata are indexed in SOLR as we have done in Curate, so that we can use this data for display and reporting purposes.

For all of these, we want to make sure data in SOLR is stored in a structured way so that we can parse it out for display instead of having it display as one blob of unformatted text. As references for how we may want to parse this data out for display, view a [FileSet page in Curate](https://curate-test.library.emory.edu/concern/parent/5053ffbgk1-cor/file_sets/0752fqz69n-cor) or view a [Preservation Events page in Curate](https://curate-test.library.emory.edu/concern/curate_generic_works/5053ffbgk1-cor/event_details).

- [x] Preservation Events (Work-level and FileSet level)
- [x] Preservation Workflows (Work-level)
- [x] Include extended technical metadata extractions into FileSets ([This PR from Curate](https://github.com/emory-libraries/dlp-curate/pull/299) may relate) - may be addressed in #82

Note: the actual display for these properties will be addressed in separate tickets for the View Work page and View FileSet page.
Additionally, any customization of search in Hyrax related to these properties would be separate tickets or enhancements.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/209

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/210

**Comment by bwatson78** [comment]
The final bit of business is blocked until #82 is complete.

**Comment by eporter23** [comment]
Looks great @bwatson78 and @alexBLR ! I checked 3 FileSets and FileMetadata ids in SOLR. Note for my own future testing/documentation: the FileSet entry in SOLR contains all the technical metadata where in Fedora it's on the FileMetadata object.
