### ISSUE TITLE
Configure controlled vocabularies for subject entries

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#152]
For this ticket we want to support 2 different types of subjects that may be entered (or migrated).

- [ ] Subject - Topics (aka Hyrax "Subjects" field)

This will be a clone of what we previously configured for Curate, unless there are any conflicts with basic Hyrax metadata field name.
Vocabulary: QA lookup for Library of Congress Subject Headings

- [ ] Research Categories

This will be a new field (suggested fieldname: `research_categories`).
Vocabulary/form entry: lookup field for a new locally defined vocabulary. (Example: [data_classification.yml](https://github.com/emory-libraries/dlp-selfdeposit/blob/main/config/authorities/data_classification.yml))
The vocabulary terms for the lookup function should use the [Proquest Subject Categories list as documented here](https://docs.google.com/spreadsheets/d/1Y5UDecTVbiJS1PntIUGJeUmFx7Mhw0WCCuVBxgYs59s/edit#gid=1413493374) 
The official release of terms is produced on no more than an annual basis, and is published in a PDF such as this: 
https://pq-static-content.proquest.com/collateral/media2/documents/umi_subjectcategoriesguide.pdf

**Comment by abelemlih** [comment]
@eporter23 this ticket is ready for testing on Arch

**Comment by abelemlih** [comment]
@eporter23 @tmill29 I changed the estimate to 8 to account for all time spent debugging UI issues in Hyrax

**Comment by eporter23** [comment]
This is great, thank you!
