### ISSUE TITLE
Implement custom Creator field entries

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#154]
For this ticket, the goal is to expand on the basic Creator field which is by default a single input field, and split it into subfields so that we can account for an author's name, affiliation, and ORCID ID. 

When there are multiple authors entered for a Publication, we need to preserve the order in which they were entered, because the author order has significance in the record of a publication.

We previously prototyped methods for achieving this during the OpenEmory 2023 project using both Valkyrie and ActiveFedora. See https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/210 and https://app.zenhub.com/workspaces/legacy-systems-5d793aeb3859ca0001801253/issues/gh/emory-libraries/openemory/200

Here is a [draft mockup of what this may look like in the UI](https://docs.google.com/drawings/d/1hX1qi1v1AK8qB8tbU5vrPky2G8yIcKQveksNoHTEGXc/edit).

For this ticket, we want to present the Creator entry options in the Work form as:
Lastname*
Firstname*
Affiliation*
ORCID ID

*a user must enter a first name, last name, and affiliation for each author entered for a Publication.

NOTE: we will also want a facet field for Creator entries based on last name, first name only, so that users can browse by an author's last name. We should discuss if that work can be handled in this ticket or needs a separate ticket.

**Comment by abelemlih** [comment]
@eporter23 please refer to the screenshot below and let me know if you have any edits/suggestions to improve the UI of author addition/deletion:

<img width="910" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzJKQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7575b7a290374f8e0f3b967b37dd7970468f0272/Screenshot%202024-04-23%20at%205.02.49%E2%80%AFPM.png" alt="Screenshot 2024-04-23 at 5.02.49 PM.png" />

Authors are stored in order, and the order is preserved in Fedora and Solr. I will move this PR to review if the UI meets the requirements: https://github.com/emory-libraries/dlp-selfdeposit/pull/240
