### ISSUE TITLE
SOLR for arch environment

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#16]
In addition to the specs in the epic, we will need to also provide a Hyrax-compatible config file.

**Comment by eporter23** [comment]
We should hold off on this until we get our Hyrax instance running in case there are any changes we need to address. We also need to establish the collection name.

**Comment by eporter23** [comment]
Backend team will need to provide the config file.

**Comment by abelemlih** [comment]
@jcrompton42 These are the Solr config/schema files we current have setup in the dev environment: 

- schema: https://github.com/emory-libraries/dlp-selfdeposit/blob/main/solr/conf/schema.xml

- config: https://github.com/emory-libraries/dlp-selfdeposit/blob/main/solr/conf/solrconfig.xml

**Comment by jcrompton42** [comment]
collection OE24_collection created in arch using provided schemas and solrconfigs. 
https://solr-cor-arch.library.emory.edu/solr/#/OE24_collection/collection-overview
