### ISSUE TITLE
Adjust header for public search page views

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#165]
When viewing the public-facing search and browse pages, we want the header to display in the same way it shows on the homepage. In general, Hyrax presents a number of "views" to non-logged in users which display differently than what we see on the Dashboard (logged-in only users) views.

To resolve: When a user navigates from the homepage to do a view/browse or search, a second Hyrax header element is displaying beneath the Emory header which duplicates the same links shown in the Emory header.

Examples:

[Search page](https://oe24-arch.libraries.emory.edu/catalog?locale=en&search_field=all_fields&q=)
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGNjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05ad3681d60a585c6cad30a4d85046baea2f292d/Screenshot%202024-03-28%20at%2011.08.05%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 11.08.05 AM.png" />

[View Work page](https://oe24-arch.libraries.emory.edu/concern/publications/e6bb79ea-edd5-4f0b-9f80-f03731a469fb?locale=en)
<img width="1918" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDBjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8180c4074e7d7b7fdca198aa0ab833486d47038d/Screenshot%202024-03-28%20at%2011.17.24%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 11.17.24 AM.png" />

[View Collection page](https://oe24-arch.libraries.emory.edu/collections/5615da50-5422-4822-a35f-f5f6fb0462b6?locale=en)
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVFjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49a4a6d62e6a195d0f1757b8ab771cf2c4c7bc5b/Screenshot%202024-03-28%20at%2011.18.57%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 11.18.57 AM.png" />

[View Profile page](https://oe24-arch.libraries.emory.edu/users/admin@example-dot-com?locale=en)
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekljQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ade07653a482b3f351da3227e405236468ea1caa/Screenshot%202024-03-28%20at%2011.20.13%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 11.20.13 AM.png" />

**Comment by CB987** [comment]
<img width="1054" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEVtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50aecde5ec5f99d8c5c622e129084c5c1174f257/Screenshot%202024-04-01%20at%203.51.05%E2%80%AFPM.png" alt="Screenshot 2024-04-01 at 3.51.05 PM.png" />
profile page
<img width="862" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME1tQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb5bd3798c7a8efebfb4e22838c6f41469b12a86/Screenshot%202024-04-01%20at%203.51.32%E2%80%AFPM.png" alt="Screenshot 2024-04-01 at 3.51.32 PM.png" />
search page
I don't have collections or works on my local, but i think this will fix those too. Once it is merged I will confirm.

**Comment by eporter23** [comment]
@CB987 hopefully so, but if you need some steps for how to populate a Collection or work, just let me know! Might be good for you to have some data in your local for testing in general.

**Comment by CB987** [comment]
I was thinking the same thing, so definitely when you have time!

**Comment by eporter23** [comment]
Thanks @CB987 - tested against all the examples noted and all is looking great!

**Comment by CB987** [comment]
awesome! thanks :)
