### ISSUE TITLE
Adjust header for Dashboard/Edit/Create views

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#166]
For this ticket, we want to clean up the header display on Dashboard pages.
These pages are only visible to logged in users, and show when browsing the dashboard as well as when creating or editing items.

As a reference, the header display on the homepage is what we want to replicate:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2NjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31df488172e18ee6164730566c9ed04ae8bb391a/Screenshot%202024-03-28%20at%2011.07.43%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 11.07.43 AM.png" />

Examples of header layout when viewing the Dashboard edit pages:

Header when viewing the Dashboard general interface:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3NjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ff25003097769eb4b6d72d52ed13c8377575cd4/Screenshot%202024-03-28%20at%2011.07.23%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 11.07.23 AM.png" />

Header when scrolling down the Edit Work form:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzBjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76ec19e6d8ed47768d161d0a09f9b3de06504ee0/Screenshot%202024-03-28%20at%2011.08.46%E2%80%AFAM.png" alt="Screenshot 2024-03-28 at 11.08.46 AM.png" />

To adjust:

Please adjust the positioning of the elements so that it follows the pattern shown on the homepage header
please ensure the positioning of Emory header elements is above the inline navigation for Dashboard
please ensure the header does not cover the page content when a user is scrolling down the page

**Comment by maxdmayhew** [comment]
<img width="1403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWtlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b4d5623e12825104485b51051daebfc9af7c651/Screenshot%202024-03-28%20at%203.29.08%20PM.png" alt="Screenshot 2024-03-28 at 3.29.08 PM.png" />

PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/182

**Comment by eporter23** [comment]
Looks great, thank you!
