### ISSUE TITLE
Adjust fields in the "Additional Fields" toggle from Hyrax

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#171]
While testing the multiple form section grouping tickets, the default Additional Fields toggle seems to repeat a lot of the fields already displayed in other sections of the form.

In a team meeting, we discussed that this behavior may be resolved by setting all fields to be Primary, which should move them out of the Additional Fields toggle set. 

For the IIIF/rendering fields (Representative media, Thumbnail, and Rendering), if feasible, please keep them within the existing Hyrax "Additional Fields" section until we determine where to display them:

<img width="1323" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--432c0a63edc4178a6a24297305249e89b2f0af0d/Screenshot%202024-03-29%20at%209.24.21%E2%80%AFAM.png" alt="Screenshot 2024-03-29 at 9.24.21 AM.png" />

**Comment by eporter23** [comment]
Either front or backend could pick this up.

**Comment by CB987** [comment]
<img width="1129" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemcyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd10d7631f6229c1f9fabcf62f199ed9c16f3004/Screenshot%202024-04-04%20at%2012.02.26%E2%80%AFPM.png" alt="Screenshot 2024-04-04 at 12.02.26 PM.png" />

**Comment by eporter23** [comment]
Looks great @CB987 !
