### ISSUE TITLE
Re-order the sections in the Deposit Form

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#172]
Following the work done in multiple tickets to break the Publication Work form into sections, please re-order the form sections so that they [display in the sequence from the original mockup](https://docs.google.com/drawings/d/1j2_g4mBrb4BGrp4VU9JFKBOMtinWM64k1C2UN-NVSDQ/edit):

1. Intro section
2. Publication Information
3. Additional Information
4. Administrative Metadata

Any remaining fields can display after these sections, which will help us to identify any outliers.

**Comment by maxdmayhew** [comment]
PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/180

**Comment by maxdmayhew** [comment]
<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0FlQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe4b6ffc26aedcaffe09166e1ada88b21916f513/Screenshot%202024-03-28%20at%202.50.26%20PM.png" alt="Screenshot 2024-03-28 at 2.50.26 PM.png" />

**Comment by eporter23** [comment]
Looks great!
