### ISSUE TITLE
Implement Message Digest Calculation (aka Checksum Generation) with accompanying PreservationEvent

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/dlp-selfdeposit#173]
Expand the `original_checksum` field value by adding two more checksum digestions (SHA1 and SHA256). For reference we are adding the same customization from https://github.com/emory-libraries/dlp-curate/commit/15ee350f3bea052a24a8278839d2f500162a8a58. Because we are now dealing with Valkyrized objects, we will need to bring in the same testing and update it to use Valkyrie objects. 

After that behavior is implemented, we will need to add the PreservationEvent creation behavior, much like https://github.com/emory-libraries/dlp-curate/commit/02993e53485e48a9b7e34a7faaf49717893bb6ee and https://github.com/emory-libraries/dlp-curate/commit/5e3acc833d5ada3e23e66426897c7104b44d811d

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/224

**Comment by bwatson78** [comment]
When deployed, the system threw errors that the file wasn't accessible from the server. This [PR](https://github.com/emory-libraries/dlp-selfdeposit/pull/228) changes digestion to the binary file directly.

**Comment by eporter23** [comment]
@bwatson78 just confirming, after testing 3 new FileSets this morning I can see the extra checksum entries in Fedora and SOLR but I'm not seeing an accompanying Preservation Event yet. Is that still in progress?

**Comment by bwatson78** [comment]
Sorry, instituting the PreservationEvent got lost in the soup-making. Will do that now.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/232

**Comment by eporter23** [comment]
Looks great @bwatson78 -- checked in the test environment against multiple filesets.
