### ISSUE TITLE
Spike: Interpret IDs and directory structures stored in S3 from Fedora 6 [draft]

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#174]
Observations so far: the directory structure generated in S3 appears to be a 64 digit hash (sha256). The Fedora OCFL documents also indicate that sha256 is used.

> The SHA-256 hash of a Fedora resource's ID is calculated, converted to lowercase, then split into three-character segments. The first three segments are used in creating the first three levels of directories below the OCFL storage root. The OCFL object is persisted within a fourth-level directory, which is the entire, lowercase, SHA-256 value previously calculated. 

Scenario:

- I need to browse the S3 bucket to check to see if a file has persisted through Fedora into S3.
- I look at S3 and see a series of pair tree-ed directories based on a sha256 hash.
- Unless I navigate to the bottom directory of each folder and download its fcr-metadata file, I cannot interpret what the contents of the file/directory are, because I cannot figure out to reverse the hashed ID pattern.  

Example: path to a binary file in S3 in our arch bucket
/4eb/6a1/5f0/4eb6a15f088119da72ecd64cf30eaed8d0ea16b06f94b39e3e0b90b358497d43/v1/content/original

Path to the same "file" in Fedora: 
http://10.65.89.199:8080/fcrepo/rest/production/3b897eee-5667-41fb-9750-49eae82936c9/original/fcr:metadata

To determine: 

1. How we can trace directories and files in S3 back to their Fedora/SOLR records? [see comments below]
2. Which components of a **Fedora Resource's ID** (Fedora URI? parts of it?) are being hashed to produce the S3 directory identifier? [info:fedora/#########]
3. Should we submit a feature request to Fedora to display the OCFL storage path for a given resource? [yes]
4. Is there a way we can search within an AWS S3 bucket for a known ID? [no]
5. Is there some tagging we can add to our persisted objects in S3 with their unhashed ID?

**Comment by eporter23** [comment]
I posted my question in Fedora slack and got an answer: the sha256 hash generated for a Fedora ID is based on the pattern of `info:fedora/foo/bar`.

**Comment by tmill29** [comment]
Beth will review.

**Comment by eporter23** [comment]
Additional notes from Beth regarding custom tagging on S3 objects: 
https://docs.aws.amazon.com/AmazonS3/latest/userguide/tagging-managing.html
docs.aws.amazon.comdocs.aws.amazon.com
Managing object tags - Amazon Simple Storage Service
This section explains how you can manage object tags using the AWS SDKs for Java and .NET or the Amazon S3 console.
Summary: S3 objects should support any arbitrary tag of the form key:value (up to 10 arbitrary tags)
