### ISSUE TITLE
Update Fedora 6 to latest version (6.5)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#179]
Fedora was recently updated to version 6.5, which includes some work that we may benefit from.

https://wiki.lyrasis.org/display/FF/Fedora+6.5.0+Release+Notes

We should also update any templating scripts to reflect the version change when starting on test, prod environments

**Comment by eporter23** [comment]
I've been able to view objects deposited prior to the update, but when testing a new deposit today I am seeing this error on the file upload screen. <img width="1123" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTFCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c3c79fb08e57ae145201c8f2374ef9e24975d80/IMG_0402.PNG" alt="IMG_0402.PNG" />

**Comment by jcrompton42** [comment]
the hyrax instance is out of space, please try another upload @eporter23 ?
