### ISSUE TITLE
Spike: can we show/hide form fields based on the selected content-genres field? 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#181]
This ticket is an investigation to see if we can show or hide fields in the Publication section depending on what the user has selected for the content_genres field.

Only some of the fields in the publication section of the form will apply to certain types. As an example, if user selects a Book, the ISSN field should not display, because it only relates to Articles.

The goal here is to reduce the visual information overload in the form by only showing fields applicable to certain sub-types of Publications.

**Comment by maxdmayhew** [comment]
@eporter23  here is a really basic example but this should be no issue. 

<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzVDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93d474f38b3464539746d6220fde25383e9aa3d9/Screenshot%202024-04-08%20at%204.20.08%20PM.png" alt="Screenshot 2024-04-08 at 4.20.08 PM.png" />

<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzlDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fbbf038774c2f6f2fa5d8878df34f9a2c9a04bff/Screenshot%202024-04-08%20at%204.20.12%20PM.png" alt="Screenshot 2024-04-08 at 4.20.12 PM.png" />

estimate is as you would probably expect based on how many labels actually need to change.

**Comment by eporter23** [comment]
Thanks for looking into this! I'll write up separate followup tickets for the Backlog fairly soon.
