### ISSUE TITLE
Spike: investigate use of custom Hyrax workflow for review process

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#187]
For this ticket, we want to investigate the level of effort required to create a custom Hyrax workflow to support the OpenEmory review process. Since Hyrax offers workflow capabilities, and we want to be able to accommodate different types of material to be self-deposited in the future, we should confirm if we can use the Hyrax workflow approach for OpenEmory before implementing a one-off workaround.

The basic workflows offered in Hyrax provide a review and approve capability, but in these sequences, a work is not "published" until it is approved.

In the current OpenEmory deposit service, a deposit becomes available/visible to end users immediately, but is added to a review queue. The SCO team then works through a backlog of items to be reviewed, enhances or corrects metadata, checks the file uploaded, and then marks it as "reviewed" using a metadata status field.

If we are able to use a customized Hyrax workflow, it must support the following needs:

1. A work can be deposited and become visible immediately (public or embargoed) to non-logged in users
2. The work is then flagged as needing to be reviewed, and is displayed in the Hyrax "review" dashboard
3. The depositor cannot edit their deposit once it is reviewed and accepted

Related documents describing the OpenEmory workflow:
[High-level overview of desired steps - 2024](https://docs.google.com/drawings/d/1JPt9rRCcZ9Bhlo4TuMshVwyFpSrl5VROXiKWg_kkloA/edit)
[Workflow discussion with SCO - 12/23](https://docs.google.com/document/d/1NE7S1PrZTmi4FwDGIHl5CPaAiMS42g2Tk3GC7mRmwEk/edit#heading=h.hbyuy15xf21e)
[2023 Manual Deposit application flow in legacy OpenEmory](https://docs.google.com/drawings/d/1JuHpX2LWuWEkwMSGHtB5HVU8Z2QXmatWKvjN5UMYT5Q/edit)

Samvera docs:
https://github.com/samvera/hyrax/wiki/Defining-a-Workflow
https://samvera.github.io/workflow_and_mediated_deposit.html

See also Scrum team [breakout session notes from 4/28/24](https://emory.sharepoint.com/:w:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/01%20Active%20Project/OpenEmory%20Phase%202/04%20Meeting%20Notes/Scrum%20Team/Outside%20Discussions/OE%20Review%20Workflow%20Session.docx?d=w77e19891bbee499d8a8c509d93a02814&csf=1&web=1&e=6zdTT3)

Potential work tasks:

- [ ] Learn about existing out of the box Hyrax workflows
- [ ] Find documentation about customizing workflows
- [ ] Estimate how large of a work ticket it will be to implement

**Comment by eporter23** [comment]
Discussed with @bwatson78 in Slack that this appears to be feasible, so we are doing to do a small prototype. We also are going to test if we can generate a new Preservation Event at the end of a workflow sequence such as When a work has been “approved” (no longer “under review”):
type: Metadata modification
Start: {datetime}
End: {datetime}
Details: Deposit reviewed and approved
software_version: SelfDeposit v1
User: {the id of the user who reviewed approved the deposit}```

**Comment by bwatson78** [comment]
PR made for prototype: https://github.com/emory-libraries/dlp-selfdeposit/pull/206

**Comment by eporter23** [comment]
Discussed with @bwatson78 that I will write up a separate pt 2 spike ticket to investigate some other questions, but this is working really well so far! Moving into To Accept in case anyone else wants to discuss.
