### ISSUE TITLE
Persist pcdm_use for FileSets to Fedora and SOLR 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#195]
This ticket follows work already done to configure pcdm_use at the FileSet level in #143.

For this ticket we want to ensure for newly created FileSets:

- [x] A default value of Primary Content is assigned so that there is always a value for this property
- [x] A SOLR field is present and populated for a FileSet using one of the vocab terms (Primary Content, Supplemental Content, Supplemental Preservation)
- [x] `pcdm_use` is also persisted to Fedora with one of the 3 terms noted above

Steps for testing:

- Upload a new FileSet in Self Deposit arch
- View the FileSet by its ID in Fedora-depo-arch 
- Confirm the pcdm_use property is displayed, with a value such as Primary Content, Supplemental Content, Supplemental Preservation is present in the SOLR record
- View the FileSet by its ID in SOLR
- Confirm the pcdm_use_tesim field with a value such as Primary Content, Supplemental Content, Supplemental Preservation is present in the SOLR record

**Comment by eporter23** [comment]
For this ticket, we need to look at revising pcdm_use at the FileSet level (not for files, we will use what Valkyrie offers at the file-level) and create a new field that only uses the 3 string values noted above. Example: fileset_category or fileset_use - since these values never had anything to do with the PCDM use vocabulary and are locally defined.

**Comment by abelemlih** [comment]
@eporter23 deployed to Arch and ready for testing

**Comment by eporter23** [comment]
Looks great - I can see the data persisting to both Fedora and SOLR now. 
<img width="738" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelZTQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cc432b49904dcd76864c4f8da3e1a7e6fa4559c/Screenshot%202024-04-11%20at%209.42.56%E2%80%AFAM.png" alt="Screenshot 2024-04-11 at 9.42.56 AM.png" />
