### ISSUE TITLE
Metadata field labels - pt.1

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#197]
The following changes metadata fields' display labels have been reviewed and approved with SCO. Please adjust the display labels for these fields on the Work form and the View Work page.

`emory_content_type`	**Type of Material** [revised: should be content_genres, not emory_content_type]
`rights_statement`	**Copyright Status**
`rights_notes`	**Copyright Statement**
`final_published_versions`	**Final Published Version (URL)**
`parent_title`	**Title of Journal or Parent Work**
`conference_name`	**Conference or Event Name**
`issn` **ISSN** (change to all capitals)
`isbn` **ISBN** (change all capitals)
`series_title` **Series Title** (change to capitalize "Title")
`author_notes` **Author Notes** (change to capitalize "Notes")
`keyword` **Keywords** (change to make plural)
`subject` **Subject - Topics**
`research_categories` **Research Categories** (change to capitalize "Categories")

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/402

**Comment by eporter23** [comment]
Looks great @bwatson78 - apologies, but I listed` emory_content_type` instead of `content_genres` for **Type of Material** . So, Type of Material should be the label for `content_genres`. Can we make that change here or should I roll that into another ticket? (Hopefully that didn't mess up the Facet work also)

**Comment by bwatson78** [comment]
@eporter23 No explicit setting of `emory_content_type`'s label?

**Comment by eporter23** [comment]
Let's set that one to "Format" which is what we call the equivalent field (content_type) in Curate.

**Comment by bwatson78** [comment]
Got it.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/405

**Comment by eporter23** [comment]
@bwatson78 sorry for the never ending headache of Content genre, but in doing some testing I'm not seeing this change kick in. Is this maybe a singular vs. plural situation? In publication_metadata.yaml it seems to be "`content_genre`" though in the main metadata worksheet (and in Curate) it's "`content_genres`"?

**Comment by bwatson78** [comment]
I'll fix that. 

Reminder: change Publisher Version to Publication Version.

**Comment by eporter23** [comment]
Looks great!
