### ISSUE TITLE
Update development docker image to use 6.5

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#203]
Since we have updated to Fedora 6.5 in arch, we should make sure local development environments are using this too.

**Comment by abelemlih** [comment]
I discussed this issue with members of the Samvera community as well as the Fedora engineering team, and the issue we are encountering is tied to Fedora/Tomcat 9 configuration and allowing encoded slashes as required by Hyrax. So far, none of the members has a working solution for Hyrax 5/Fedora 6.5.0 except for replacing slashes in IDs with another character (e.g. 'admin_set/default' to `admin_set_default`). For reference, we have not run into this issue with Fedora 6.4.0 even though it also uses Tomcat 9.

**Comment by eporter23** [comment]
@abelemlih I'll mention this at standup tomorrow also, but wanted to note that so far in my testing with arch and test since the admin set ID was changed, things seem to be okay with the change. I am noticing what I think may be a Hyrax 5 bug where if you view a Work and look at the Relationships section, it shows a link to the Admin Set the work is associated with, and if you click on it, it takes you to what seems to be a keyworded search result list which includes results outside of the specified Admin Set. I have seen it in our Hyrax 5 instance and just confirmed the same behavior in pg.nurax. Just commenting as an FYI (unlikely to be any concern for us to fix anytime soon if at all because end users don't need to know about Admin Sets).
