### ISSUE TITLE
Mockups for View Work Page (first pass)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#204]
For this ticket, please create preliminary mockups/prototypes for initial enhancements to the View Work page. This is an exploratory ticket in which we can identify visual layout ideas - in some cases, there is more data available than is currently shown on the page, so additional revisions may be needed in future tickets.

General requirements:

- Identify general layout improvements to the page type - either in code, or in a mockup (see 3 variations linked below)
- Enhance the current "Citations/Citations" buttons/dropdown layout (not the actual data that is generated in the modal)
- Remove the Facebook / Twitter / Tumbler block
- Please produce 3 mockups related to the examples noted below

Reference examples:

Image with Universal Viewer: https://oe24-test.libraries.emory.edu/concern/publications/1af72a57-db13-4a12-80a4-4d878623d49a?locale=en
Video with no Universal Viewer: https://oe24-test.libraries.emory.edu/concern/publications/192ad051-c942-436c-ae18-b2d3b34d8d21?locale=en
PDF with no Universal Viewer: https://oe24-test.libraries.emory.edu/concern/publications/9ebdffb8-d348-4e0b-acae-52b725b25d0f?locale=en

**Comment by CB987** [comment]
[video-option.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHVWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2d57f4353d72fee51198ef3345ed59ffd8f85bd/video-option.pdf)
[iiif-viewer-option.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHlWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2210f6e8fe8c9af955fac8fc0ec2ce65dce7682e/iiif-viewer-option.pdf)
[pdf_option.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--794af7d10f1f4701230cab91675d8c24ee10601a/pdf_option.pdf)

**Comment by eporter23** [comment]
@CB987 these look great, thank you! One minor consistency thing, can we make the call to action block "Tools" and not "Actions" across all 3 of these? This is what we use for digital.library and I think it'd be good to have consistency between them. Also, your new layouts are giving me ideas for additional things we can do on the page, now that it is starting to have some structure, but I will write those up as separate tickets.

**Comment by CB987** [comment]
Absolutely! I'll make the update to "Tools."
Thanks!

**Comment by CB987** [comment]
Updated the original attachments.

**Comment by eporter23** [comment]
Thanks @CB987 ! Just for reference, in the video one, we should have the media/thumbnail element width consistent with the width of the Tools menu.
