### ISSUE TITLE
Mockups for FileSet Show Page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#205]
For this ticket, we want to follow a similar process for how we created [mockups for the View Work page](https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/204), and then followed up with an implementation ticket.

Please review samples of the View Fileset page type and create mockups to optimize the layout.

Initial suggestions:

- Remove the social media links (Facebook, Twitter, Tumblr)
- Restyle the Preservation Events display so that it fits into the available width without requiring horizontal scrolling
- Consider moving the Preservation Events section into an accordion
- Identify other options to enhance the layout

For a representative work that has multiple FileSets with different types of media, [please see this work](https://oe24-test.libraries.emory.edu/concern/publications/d8e4eb7e-9aae-438d-af4a-d40026141f74?locale=en).
To access a FileSet page, go to the work and look at the list of Items.
Click on any "Title"/filename in the Items list and then view the page that follows.

**Comment by CB987** [comment]
<img width="901" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1VTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3040106e4e4710444c204033f775927fc6bb9a6e/Screenshot%202024-07-26%20at%201.19.45%E2%80%AFPM.png" alt="Screenshot 2024-07-26 at 1.19.45 PM.png" />
i have removed the horizontal scroll of the table, but i think that it gets a little ridiculous below about 1000px screenwidths. we can just have it scroll horizontally at that point? or, what would make sense to you @eporter23 ?

**Comment by eporter23** [comment]
I think if we can try to fit the table width to the container at 1000px+ and then have it scroll horizontally for smaller screens, that is good. Here's a recent snapshot of screen resolution and device activity for legacy OpenEmory in the last month:
<img width="1807" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0FUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe618b2acb201c88700f3b87d3e7df9762d36190/Screenshot%202024-07-26%20at%205.02.26%E2%80%AFPM.png" alt="Screenshot 2024-07-26 at 5.02.26 PM.png" />

**Comment by CB987** [comment]
<img width="521" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW9aQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ca5643e85f522e1a6b2cc01ce3aebe0444f0fc9/fileset.1.png" alt="fileset.1.png" />

The file details section looks a bit crowded to me, especially around the Tools menu. This is pretty consistent with other view/show pages but needs some refining still.

**Comment by CB987** [comment]
Example with the data tables collapsed. 
Having both tables collapsible might also benefit mobile viewers.
<img width="743" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29aQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26651be62f7fede1923beb1dd4da8759f6868d3a/screencapture-localhost-3000-concern-parent-bc58c286-b80a-48dd-a614-bd1244a9c88c-file-sets-0ec657b3-5a6b-4311-a4e5-3ea22e1b9a8a-2024-07-29-18_42_44.png" alt="screencapture-localhost-3000-concern-parent-bc58c286-b80a-48dd-a614-bd1244a9c88c-file-sets-0ec657b3-5a6b-4311-a4e5-3ea22e1b9a8a-2024-07-29-18_42_44.png" />

**Comment by CB987** [comment]
Tools menu has a bit more breathing room here
<img width="743" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79bb8cf86b3293e1ff4d424535efbd7bb29887d1/screencapture-localhost-3000-concern-parent-bc58c286-b80a-48dd-a614-bd1244a9c88c-file-sets-0ec657b3-5a6b-4311-a4e5-3ea22e1b9a8a-2024-07-29-18_55_10.png" alt="screencapture-localhost-3000-concern-parent-bc58c286-b80a-48dd-a614-bd1244a9c88c-file-sets-0ec657b3-5a6b-4311-a4e5-3ea22e1b9a8a-2024-07-29-18_55_10.png" />

**Comment by CB987** [comment]
Example with the tools menu (excepting the download item link) as buttons across the top, which has precedent in the view work page. 
<img width="545" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0FaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd0c311d9bfb36fda1d07b5bf77823e7982a510d/screencapture-localhost-3000-concern-file-sets-588683ea-8fbe-41a0-949f-f3360f8f6c06-2024-07-29-20_11_45.png" alt="screencapture-localhost-3000-concern-file-sets-588683ea-8fbe-41a0-949f-f3360f8f6c06-2024-07-29-20_11_45.png" />

**Comment by CB987** [comment]
@eporter23 ready for some input from you at your convenience, i think, thanks!

**Comment by eporter23** [comment]
@CB987 I prefer the one that retains the buttons! Though we may want to add some margins between the buttons and the File Details heading block.
Also, we seem to have a good bit more container width in Curate for the Preservation Events table. Can you take a look at one of these and let me know if anything we did there may help? https://curate-test.library.emory.edu/concern/parent/5053ffbgk1-cor/file_sets/0752fqz69n-cor

**Comment by CB987** [comment]
<img width="752" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3dqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a759d7a476e728355bf8387d41d8258ec7ad7e6f/Tool%20buttons%20and%20collapsed%20tables.png" alt="Tool buttons and collapsed tables.png" />
<img width="456" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2bd5e9b8a0d02ee2d29e35a41c7e5847c80031a6/Tool%20buttons%2C%20tables%20expanded.png" alt="Tool buttons, tables expanded.png" />
final version?

**Comment by eporter23** [comment]
Thanks @CB987, I like it! I'm not sure how you're approaching column widths, but it'd be great if we could expand the Event column so the entries don't have awkward word-breaks (such as how Characterization is shown above). We can also make the Outcome column narrower, because it will predictably be either "Success" or "Failure" only.

**Comment by CB987** [comment]
Got it! Thanks!
