### ISSUE TITLE
UX enhancement - accordions behavior on Publication work form

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#207]
This ticket was added as a byproduct to other UI work on the deposit form.

**Comment by maxdmayhew** [comment]
took a bit longer because using a bootstrap version produced unexpected results.

**Comment by eporter23** [comment]
Looks great so far @maxdmayhew ! I'll keep an eye out to see if there are any unexpected behaviors, if so I'll write up a new ticket.
