### ISSUE TITLE
Thumbnails/characterization errors in sidekiq

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#213]
After our most recent deploy to arch on 4/8/24, I am able to upload FileSets but they are returning errors in sidekiq and the characterization and thumbnail process is not completing.

As an example, see this work created on 4/9/24:
https://oe24-arch.libraries.emory.edu/concern/publications/ea74dc8e-d52a-41a6-a544-5da77272093f?locale=en

Sidekiq errors:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXhHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55717ff8c4d7e207fc75816b6eddc8551ca654d1/Screenshot%202024-04-09%20at%208.45.17%E2%80%AFAM.png" alt="Screenshot 2024-04-09 at 8.45.17 AM.png" />

**Comment by bwatson78** [comment]
With Beth's help, we identified that FITSservlet stopped working as expected. She is currently working on the fix and will ping me on Slack when it's back up.

**Comment by bwatson78** [comment]
The FITSservlet is reinstalled and working from Rails root. Checking Sidekiq, the objects have processed correctly.

**Comment by eporter23** [comment]
Looks good!
