### ISSUE TITLE
Optimize JS loading on Publication form [placeholder]

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#214]
Is there an easy way to have scripts only load in certain pages, or optimizing how JS is loaded? Some JS is only needed for the form and is not needed across the entire application.
Is it possible to target JS to a partial?

**Comment by maxdmayhew** [comment]
after talking to brad and ayoub, it appears that things are setup in a typical/practical way. This could be investigated later if needed (if we need to add a lot more JS or something down the road), but for now things look good. 

Closing out.
