### ISSUE TITLE
Spike: Hyrax workflow for OE deposits, pt 2

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#216]
For this ticket, we want to investigate a few more questions related to creating a custom workflow.

1. **Depositing User in Review Submissions** - this appears to be using `Creator` and not `depositor`
For this issue, we want to ensure that the value shown for "Depositing User" is a user ID and not an arbitrary author name. See the screenshot below as an example. In this case, I was logged in as basic_user, but the Depositing User shows up as "Test".
To confirm: is this a Hyrax bug?

<img width="1300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGRNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--419eb8ee8e35c5f81c35f2229215ba72aa63bc58/Screenshot%202024-04-10%20at%209.48.56%E2%80%AFAM.png" alt="Screenshot 2024-04-10 at 9.48.56 AM.png" />

2. **Preservation Event** - is it possible to also capture and store any comments added by a reviewer to the event details?
Context: when an admin approves a submission, there is an option to add comments as part of the approval interface. 
To determine: can we capture that comment entry and append it to the generic Metadata Modification event detail?
Example (the bold text is a comment added by the approver while completing the workflow):

> eventDetails: Deposit reviewed and approved. **File corrected and rights statement added.**

3. **Migration context** - is possible to assign a workflow state during a bulk ingest (e.g. Bulkrax)?
Context: we will have up to 1000 records still in an unreviewed state in the legacy OpenEmory application.
If using a workflow, we want to ensure that status is brought over into the new Self Deposit so that those records are still flagged as needing review.

4. **Notifications:** are there different options for using in-application notifications as well as sending email notifications?
For this question, we want to understand what options there may be to notify an Admin user or a depositing user about activity related to deposits. At this time, we haven't confirmed if notifications will be wanted, so this is just research.

**Comment by eporter23** [comment]
In-app notifications may need to have an Approver assigned

**Comment by bwatson78** [comment]
For 1. Depositing User in Review Submissions, I can confirm that the out-of-box behavior is intended to be the `#creator` attribute for the Publication. In my opinion, this is a Hyrax bug. I understand the logic that may be inherent here that, for applications like SelfDeposit, the Creator would also be the Depositor, but that doesn't extend to applications like Curate. I will code an overwrite of the partial and also submit a PR to Hyrax for the change.

**Comment by eporter23** [comment]
Thanks @bwatson78 !

**Comment by bwatson78** [comment]
PR made for above comment: https://github.com/emory-libraries/dlp-selfdeposit/pull/237

**Comment by bwatson78** [comment]
For 2. Preservation Event, I have made PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/239

**Comment by bwatson78** [comment]
For 3. Migration context, the Bulkrax ingestion processing can be overridden to include this code line:
```
Hyrax::Forms::WorkflowActionForm.new(current_ability: << user.current_ability>>, work: << publication object >>, attributes: {name: <<name of mediation step ("deposit" or "approve")>>, comment: <<comments made on form>>}).save
```
This will update the status of the mediated deposit.

**Comment by bwatson78** [comment]
And finally, for 4. Notifications, the `email` option for workflow notifications updates the User's Mailbox object with the same message it is attempting to email to them. So if we "turn on" the email notification processing in the workflow's JSON, the User would get the bell notifications even if the email settings aren't completely activated in AWS.

**Comment by eporter23** [comment]
Note regarding testing, the bug related to accordions and KeyError is blocking me from testing items 1 and 2.

**Comment by eporter23** [comment]
Items 1 and 2 are looking great. Screenshots below: 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGFaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62200f5d1c84d8085ead65e001ca71ba0e5dc5ac/Screenshot%202024-04-26%20at%2012.52.44%E2%80%AFPM.png" alt="Screenshot 2024-04-26 at 12.52.44 PM.png" />


<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFdaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b074c17111cabc6c13a640e8d56ebb28d3f46126/Screenshot%202024-04-26%20at%2012.52.44%E2%80%AFPM.png" alt="Screenshot 2024-04-26 at 12.52.44 PM.png" />
