### ISSUE TITLE
Install Hyrax/Samvera dependencies for arch

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#22]
We should also make sure that 

- [x] FITS
- [x] ImageMagick
- [x] LibreOffice
- [x] Yarn (for the UV)

are installed.

**Comment by tmill29** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DLP-Self-Deposit-65a7f6937b42b04b7bc5d018/issues/emory-libraries/dlp-selfdeposit/22?planning-poker) with Zenhub @abelemlih @bwatson78 @jcrompton42 @kbowaterskelly @alexBLR

**Comment by tmill29** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DLP-Self-Deposit-65a7f6937b42b04b7bc5d018/issues/emory-libraries/dlp-selfdeposit/22?planning-poker) with Zenhub @alexBLR

**Comment by abelemlih** [comment]
So far, the following dependencies are needed for errors in Arch to be resolved:

- redis
- memcached
- fits

Once these dependencies are created, I will reconfigure Arch and test.

**Comment by abelemlih** [comment]
Per team recommendation, we will keep using `ActiveSupport::Cache::FileStore` for caching, similar to the Curate setup. Therefore, we can remove `memcached` from the list of dependencies needed.

**Comment by abelemlih** [comment]
Redis was added to Arch successfully

**Comment by abelemlih** [comment]
@eporter23 @jcrompton42 FITS is installed and configured correctly on Arch

**Comment by abelemlih** [comment]
I added LibreOffice to the Hyrax configuration in #117. Once derivatives are working, we will be able to test whether LibreOffice is functioning properly in Arch.

**Comment by eporter23** [comment]
This is blocked for testing due to separate issues.

**Comment by bwatson78** [comment]
@abelemlih Has ImageMagick been installed on Arch yet?

**Comment by eporter23** [comment]
We can close this so if we find more dependencies, we will write up a new ticket or update this one.
