### ISSUE TITLE
Accordions not functioning in Edit Work form (arch and test) and KeyError when creating new works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#241]
After doing some testing on 4/23, I am finding that the accordions are no longer opening and closing. This seems to be happening when editing only - not when creating a new work.

The Publication accordion is open by default, but cannot be closed. 
The Additional information and Administrative metadata accordions can't be opened.

I've tested this in both Safari and Chrome browsers.

Steps to reproduce:

Login as the admin user
Go to Dashboard > Works
Open any work
Click Edit
Try to close/open any of the accordions

Note: this may be occurring because we made some changes to the required fields, so works that already existing won't allow you to move past the Publication section until those are entered.

Additional error:
When trying to manually add the required values, I can save the changes but then get a KeyError.

<img width="1947" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHFHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6470865f240c42dd5c78420228c18e08e2ac85b0/Screenshot%202024-04-23%20at%2010.43.08%E2%80%AFAM.png" alt="Screenshot 2024-04-23 at 10.43.08 AM.png" />

**Comment by eporter23** [comment]
Update on this: I get the same KeyError when creating a brand new work.

**Comment by abelemlih** [comment]
I deployed a fix for license related errors when saving a work to Test and Arch

**Comment by eporter23** [comment]
Thanks @abelemlih - I tested this with an existing work and also on a brand new work, and everything looks good.
