### ISSUE TITLE
Enable in-app notifications in custom mediated deposit workflow

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#248]
This ticket follows our second spike ticket #216 to investigate how to configure the workflow to generate notifications within Hyrax. At this time, we have not confirmed if this will be needed or not. We also anticipate not being able to send emails from an emory.edu address, and we also anticipate the potential for bounced emails if graduate/undergraduate students are submitting their work.

Notes from ticket #216:

Notifications, the email option for workflow notifications updates the User's Mailbox object with the same message it is attempting to email to them. So if we "turn on" the email notification processing in the workflow's JSON, the User would get the bell notifications even if the email settings aren't completely activated in AWS.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/269

**Comment by eporter23** [comment]
Looks great! I deposited a new work into the custom workflow approval process, saw the notification come in within the application, approved it, and then saw the approval notification. 

<img width="1538" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEhNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a9f9babeee0265c97d1a4fb6f5ce3db39345d33/Screenshot%202024-05-09%20at%204.56.03%E2%80%AFPM.png" alt="Screenshot 2024-05-09 at 4.56.03 PM.png" />
