### ISSUE TITLE
BUG: Cannot create a new Collection

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/dlp-selfdeposit#253]
Steps to Reproduce:

1. Log into any environment and go to Dashboard
2. Click on Collections, choose to Add New Collection, and choose any option explicitly named Collection
3. Click on Create Collection

The following error appears: 
<img width="1104" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnFsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fcc1bba7357773b7ef8a4c3b61b1e78ad130079/image.png" alt="image.png" />

This most likely has to do with the recent work done with the creators field.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/271

**Comment by eporter23** [comment]
I was able to create a new Collection in oe24-test. Thanks!
