### ISSUE TITLE
Can't expand or close accordions when editing an existing work

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#257]
The bug related to accordion behavior in the form is recurring. This occurs when trying to edit an existing work. Creating a brand new work does not show this issue.

See notes in https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/241. 

When editing an existing work, the Publication accordion is expanded and can't be closed.
The Additional Information and Administrative Metadata accordions can't be opened.

I've experienced this in both Chrome and Safari browsers.

Example - work deposited on 5/1/24:
https://oe24-arch.libraries.emory.edu/concern/publications/4874a812-afab-444e-aa50-e2efdfea52de/edit?locale=en

**Comment by bwatson78** [comment]
@eporter23 Can you retest? I'm not seeing the behavior for the example provided in Firefox and Chrome.

**Comment by eporter23** [comment]
I'm still seeing it - tried 3 or existing works this morning, also tried Firefox, same issue.

**Comment by bwatson78** [comment]
Still not seeing the behavior in the same browsers in my Linux boot, will attempt this on the Windows side of things...

**Comment by bwatson78** [comment]
@rotated8 I cannot get the vpn to connect on my Windows boot. Can you check the above behavior in your browsers?

Also, @abelemlih can you check the same on your Mac?

**Comment by bwatson78** [comment]
@eporter23 I decided to click through from the Works list to the work to the edit page and am now seeing the issue. Let me check if turbolinks are still a thing in Hyrax.

**Comment by bwatson78** [comment]
The workaround for the time being is a hard reload when that page exhibits that behavior or clearing cache before visiting.

**Comment by eporter23** [comment]
If I clear cache, accordions do function. But something we definitely want to fix!

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/264

**Comment by eporter23** [comment]
Looks good so far, thanks!
