### ISSUE TITLE
Remove selected fields from Collection metadata form

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#260]
For this ticket, we want to remove the following fields from the Collection metadata form. NOTE: additional tickets will be written to make other adjustments to the Collection form; this one focuses only on removals.

- [x] rights_statement
- [x] target_audience
- [x] Department
- [x] access_right
- [x] alternative_title
- [x] arkivo_checksum
- [x] abstract
- [x] identifier
- [x] publisher
- [x] label
- [x] language
- [x] license
- [x] related_url
- [x] resource_type
- [x] Source
- [x] Course

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/274

**Comment by eporter23** [comment]
@bwatson78 just started testing this, and if I try to save a change to an existing collection, it is prompting me to populate access_right - even though we removed it from the Collection form?

**Comment by eporter23** [comment]
Additionally, it prompts me to add a "language" though that is also not present in the Collection form.

**Comment by bwatson78** [comment]
I'll fix that.

**Comment by eporter23** [comment]
Looks good! Thanks!
