### ISSUE TITLE
Add selected fields to Collection metadata 

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#262]
For this ticket, we want to bring over some fields already defined for Publications, as well as selected fields defined for Curate Collection metadata.

Fields from Publication metadata:

- [x] holding_repository
- [x] Institution
- [x] internal_rights_note 
- [x] System_of_record_ID
- [x] Emory_ark
- [x] Staff_notes

New fields from Curate metadata:

- [x] Contact_information 
- [x] administrative_unit
- [x] Note

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/272

**Comment by eporter23** [comment]
Looks good! I'll wait to re-test this after we resolve the behavior noted in my comments on #260.
