### ISSUE TITLE
Adjust access_right field in Publication form

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#265]
After discussions with SCO and reviewing the existing rights metadata requirements, we want to make the following changes:

- [ ] Move access_right out of the Administrative Metadata section of the form and into the Publication section
- [ ] Display the access_right field immediately below the rights_statement field in the form
- [ ] Make access_right required in the form

**Comment by abelemlih** [comment]
PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/275

**Comment by eporter23** [comment]
Looks good, thanks @abelemlih !
