### ISSUE TITLE
Implement Shibboleth/SAML for Hyrax

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#267]
See prior work in #97 and in the linked epic.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/323
This gets us to the ability to reach Auth via `/users/saml/sign_in`.

**Comment by bwatson78** [comment]
@rotated8 Per your request:
<img width="1934" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejA4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8122a3ed5df6712094d723c74dac7285fd73a0e0/Screenshot_20240605_112756.png" alt="Screenshot_20240605_112756.png" />

**Comment by eporter23** [comment]
This will hook up the SAML backend, but the local auth is still in place for now.
