### ISSUE TITLE
Spike: how to address Creator field in Collections

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#268]
Investigate Hyrax/SOLR query needs for Collections are
Investigate if we should create a new distinct field for Creators with a separate predicate
Investigate if we should redefine/separate metadata configs for Publications vs. Collections

**Comment by bwatson78** [comment]
**Investigate Hyrax/SOLR query needs for Collections are:** Hyrax queries or interactions aren't concerned with any metadata field we pass along via the YAMLs.

**Investigate if we should create a new distinct field for Creators with a separate predicate:** Yes, we should use our own, separate, creator field for collection.

**Comment by bwatson78** [comment]
**Investigate if we should redefine/separate metadata configs for Publications vs. Collections:**
