### ISSUE TITLE
Customize File Uploader in Work Form

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#278]
This ticket follows work already done to allow for categorization of different FileSet types for OpenEmory material, and also relates to work we have implemented in Curate to allow for these different types of FileSets. 

Unlike Curate, however, we anticipate only having one file per each Fileset.

For Self-Deposit material, we want to allow users to submit one or more files:

**Non-admin depositors**

- [ ] Primary Content file (only 1 primary content file per work, always required)
- [ ] Supplemental Content files (optional: 1 or more per work)

**Admin users**
Admins should also have ability to upload the following, to assist with migration issues or complex publication objects:

- [ ] Supplemental Preservation files (optional: 1 or more per work)

**See also:**
[Early mockup for file uploader customizations](https://docs.google.com/drawings/d/1IkA7I6wImT1DxZ0XoEgaAvDowJKnV6W3Ac6b5992iqo/edit)

**Comment by abelemlih** [comment]
@eporter23 on Curate, a user can upload multiple filesets (with their separate primary content, intermediate files, etc.), would that also be the case in Self Deposit? Can a user submit multiple filesets, with each one having one primary content file for instance?

**Comment by eporter23** [comment]
@abelemlih yes, each fileset will have one and only one file attached. In the case of Self Deposit, it will be original_file instead of preservation_master_file. Let me know if you want more info!

**Comment by abelemlih** [comment]
For reference, I confirmed with Emily that multiple fileset creation and file upload will be supported, similar to Curate.

**Comment by abelemlih** [comment]
I discussed requirements with Emily, and enforcing one primary content file upload in the UI, as well as adding "Add files" to requirements (similar to Curate), will be addressed in a separate UI enhancement ticket.

**Comment by abelemlih** [comment]
@eporter23 this ticket is ready for testing

**Comment by eporter23** [comment]
Thanks @abelemlih ! Looks great and I appreciate all the check-ins you gave me along the way. One note that I want to capture while I was testing is that for the future UI enhancement work, I did run into a glitch where I tried to provide a custom name for the FileSet after I attached it but before submitting, and this caused the form to freeze up. But definitely something we can work around later!

**Comment by eporter23** [comment]
@abelemlih another thing I wanted to capture for any future enhancements is the behavior where if you don't provide a custom name/label for the FileSet, it shows a Hyrax path instead of the filename. I think this is something new or different in Hyrax 5 than previously so I will consider that as a future work as well.
