### ISSUE TITLE
Create mockup for header

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#28]
Please see the notes in the preliminary mockup for header and footer for OpenEmory, which shows a translation of Hyrax interface elements into EUL positions, and also notes default Hyrax elements that should be removed or hidden. 

Feel free to mock these up in whatever tool or format you prefer. 

Please adapt the following as needed to reflect current layout standards:

https://docs.google.com/drawings/d/11WdK_G1qkvITa0UlA0xRlNUJZ2MjjZiGIF4o2wLE8t0/edit?usp=sharing

**Comment by CB987** [comment]
https://docs.google.com/drawings/d/1-Msad2eUK9JID8FLEzdsolRBKWxkh8DRVCsyYkruiEk/edit?usp=sharing<img width="1370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejFXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59bb19921b490908a71b42cda9f9bc80a8508777/Screenshot%202024-02-13%20at%204.46.45%E2%80%AFPM.png" alt="Screenshot 2024-02-13 at 4.46.45 PM.png" />

**Comment by eporter23** [comment]
Hi @CB987 looks good, thank you! A couple of comments/questions for when we build this out:

1. Would it be possible to add more vertical padding/margins to the top and bottom of the search box element so that it isn't so close to the horizontal gray divider lines? 
2. Can we align the drop-down arrows with the text for Login and language selection? The arrows seem lower than the baseline for the text.
3. With the Emory shield and the bottom gray border, let's keep an eye on that to see if we may need to add some more margin below the header when we look at how the page content appears below it.  (We had some issues with that on digital.library.emory.edu and ended up removing that bottom border)

**Comment by CB987** [comment]
Got it. Absolutely!
