### ISSUE TITLE
Editing a work causes a Visibility change prompt, even if Visibility does not change

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#280]
This is a bug already documented for Hyrax, but if we are able to resolve it, that will help with our ongoing development and testing.

https://github.com/samvera/hyrax/issues/6537

**Comment by abelemlih** [comment]
PR ready for review: https://github.com/emory-libraries/dlp-selfdeposit/pull/296

**Comment by eporter23** [comment]
@abelemlih I haven't been able to test this yet due to the bug when editing works that I identified in #309.

**Comment by eporter23** [comment]
Thank you for fixing this Hyrax bug!
