### ISSUE TITLE
Install/configure Bulkrax

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#286]
This work follows the spike ticket to assess compatibility for Bulkrax with Hyrax 5 and Valkyrie.

As a first step, we want to do the basic installation of Bulkrax.

Definition of done:

- [x] We install Bulkrax as a gem and can see it in the UI
- [x] Configure the metadata as we currently have defined in the form
- [x] We should be able to load an object with required metadata

**Comment by eporter23** [comment]
We will start with the manually created zip file approach first.

**Comment by bwatson78** [comment]
I've just hit a wall with this work. Apparently, this has been customized for Postgres, and certain queries made for Bulkrax are Fedora incompatible. More to come.

**Comment by abelemlih** [comment]
PR approved and merged, ready to deploy

**Comment by eporter23** [comment]
Working great so far @bwatson78 ! One question: if I want to assign a work to the OpenEmory collection in oe24-test during import, plugging in the UUID for the collection (e4ce0baf-47eb-419f-9c46-a70a21ad43b5) in the "parent" column doesn't seem to do the trick. Any insights?

**Comment by bwatson78** [comment]
That "should" work. I know that the association to parent still happens later in the chain of events, so that may be a delayed assignment. I know that it worked for me locally. If this behavior persists, can you write up a bug ticket for it?

**Comment by bwatson78** [comment]
I also know that if the Collection is private and the Work is public, it will hide any trace of the containing collection on a non-admin's show page.

**Comment by eporter23** [comment]
The OpenEmory collection is public. I wrote up a "part 2" ticket where we can look at the Collection assignment along with a couple of other refinements. Looks great so far!
