### ISSUE TITLE
Additions to Collection Metadata

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#287]
This ticket follows initial work in #136 to review the Hyrax collection metadata vs. Curate's metadata and also Self Deposit's work-level metadata. Some of these fields will be new because we have not identified them as needed at the work-level.

The following should be added, using Curate and/or Hyrax equivalents:

**description** (restore from Hyrax MD?)
http://purl.org/dc/elements/1.1/description
Primary field
Requirement: Required
Form position/order: please display after the Creator entry

**subject_geo** (Subject - Geographic)
http://purl.org/dc/elements/1.1/coverage
QA lookup using GeoNames
Secondary field
Requirement: Optional
Form position/order: please display after the Subject entry

**subject_names** (Subject - Names)
http://purl.org/dc/elements/1.1/subject#names
QA lookup using LC Name Authority File
Secondary field
Requirement: Optional
Form position/order: please display after the subject_geo entry

**Comment by abelemlih** [comment]
@eporter23 for each field, could you please add the following:
- whether the field is primary or secondary
- whether the field is required or not
- the exact position of the field on the page

Thanks!

**Comment by eporter23** [comment]
@abelemlih I've refined the description above, but please let me know if you need more information, and thanks for prompting me to provide more details!

**Comment by abelemlih** [comment]
@eporter23 thanks!

**Comment by eporter23** [comment]
Looks great @abelemlih !
