### ISSUE TITLE
Ensure EFS mount for OE24 exports are accessible via SSH

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#289]
In previous tickets we configured and tested this, but when I was ssh-ing into the OE24 directory this morning, the connection at this path on libetdappprod1 seems to hang or gives an error:

ssh: Could not resolve hostname libetdappprod1.library.emory.edu:/mnt/efs/OE24: nodename nor servname provided, or not known

**Comment by eporter23** [comment]
Tried again by ssh to root, then cd to /mnt/efs/OE24, and it is working.

**Comment by jcrompton42** [comment]
updated the security groups for the efs (I was trimming them down for the security review and got one too many)

**Comment by eporter23** [comment]
@jcrompton42 @bwatson78 I want to double check on this, which also relates to #125 - when I go into /mnt/efs/OE24, I can see a prod and qa directory and a test file directory, but no actual Fedora 3 data, just empty directories? <img width="684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGpxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8aa0adffdf6ab03a1f781c5d5694b7452bc6d5c8/Screenshot%202024-05-16%20at%201.04.29%E2%80%AFPM.png" alt="Screenshot 2024-05-16 at 1.04.29 PM.png" />

**Comment by eporter23** [comment]
Let me know if this is a new ticket, in that I was expecting the Fedora 3 exported files to be copied to EFS.
