### ISSUE TITLE
Display all populated metadata on View Work page (first pass)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#292]
For this ticket, we want to ensure that our customized metadata displays on the View Work page.

In future tickets we will continue to refine the interface and add any additional display behaviors needed for selected fields, and also will later add Preservation Events and Worfklows to the display.

- [x] All populated metadata should be shown on the form
- [x] Metadata should be listed in the same order as the fields' order on the form (instead of alphabetically)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/301

**Comment by eporter23** [comment]
Looks great @bwatson78 !
