### ISSUE TITLE
Ensure exports from Fedora prod are stored in EFS mount

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#293]
When trying to test our prior tickets related to exporting data from Fedora 3 production and our new EFS staging space for these exports, I do not see actual data being populated in EFS (see screenshot below).

See also [this readme](https://github.com/emory-libraries/dlp-selfdeposit/blob/cc23a88711498d3c588438eea16371c249fd64e3/lib/fedora/MIGRATE_FEDORA3_OBJECTS_TUTORIAL.md?plain=1#L3) for how to run the export tool.

For this ticket, we want to: 

- [x] run the Fedora 3 export function on a single ID from production data (example:` emory:tnkj3` or [other IDs on this list](https://docs.google.com/spreadsheets/d/1qLzdhhOIXj9ebPAS58qWpWLUD8SMXGeIjR9re0qTfMQ/edit#gid=0))
- [x] Check to see that the exported files get written to /mnt/efs/OE24/prod

Screenshot showing no data on EFS

<img width="684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGpxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8aa0adffdf6ab03a1f781c5d5694b7452bc6d5c8/Screenshot%202024-05-16%20at%201.04.29%E2%80%AFPM.png" alt="Screenshot 2024-05-16 at 1.04.29 PM.png" />

**Comment by bwatson78** [comment]
@eporter23 Which environment and path is the export script being processed?

**Comment by eporter23** [comment]
I was able to download an export that @bwatson78 ran using a single production Fedora 3 object. The object was stored in /mnt/efs/OE24/prod/test_prod_file/emory_q4fd0 and contained all the expected files.

**Comment by bwatson78** [comment]
Created ticket for symlink to simplify the import location.https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/297
