### ISSUE TITLE
Automate assignment of OE Admin Set and OpenEmory Collection to Publication works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#295]
If a self-depositor who is not an Admin deposits a work, we do not want them to have to understand the Hyrax Relationships tab which prompts them to select an Administrative Set as well as a Collection.

Sequentially, the assignment of the Administrative Set is what triggers the workflow and visibility options shown to a depositor, so this needs to occur before users begin entering data.

The goal of this ticket is to automate the following steps when Publication is selected as the Work Type:

- [x] Assign the new work to the customized OpenEmory Admin Set that contains the deposit workflow
- [x] Assign the new work to the OpenEmory collection

Additionally, if feasible:

- [x] Do not show the Relationships tab of the Work Form to non-admin users

NOTE: If we have to rely on a name only, I have made sure the naming convention between arch and test for the Admin Set and Collection instances is consistent, and I will make this consistent for prod. 

Screenshot of desired behavior from Test environment:

<img width="964" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHNJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a378cfc9d4ebec02a98fa88a56c002c810d0de6/Screenshot%202024-05-23%20at%2011.13.32%E2%80%AFAM.png" alt="Screenshot 2024-05-23 at 11.13.32 AM.png" />

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/346

**Comment by eporter23** [comment]
@bwatson78 I was able to create a [new work](https://oe24-test.libraries.emory.edu/concern/publications/857fa420-e9f3-4dbf-9a10-d9fa97bc3bf6?locale=en) just now in oe-test while logged in as basic_user (non-Admin). The Relationships tab is not visible in the form to that user, but, it did get assigned to the Default Admin Set instead of the OpenEmory Admin Set and it also did not get assigned to the OpenEmory Collection.

**Comment by bwatson78** [comment]
My apologies, I forgot to assign new ENVs with the collection and admin set IDs doing that right now and redeploying.

**Comment by eporter23** [comment]
Looks great! Just checked this in oe24-test.
