### ISSUE TITLE
Symlink Uploads folder to EFS mount during deploy

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/dlp-selfdeposit#297]
So that imports from Fedora can be stored in our mounted EFS folder, Capistrano should symlink `/opt/dlp-selfdeposit/current/uploads` to `/mnt/efs`. That way, we could fire off the import command from our root application and not the actual mount.

**Comment by eporter23** [comment]
This relates to a bug resolved in #138 - we need to make sure it works in the local/docker environment.

**Comment by eporter23** [comment]
See also these notes for how to test locally: https://docs.google.com/document/d/1a_Jp0PPm9OnQTAZRI-I9z1mPv8kw7LLMRsqJKWSwFWE/edit#heading=h.gwz039b925aa

**Comment by abelemlih** [comment]
@eporter23 I followed the testing instructions above and everything works as expected on my local environment. This ticket is ready to close.
