### ISSUE TITLE
Styling for form input labels

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#299]
When a user is interacting with the Create New Publication work form, the field labels preceding the inputs have no visual contrast with the entries/guidance text themselves, and it can make it difficult to scan.

Recommendation: increase the font weight on the field labels so they have more contrast against the rest of the text on the form, or find another visual styling approach that creates distinction between the form labels vs guidance text and entries text.

**Current display**

<img width="739" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEFCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e688ecc7fe80f872ec64288904a0823bb6ba10ec/Screenshot%202024-05-22%20at%209.38.50%E2%80%AFAM.png" alt="Screenshot 2024-05-22 at 9.38.50 AM.png" />

**Example with increased contrast via font-weight and dark gray text color**

<img width="1660" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejhCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d44fa202efc5d101475f1e6e26096c60ecd8b26/Screenshot%202024-05-22%20at%209.49.20%E2%80%AFAM.png" alt="Screenshot 2024-05-22 at 9.49.20 AM.png" />

**Comment by maxdmayhew** [comment]
<img width="1403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemdFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb559cee02481195bec38b5fbb58f9c8bb29bc16/Screenshot%202024-05-22%20at%205.32.54%E2%80%AFPM.png" alt="Screenshot 2024-05-22 at 5.32.54 PM.png" />

<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejBFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b07a9642bb13a72a8a5492ec6e64702a9317ecf/Screenshot%202024-05-22%20at%205.34.25%E2%80%AFPM.png" alt="Screenshot 2024-05-22 at 5.34.25 PM.png" />

<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEFFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b2f8a856b4682ec7500726693ffb9f678848d90/Screenshot%202024-05-22%20at%205.35.48%E2%80%AFPM.png" alt="Screenshot 2024-05-22 at 5.35.48 PM.png" />

switched to a 2 column layout so things aren't as cramped.

https://github.com/emory-libraries/dlp-selfdeposit/pull/302

**Comment by eporter23** [comment]
@maxdmayhew for the 2 column layout, please note that some records will have many authors (over 20). Will this layout make that more challenging to work with? If we keep the 2 column layout, we may need to make some kind of visual separation between the entries for each author.

**Comment by eporter23** [comment]
@maxdmayhew the form label styling looks great so far. There one label seems to not be picking up the styling however: 

content genre (at the very top of the form)
<img width="494" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW9XQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3473f825865f0b3e2a16aae0c28052f0e207d327/Screenshot%202024-05-28%20at%208.54.02%E2%80%AFAM.png" alt="Screenshot 2024-05-28 at 8.54.02 AM.png" />

**Comment by maxdmayhew** [comment]
<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHdmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--776da387f2bb350f83eb00e78185600c96fa434e/Screenshot%202024-05-29%20at%203.14.43%E2%80%AFPM.png" alt="Screenshot 2024-05-29 at 3.14.43 PM.png" />
updated

**Comment by eporter23** [comment]
@maxdmayhew form labels look great! I am noticing an issue with the Authors section where if you click on Add Another Creators, the form no longer displays the options to add more entries. I'm not sure if this is related to the change in the layout, but can we re-set the Authors fields to be in a single row again to check it out?
