### ISSUE TITLE
Investigate options to export files from Fedora 3

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#30]
As a first step in this epic, we should research options to extract/export the data files themselves. In future tickets we will determine the best approach for extracting metadata from those files.

For each object exported, we want to get a copy of all the data streams for the Fedora object, and also the AUDIT.xml file. The AUDIT file is not listed as a data stream in the links provided below, but we observed it being copied as part of the Fedora 3 to 6 migration-utils.

For each object, there can be up to 10 files. For this ticket, we should determine if we can capture all of them. In future tickets we will refine the process so that we only capture those files we need to preserve long term.

**Initial acceptance criteria:**
One approach may be a command line tool that:

- Takes a selected set of IDs
- Downloads all datastreams for that ID
- Stores them in a directory with the naming convention of the ARK id after the `emory:` prefix - example: For `/emory:q4fd0/`, create a directory named `q4fd0` and store all the data stream files there
- Determine if the AUDIT xml file can be accessed as well as the other regular data streams
- Review what the filenames are and note if they contain a file extension such as PDF or XML, or none is assigned

**Data**
Look at using the 10 data samples from the Fedora 3 QA environment. [This worksheet](https://docs.google.com/spreadsheets/d/1qLzdhhOIXj9ebPAS58qWpWLUD8SMXGeIjR9re0qTfMQ/edit#gid=1142298975) includes notes about the path to the Fedora object and how many data streams are expected for each. NOTE: the total number of data streams does not include the AUDIT.xml file.

https://testopen.library.emory.edu/publications/emory:q4fd0/
https://testopen.library.emory.edu/publications/emory:fjhxt/
https://testopen.library.emory.edu/publications/emory:dzmbk/
https://testopen.library.emory.edu/publications/emory:gjs96/
https://testopen.library.emory.edu/publications/emory:pqpg4/
https://testopen.library.emory.edu/publications/emory:fm17r/
https://testopen.library.emory.edu/publications/emory:gj35k/
https://testopen.library.emory.edu/publications/emory:fj9p7/
https://testopen.library.emory.edu/publications/emory:pqqq6/
https://testopen.library.emory.edu/publications/emory:gjpc5/

**Comment by bwatson78** [comment]
[Chatted with Scott Prater](https://fedora-project.slack.com/archives/C8B5TSR4J/p1708353728461679) from the Fedora Project today, and he advised us to use the `fedora-export` tool with the `econtext` of `archive` to pull all of the files we're looking for (including `AUDIT.xml`). He also mentioned that the binaries would come out in base64 encoding, so that we'd have to decode them after receiving them from the CLI tool. He also hyped the migration tool when I mentioned we were going to Fedora6 with the objects, but explained to him that wasn't an option in this case.

**Comment by bwatson78** [comment]
Created https://github.com/emory-libraries/dlp-selfdeposit/pull/52 as prototype. `AUDIT.xml` is pulling the pure XML string from `fedora-export`'s "migrate" XML. We will need to circle back to this document if our intention is to import it into the new Fedora 6 objects. We will have to verify with Lyrasis how to structure the importing XML to be compliant and readable.

**Comment by eporter23** [comment]
@bwatson78 My goal for the AUDIT file is to retain/persist it but not do anything systematic with it, in case that helps.

**Comment by bwatson78** [comment]
@eporter23 I have to install the Fedora Client software on the server before this can work in that environment, and Collin wants Beth to collaborate with that software install, so I have to wait until Thursday, when she comes back. Moving this into blocked for that reason.

**Comment by bwatson78** [comment]
@eporter23 https://emory.sharepoint.com/:u:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/01%20Active%20Project/OpenEmory%20Phase%202/02%20Planning%20and%20Execution/02%20Technical%20Documentation,%20Drawings%20%26%20Diagrams/Migration%20Planning/emory_q4fd0.zip?csf=1&web=1&e=FjIBmc

**Comment by eporter23** [comment]
Looks great @bwatson78 ! No issues opening any of the files, and they correlate with what I'd expect to see for that particular work. I may have some questions for you about the filenames so we can figure out what the "content" data stream (primary) file is.

**Comment by bwatson78** [comment]
Making changes to `content` filename as discussed in Sprint Planning 3/6/2024.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/99

**Comment by bwatson78** [comment]
[emory_q4fd0.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGEvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79727245bf366d03e4a4a62b87577861d72caab9/emory_q4fd0.zip)

**Comment by eporter23** [comment]
Looks great! Closing this and will write up a separate ticket for other work required to implement.
