### ISSUE TITLE
Customize form field behavior for Articles

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#300]
This ticket follows work done in #181 where we want the work form to present certain inputs depending on the type of Publication (content_genres) being submitted. This behavior will be added on top of fields that are always required for all Publications.

For this ticket we want the following:

**Prompt users to populate the following fields if they have selected Article as the Type of Publication (content_genres). These fields are not required for all types of Publications, but need to be populated for Articles**.

- [x] publisher_version
- [x] parent_title

**Hide the display of selected fields that aren't applicable to Articles.** 

- [x] conference_name
- [x] isbn
- [x] series_title
- [x] edition

**Comment by eporter23** [comment]
@maxdmayhew I wasn't thinking so much of a popup type alert so much as in-form validation warning. Happy to chat more about it, as I'm sure there are multiple ways we could approach it.

**Comment by maxdmayhew** [comment]
https://github.com/emory-libraries/dlp-selfdeposit/pull/319

**Comment by maxdmayhew** [comment]
currently the script has some console.log statements in them. These need to be removed at some point.
