### ISSUE TITLE
Unspecified form error when editing works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#309]
**Describe the bug**
After our deployment on 5/23, I am receiving a non-specific form error message when trying to edit existing works.

**To Reproduce**
1. Login as Admin user
2. Go to the Dashboard and select Works
3. Select any work
4. Edit the work
5. Make a metadata entry, and make sure the green checkbox for Describe your work shows that all required entries are populated
6. Save the work
7. See `"   can't be blank"` error message in a red banner above the form

**Expected behavior**

If all required fields have been populated, a user should be able to save changes to the work.

**Screenshots**

<img width="1823" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWdXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bada8170c39c0c16ebd1046a3c4d0c7cad3311b/Screenshot%202024-05-28%20at%208.50.49%E2%80%AFAM.png" alt="Screenshot 2024-05-28 at 8.50.49 AM.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abelemlih** [comment]
Fix deployed to Arch/Test, ready for testing.

**Comment by eporter23** [comment]
Thanks @abelemlih !
