### ISSUE TITLE
Create EC2 for Hyrax in arch

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#31]
Setup the EC2 itself

- fedora-depo-arch/ will take you to Hyrax
- fedora-depo-arch:8443/fcrepo/rest will take you to Fedora

In preparation for the Hyrax installation, we will also need: 

- Ruby manager (we will use what we use in other instances)
- Passenger
- Webserver
- Git
- SSH

**Comment by jcrompton42** [comment]
hyrax ec2 created and available at fedora-depo-arch.libraries.emory.edu. Passenger module and gem installed, ruby 3.1.2 is the current ruby version.

**Comment by eporter23** [comment]
Thanks @jcrompton42 ! I see Apache goodness.
