### ISSUE TITLE
Errors when creating new works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#310]
**Describe the bug**
While testing the process of creating a new work after the 5/23 deploy and trying to fill out all the form fields, I am receiving 2 errors while going through the process (in the test environment).

**To Reproduce**
1. Sign in as Admin user, go to Dashboard > Works > Create New Work
2. Fill out every field in the Publication accordion section
3. Try to open the Additional Information accordion and note that it will not open
4. Save the work
5. See Argument Error message

**Expected behavior**
Creating a work with all required data and files populated should not result in an error.
All accordions should be able to be opened by admin users.

**Screenshots**

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVFYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc61f31834b9593fb1f0006a2c52f030960a0123/Screenshot%202024-05-28%20at%2011.06.40%E2%80%AFAM.png" alt="Screenshot 2024-05-28 at 11.06.40 AM.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abelemlih** [comment]
@eporter23 With the newest version of main (deployed to Arch/Test), I was able to create a new publication with all fields locally, and fill in additional information (accordions did open). Could you please verify if this is still an issue? My fix for #309 may have fixed any issue previously encountered saving a publication.

**Comment by eporter23** [comment]
Thanks @abelemlih - I tested on 2 new works and it looks great!
