### ISSUE TITLE
Samvera support work for Hyrax 5 and Fedora 6.5 compatibility

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#314]
See also our prior local workaround for supporting Fedora 6.5 with Hyrax 5: #203

The goals of this ticket will be to:

- [ ] Submit a PR to Hyrax
- [ ] Ensure we support backward compatibility

**Comment by abelemlih** [comment]
PR: https://github.com/samvera/hyrax/pull/6825

I reached out to Daniel and Randall for feedback on Samvera Slack.

**Comment by abelemlih** [comment]
Fixed all the specs in the PR and now it is ready for another review

**Comment by abelemlih** [comment]
@eporter23 I attended the Samvera weekly call, and Daniel mentioned that there are CI related tickets that are currently blocking the approval of this ticket. As far as timeline goes, Daniel estimated end of next week, during the Hyrax maintenance sprint, as possible timeline for this ticket's PR in Hyrax to be merged.

**Comment by abelemlih** [comment]
I reached out to Daniel Pierce for another review on the [PR](https://github.com/samvera/hyrax/pull/6825), and have not heard back. I will attend tomorrow's tech call to ask for a review.

**Comment by abelemlih** [comment]
@eporter23 Daniel Pierce will pull the branch and test the changes, and get back to us by end of week.

**Comment by abelemlih** [comment]
@eporter23 PR approved and merged into Hyrax. This ticket is ready to close.
