### ISSUE TITLE
NoMethodError when creating new works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#317]
**Describe the bug**
After our latest deploy on 5/31, creating new works using our approval workflow results in an error. This also seems to be affecting the ability to edit existing works as well as editing an existing Collection.

**To Reproduce**
1. Login as Admin
2. Create a new work and fill out all required metadata and upload a file
3. Go to the Relationships tab and assign the OpenEmory custom Admin set with workflow
4. Submit the work
5. Approve the deposit
5. See NoMethodError

Additional note: if I hit the back button in my browser, the work appears, but still shows as under review. So it appears that the work is being created, but can't make it through the approval steps in the workflow.
Also, I am seeing a default UUID pattern for the ID and not our custom NOID pattern.

Here is the work I created that can't get past the approval step: https://oe24-test.libraries.emory.edu/concern/publications/43e8e58f-9b6c-4ecf-9e73-bdfa0aa828dc?locale=en

**Expected behavior**
A work should be created without errors

**Screenshots**

<img width="1749" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0VwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6d2e8ca595d9bd3f9542d067c8105a06ddb6b29/Screenshot%202024-05-31%20at%2011.11.35%E2%80%AFAM.png" alt="Screenshot 2024-05-31 at 11.11.35 AM.png" />

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/318
