### ISSUE TITLE
OpenEmory transforms: batch 1 - simple transforms

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#320]
This ticket includes multiple XML transformations for selected fields. For now, we can start with straightforward transformations - more complex ones (with yellow highlights on the worksheet) will be addressed in separate tickets.

The following fields' data is stored in the descMetadata (MODS) XML file for each work that we export.

The goal for this ticket would be to:

- [ ]  create a script that can pull the data from a sample export from OpenEmory, takes the data, parses it and can write it to a CSV file. The column names should correlate to the attribute names needed for Bulkrax import.
- [ ] The initial step for this could be to have it operate on a single folder/package as opposed to iterating across multiple paths - which would be future work.
- [ ] This script could be run as needed, but does not need to be incorporated into the Hyrax UI. 
- [ ] CSVs generated by the script should use pipe separated instead of comma separated for multi-valued fields (creators, subjects, etc.)

For sample data, we can work from the [Sample Objects for Migration](https://docs.google.com/spreadsheets/d/1qLzdhhOIXj9ebPAS58qWpWLUD8SMXGeIjR9re0qTfMQ/edit?gid=0#gid=0) worksheet. For a single starter object please use the following production object's ID to export and transform: emory:t5nbh.

Please see this [filtered view of the Metadata Implementation - Objects worksheet](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589&fvid=1424344959) for easier access to information about OpenEmory specifically. The OE xpath column includes a starting point for how to select the data needed, but please revise the xpath as needed.

- [x] title
- [x] holding_repository
- [x] content_genres
- [x] creator
- [x] abstract
- [x] date_issued
- [x] keywords
- [x] subject_topics
- [x] parent_title
- [x] series_title
- [x] publisher
- [x] final_published_versions
- [x] issue
- [x] page_range_start
- [x] page_range_end
- [x] volume
- [x] edition
- [x] place_of_production
- [x] issn
- [x] conference_dates
- [x] conference_name
- [x] author_notes
- [x] rights_statements
- [x] emory_ark
- [x] research_categories

**Comment by bwatson78** [comment]
@eporter23 `subject_topics` isn't assigned any xpath data in the spreadsheet.

**Comment by bwatson78** [comment]
@eporter23 If I'm reading the sheet right, `conference_dates` shouldn't be extracted?

**Comment by bwatson78** [comment]
Emily, just a reminder that we are using `rights_statement` for OE, not `emory_rights_statments`

**Comment by eporter23** [comment]
@bwatson78 for subject_topics, correct. This is because we're mapping the legacy subject terms to the new research categories field.

**Comment by eporter23** [comment]
@bwatson78 for conference_dates, we want to extract that, but store the value in date_issued. We combined date_issued and conference_dates in the new work type.

**Comment by bwatson78** [comment]
@eporter23 I need objects that have the xpaths for page_range_*, edition, place_of_production, conference_name, and rights_statement.

**Comment by eporter23** [comment]
Conference Dates doesn't need its own column. I will report back with examples for your second comment.

**Comment by eporter23** [comment]
Page ranges:` emory:t5nbh`
Place of production:` emory:s8jqw`
Conference Name: `emory:rr0z4`

**Comment by eporter23** [comment]
For rights_statement, I likely got my wires crossed. For the rightsstatement.org controlled values field that exists in Hyrax and Curate, this data will not exist in legacy data but we want to create a default value of "In Copyright" for that attribute. For the free-text copyright statement (rights_notes aka emory_rights_statements), that should be found in pretty much every work in legacy OpenEmory but I will add that to the part 2 ticket. Or, let me know if I should move both of those to pt 2.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/363

**Comment by eporter23** [comment]
Discussed with Brad today that in some cases (e.g. conference_name for posters or presentations) the expected xpath (per MODS standards) is not working because multiple elements may be inserted into a single MODS element and manual cleanup may be required. Since we have very few non-articles, we can try to track these manually for cleanup.

**Comment by eporter23** [comment]
@bwatson78 is there anything I can test for this ticket?

**Comment by eporter23** [comment]
I looked at the latest CSV you sent me and it looks good! One note: for `emory_content_type`, I have notes about that field in the other ticket which I'm still getting ready. I'm assuming you put that in this as part of this ticket because it's a required field.
