### ISSUE TITLE
Persistent URLs

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#322]
This ticket will follow work to support our own minted ID scheme. While we are not able to utilize the ID scheme directly in Hyrax/Fedora, we do want to ensure that we provide a persistent URL that is more human usable than UUIDs.

Proposed pattern:
/purl/ + local ID 

For this ticket we should ensure:

- [x] A persistent URL is generated for Collections
- [x] The persistent URL is displayed on Collection view pages (public and Dashboard)
- [x] A persistent URL is generated for Works
- [x] The persistent URL is displayed on Collection view pages

**Comment by eporter23** [comment]
@alexBLR and I discussed in Slack that we will also ensure that alternate_ids needed for the above requirements are also indexed in SOLR. I recommended that we don't need to do this for FileSet IDs because they are more subject to change, and for that reason I didn't include FileSets in this ticket's requirements for purls.

**Comment by alexBLR** [comment]
<img width="870" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzJxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1baad3e04dcbc37de6fe26c3359fdd81c9b3a6cd/Screen%20Shot%202024-07-02%20at%2011.59.47%20AM.png" alt="Screen Shot 2024-07-02 at 11.59.47 AM.png" />

**Comment by alexBLR** [comment]
<img width="999" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fea9b2ca2371ceaf8a2ca80ce4644a7ba220112/Screen%20Shot%202024-07-02%20at%2011.59.33%20AM.png" alt="Screen Shot 2024-07-02 at 11.59.33 AM.png" />

**Comment by eporter23** [comment]
@alexBLR I'm seeing the Persistent URLs in arch now and they look good. I am seeing an issue when I try to load the generated URL, though ([see example work in Arch](https://oe24-arch.libraries.emory.edu/concern/publications/a178fe30-a083-41fe-8d6d-9bdcf1c403f1?locale=en)). If I click on the URL directly or copy it into a new window, it returns a NoMethodError -see below: 

<img width="1736" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFhLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80bc56cc8b9fb8db2ceb3e5401856b91a304b57d/Screenshot%202024-07-10%20at%208.46.50%E2%80%AFAM.png" alt="Screenshot 2024-07-10 at 8.46.50 AM.png" />

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/403

**Comment by eporter23** [comment]
Working as expected now, thanks!
