### ISSUE TITLE
fcr:metadata not found in fedora-depo-test

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#325]
When trying to view certain levels of objects in the test environment, I encounter a Fedora error saying fcr:metadata not found. Note: this does not occur in the arch environment, only in test.

As of today, I am finding that trying to browse the objects in /rest/production continually returns this error.

To reproduce:

1. Navigate to https://fedora-depo-test.libraries.emory.edu/fcrepo/rest/production/
2. Click on any linked ID in the list of children
3. See error

**Comment by bwatson78** [comment]
@jcrompton42 Since it's every object, can you try a restart and/or reindex on this server?

**Comment by eporter23** [comment]
So far so good @jcrompton42 - thank you!
