### ISSUE TITLE
Move rights_statement field into Administrative Metadata section of form

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#327]
After discussions with SCO, we want to reduce complexity of data entry for depositors related to the various rights and license information. In order to accommodate both this and the established Curate/DLP metadata requirements, we to make the following adjustments:

- [ ] Move rights_statement field into Administrative Metadata section of the form (it is currently in the Publication Information section)

**Comment by eporter23** [comment]
This could go either into the first or last position in terms of the form field display order.

**Comment by maxdmayhew** [comment]
https://github.com/emory-libraries/dlp-selfdeposit/pull/329
