### ISSUE TITLE
Create system architecture diagram

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#33]
As we build out our first reference environment (arch), we should also create a working system architecture diagram. This will benefit us for long-term documentation needs as well as to prepare for upcoming ART/Security reviews.

**Comment by rotated8** [comment]
New Diagram: https://lucid.app/lucidchart/21a529d5-aa77-44fb-ad78-397c9bd8b082/edit?viewport_loc=-209%2C39%2C2219%2C1079%2C5lzbCm6EAc-j&invitationId=inv_33e9bc7f-5fa1-45e5-a9f3-36c9ff0c5277

**Comment by jcrompton42** [comment]
Looks good! I have one question @rotated8: the way you have drawn this it appears that shibboleth authentication is being done on a separate ec2 instance. Is that the plan?

**Comment by eporter23** [comment]
Thanks @rotated8 ! I wanted to ask about the BG jobs EC2. Is this something we already have setup, or something that we need to write tickets for?

**Comment by eporter23** [comment]
Discussed in standup: some components are not yet implemented including the BG jobs EC2. We can update the diagram later depending on where we end up.
