### ISSUE TITLE
Customize form field behavior for Books

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#333]
This ticket follows work done in #300 and #181 where we want the work form to present certain inputs depending on the type of Publication (content_genres) being submitted. This behavior will be added on top of fields that are always required for all Publications.

For this ticket we want the following:

**Prompt users to populate the following fields if they have selected Book as the Type of Publication (content_genres). These fields are not required for all types of Publications, but need to be populated for Books.**

- [x] publisher_version

**Hide the display of selected fields that aren't applicable to Books.**

- [x] parent_title
- [x] conference_name
- [x] issn
- [x] volume
- [x] issue
- [x] page_range_start
- [x] page_range_end

**Comment by maxdmayhew** [comment]
https://github.com/emory-libraries/dlp-selfdeposit/pull/337
