### ISSUE TITLE
Customize form field behavior for Book Chapters

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#335]
This ticket follows work done in #300 and #181 where we want the work form to present certain inputs depending on the type of Publication (content_genres) being submitted. This behavior will be added on top of fields that are always required for all Publications.

For this ticket we want the following:

**Prompt users to populate the following fields if they have selected Book Chapter as the Type of Publication (content_genres).** These fields are not required for all types of Publications, but need to be populated for Book Chapters, which are only a single chapter from a larger book publication.

- [x] publisher_version
- [x] parent_title

**Hide the display of selected fields that aren't applicable to Book Chapters.**

- [x] conference_name
- [x] issn
- [x] volume
- [x] issue

**Comment by maxdmayhew** [comment]
https://github.com/emory-libraries/dlp-selfdeposit/pull/341
