### ISSUE TITLE
BUG: Cannot Create a New Collection of Either User or Library Type

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/dlp-selfdeposit#336]
When attempting to create a Collection object of either User or Library, the following error appears:
<img width="957" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0ZPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0a095b56c1b0eb20bb1dee56d0e34d925521ff6/Screenshot_20240610_142931.png" alt="Screenshot_20240610_142931.png" />

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/344

**Comment by eporter23** [comment]
Just retried this on oe-test and I'm getting this error: <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzE4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b3f84672428ecf79221d86ee278bdb5a494b037/Screenshot%202024-06-20%20at%2010.42.32%E2%80%AFAM.png" alt="Screenshot 2024-06-20 at 10.42.32 AM.png" />

**Comment by bwatson78** [comment]
Bug fix incoming.

**Comment by bwatson78** [comment]
PR https://github.com/emory-libraries/dlp-selfdeposit/pull/354 should have fixed this.
