### ISSUE TITLE
Customize form field behavior for Presentations and Posters

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#339]
This ticket follows work done in #300 and #181 where we want the work form to present certain inputs depending on the type of Publication (content_genres) being submitted. This behavior will be added on top of fields that are always required for all Publications.

For this ticket we want the following:

**Hide the display of selected fields that aren't applicable to Presentations and Posters. These two content_genres follow the same pattern.** 

- [x] issn
- [x] isbn
- [x] series_title
- [x] edition
- [x] volume
- [x] issue
- [x] page_range_start
- [x] page_range_end

**Comment by maxdmayhew** [comment]
https://github.com/emory-libraries/dlp-selfdeposit/pull/347

**Comment by eporter23** [comment]
Looks great so far @maxdmayhew ! I ran into bug #355 which could be related to various other work so I will leave this open for now.
