### ISSUE TITLE
Setup Capistrano for deployment

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#35]
This ticket is a prerequisite for us to be able to deploy/install Hyrax on our new EC2s.
NOTE: this ticket may exceed our preliminary estimates due to unknowns.

A stretch goal is to avoid using the cap-ec2 gem if we can avoid it.

**Comment by abelemlih** [comment]
I am currently working on this ticket. So far I have a similar setup to that of DLP-curate, meaning we will still need to use the `cap-ec2` gem. My plan is to get a deployment setup working tomorrow, after I ask Beth for help with a few configuration steps on the server. Once we have a working setup, I can look further into the feasibility of not using the `cap-ec2` gem.

**Comment by abelemlih** [comment]
Beth and I are still debugging Postgres related issues, but are making progress towards a functional database for the Arch environment. Once the Postgres issues are fixed, we will be able to resolve migration related issues in the deployment process.

**Comment by eporter23** [comment]
Looks good @abelemlih! I think this ticket should be good to close but I will put it in To Review just in case others may want more info.
