### ISSUE TITLE
Error when creating new works via the UI form: NoMethodError in Hyrax::PublicationsController#create

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#355]
**Describe the bug**
When testing the process of creating a new work in the form on 6/20/24, I receive the below error when submitting.

**To Reproduce**
1. Go to oe24-test
2. Login as basic_user 
3. Go to the Dashboard > Works > Create New Work
4. Fill out all required metadata and upload a file
5. Assent to the deposit agreement and click save
6. See error

**Expected behavior**

**Screenshots**

<img width="1705" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU45QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36785906e125d9f8666cd135a1c581b5c64890ba/Screenshot%202024-06-20%20at%2011.43.41%E2%80%AFAM.png" alt="Screenshot 2024-06-20 at 11.43.41 AM.png" />

**Desktop (please complete the following information):**
 - Mac OS
 - Chrome

**Comment by maxdmayhew** [comment]
this seems to happen regardless of what type content genre you select. And as far as I can tell my validation script is not related to this issue. 

﻿ 
<img width="702" alt="image" src="https://github.com/emory-libraries/dlp-selfdeposit/assets/5154092/56f4c29f-e4e3-470f-9692-aca815d5097e">

**Comment by eporter23** [comment]
I did some testing again today, and I'm getting this error now - I'll add this to the PID ticket too: <img width="1804" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFdOQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a96fd708d68d3e4bb3097de7c2bd47eddc9adf45/Screenshot%202024-06-25%20at%209.51.16%E2%80%AFAM.png" alt="Screenshot 2024-06-25 at 9.51.16 AM.png" />

**Comment by bwatson78** [comment]
Fix should be in place. Let me know if this error is seen again.
