### ISSUE TITLE
Setup local development environment

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#36]
This may be dependent on using a Hyrax generator vs. having to build it manually. Sirenia may be a good starting point. Docker subscription is now available.

Goals:

- Ability to build and run the application locally
- Setting a docker configuration (Fedora 6, Postgres, SOLR, Rails server all in docker) - docker compose configuration
- Onboarding for team members using Docker Desktop and Sirenia

**Comment by abelemlih** [comment]
This is my first attempt at setting up a development environment, based on the Sirenia setup from Hyrax: https://github.com/abelemlih/dlp-self-deposit

As I receive feedback from other developers and test the setup further, I will focus on fixing any outstanding setup/configuration issues.
