### ISSUE TITLE
Show Preservation Events for Works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#361]
For this ticket, we want to enable display of any Preservation Events that are associated with an individual work when a user is viewing the record. 

Some aspects of this ticket may be similar to work done in #348 to display preservation events on the View FileSet page.

We previously added this capability to Curate, but for OpenEmory we may want to adjust the layout somewhat since it is public facing.

Please [see this mockup](https://docs.google.com/drawings/d/1Wv7PHPfZghz5h2SUq51Abycr06eGrALqKikxSZjcqJo/edit?usp=sharing) as an example.

- [x] Add new section to the page, following the Items list with the heading "Preservation Events".
- [x] Generate a table showing each preservation event for the work (see mockup)
- [x] Display the entries in the table listed as newest first (using the timestamp value)

**Comment by alexBLR** [comment]
<img width="1687" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3o3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--698f2defef2702dc54e58927867f0edac021b520/Screen%20Shot%202024-07-22%20at%201.47.59%20PM.png" alt="Screen Shot 2024-07-22 at 1.47.59 PM.png" />

**Comment by eporter23** [comment]
Thanks @alexBLR, looks great so far ! In your screenshot, some of the values are showing up under the wrong heading though. I took your screenshot and [mocked it up here with notes about the SOLR values](https://docs.google.com/spreadsheets/d/1S78sZzF5L5hBbK0FM3uGud33B2T0g6CTWKEqFGack3I/edit?gid=0#gid=0).

**Comment by eporter23** [comment]
@alexBLR looks good, thanks! @CB987 alerted me to the fact that Outcome and Detail columns and their values were switched in the View FileSet page so I am checking with her first to see if she will address it with work she's doing on the page layout in separate tickets.

**Comment by eporter23** [comment]
We'll address the above note in Clare's upcoming ticket. Thanks!
