### ISSUE TITLE
Additional form input data type validations

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#362]
Selected fields in the form should have additional validation logic to ensure the data is formatted correctly. If a user doesn't format the entries correctly, the form should prompt them to correct their entries.

**URI fields** - these fields must contain a full URL entry (starting with http://, https:// etc) only because they will be used as hyperlinks to external content.
- [x] related_datasets
- [x] final_published_versions

**Date Issued field** - entries in this field should be formatted to only allow entries in [W3C Date Time format](https://www.w3.org/TR/NOTE-datetime)/ISO 8601 format. 

- [x] YYYY (year only - a user must at least supply a 4 digit year)
- [x] YYYY-MM (year and 2 digit month only)
- [x] YYYY-MM-DD (year, 2 digit month and 2 digit day)

Examples of valid entries:

- 2024
- 2024-06 (note leading zero is required)
- 2024-06-26

**Comment by maxdmayhew** [comment]
Increasing estimate. This functionality will require a different approach since these fields are not always required but require formatting if they are filled out.

**Comment by eporter23** [comment]
Deployed to arch, will also be deployed to test.

**Comment by eporter23** [comment]
@maxdmayhew couple of things I'm seeing: 
1 - the date format should use hyphens as separators and not slashes
2 - I am seeing some glitchy behavior with all the fields (date and URLs) where if I incorrectly format the entry, it shows the modal. But then if I correct it, it shows the modal again BUT still triggers the save to the work. I can demo this for you if it would help!

**Comment by maxdmayhew** [comment]
met with emily, unable to reproduce error but will keep an eye out for it. switched to hyphens

https://github.com/emory-libraries/dlp-selfdeposit/pull/436

**Comment by eporter23** [comment]
Re-checked in test and I think everything is good!
