### ISSUE TITLE
Shibboleth - handling successful authentication

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#367]
For this ticket, we will work on the arch environment first (see #370). 

This ticket follows up on work done in #221.

Middleware will setup the initial configuration on arch.

Backend will work on the connection of Shibboleth to the Hyrax application.
Current issues are:
Duo and redirection back to Self Deposit.

https://shibboleth.atlassian.net/wiki/spaces/SP3/pages/2065335333/ApplicationIntegration

**Comment by kbowaterskelly** [comment]
I pasted what I believe to be the relevant documentation into the body of this ticket, but for reference, it is here: https://shibboleth.atlassian.net/wiki/spaces/SP3/pages/2065335333/ApplicationIntegration

@bwatson78 I suspect we may have to look at the implementation together and should have time available for that

**Comment by rotated8** [comment]
Here's Shib's docs about it's [Application Model](https://shibboleth.atlassian.net/wiki/spaces/SP3/pages/2065334314/ApplicationModel)

**Comment by eporter23** [comment]
Callback module has been implemented.

**Comment by eporter23** [comment]
Callback module needs additional work to take the application referrer tags but it isn't a blocker yet.

**Comment by tmill29** [comment]
@kbowaterskelly and @alexBLR will meet this afternoon. We will revisit closing this ticket when @rotated8 returns.

**Comment by rotated8** [comment]
Superseded by #601
