### ISSUE TITLE
Wipe data in arch and test to ensure custom ID scheme is set properly

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#368]
Starting with arch first:

- [x] Wipe the Postgres data
- [x] Wipe the SOLR collection for OE
- [x] Wipe Fedora 6
- [x] Wipe S3 data
- [x] Rebuild the above

Emily will recreate groups, custom admin set, custom collection type, etc based on prior setup tickets

Do test second and repeat the above

**Comment by eporter23** [comment]
@jcrompton42 everything looks good here - do you want to estimate it and then I'll add my time in too?

**Comment by jcrompton42** [comment]
Sure! Done. I ended up having to make some ansible adjustments.
