### ISSUE TITLE
Set up Shib on Application Server

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-selfdeposit#370]
- [x] Install and configure the Shibboleth SP on oe24-arch
- [x] Add SP installation/configuration to Ansible
- [x] Ask Gerry to update the metadata (if needed)
- [x] Add to Ansible playbook

**Comment by kbowaterskelly** [comment]
https://emorylib.atlassian.net/wiki/spaces/ULTS/pages/290160643/Shibboleth+deployment

**Comment by kbowaterskelly** [comment]
wasn't clear if oe24-arch meant oe24-hyrax-arch or fedora arch, but it shouldn't matter once we have a working playbook. 

playbook starter will be available on the wiki page above. 

asking gerry to update anything is not necessary as far as i know since our service provider url did not change.

**Comment by eporter23** [comment]
Next steps: will involve adding to an Ansible playbook to push the config files

**Comment by kbowaterskelly** [comment]
I am still troubleshooting this playbook. It mostly passes linting and should be ready pretty soon.

**Comment by kbowaterskelly** [comment]
https://github.com/emory-libraries/dlp-selfdeposit/commit/93a1c60d15193943b56f6d36807470dc9c11bda6

**Comment by tmill29** [comment]
@kbowaterskelly and @alexBLR will meet this afternoon. We will revisit closing this ticket when @rotated8 returns.

**Comment by rotated8** [comment]
Superceded by #600
