### ISSUE TITLE
Implement initial layout changes to View Work page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#372]
This ticket follows work done to create mockups for the View Work page (#204). For this ticket, we want to implement those changes to the basic Hyrax layout.

Note: we will also likely do more refinements on this page, so this will be a version 1 effort.

**Comment by CB987** [comment]
<img width="1204" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkc1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9adddfccd134a54266d3e43c1c9b5c5499b016c1/Screenshot%202024-07-05%20at%2012.44.57%E2%80%AFPM.png" alt="Screenshot 2024-07-05 at 12.44.57 PM.png" />
<img width="1257" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlM1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2bcd00f7e2d8effd04b32a99eca80fe06b0cf546/Screenshot%202024-07-05%20at%2012.45.27%E2%80%AFPM.png" alt="Screenshot 2024-07-05 at 12.45.27 PM.png" />
<img width="1815" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlc1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--303e44af9eb26b42d5662ae1fe1822e82f0def39/Screenshot%202024-07-05%20at%2012.46.17%E2%80%AFPM.png" alt="Screenshot 2024-07-05 at 12.46.17 PM.png" />

**Comment by CB987** [comment]
PR#[390](https://github.com/emory-libraries/dlp-selfdeposit/pull/390)

**Comment by eporter23** [comment]
Looks great @CB987 !

**Comment by eporter23** [comment]
@CB987 sorry but I just noticed the heading text on the "Tools" block isn't rendering in arch or test: 
<img width="462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDdLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f4a8ff89dfb391a73884d5607379f300d096546/Screenshot%202024-07-10%20at%209.43.52%E2%80%AFAM.png" alt="Screenshot 2024-07-10 at 9.43.52 AM.png" />

**Comment by CB987** [comment]
Strange! Will take a look, thanks!

**Comment by CB987** [comment]
should be fixed with PR#[399](https://github.com/emory-libraries/dlp-selfdeposit/pull/399)

**Comment by eporter23** [comment]
Thanks @CB987 !
