### ISSUE TITLE
Adjust access_rights vs. rights_notes in the form and model

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#374]
Due to some nomenclature and mapping mixups between our local metadata profile and Hyrax's current metadata, I've uncovered a fix that we need to make.

We have access_rights in place as required on the form currently, however, this is not the field and RDF predicate we want to use for free text copyright statements.

Instead, we should use rights_notes (http://purl.org/dc/elements/1.1/rights) to contain free-text rights statements. 

For this ticket please adjust the following:

- [x] Remove access_rights from the form
- [x] Make access_rights not required
- [x] Add rights_notes to the form
- [x] Make rights_notes required (always required for all Publications) 

Additional work that may be needed:
- [x] Adjust Bulkrax CSV template if needed
- [x] Adjust metadata transformation/extraction scripts if needed

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/381

**Comment by eporter23** [comment]
Suggestion: provide a README for the application. We have to know the IDs for the Admin Set and Collection and these need to be provided as the ENV variables.

**Comment by eporter23** [comment]
Looks great @bwatson78 - also please disregard the above comment which I clearly added to the wrong ticket.
