### ISSUE TITLE
Adjust display for creator and emory_content_type values

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#376]
For these 2 fields, we want to adjust how they display on the View Work page. 

- [x] **creator**

We also want the ability to display the creator entries in a more human readable format on the View Work page.

Example for View Work Page display: 
Current output: `Emily, Porter, Emory University, 0000-0002-2093-5650 `
Desired output: Emily Porter `{orcid icon with link - see below}`, Emory University

- If there is no ORCID ID populated, omit that segment and continue with a comma and then the institutional affiliation segment

- For the above author example, here is the recommended HTML snippet from the [ORCID branding guidelines - inline display section](https://info.orcid.org/brand-guidelines/): 

```
<p>Emily Porter <a href="https://orcid.org/0000-0002-2093-5650">
<img alt="ORCID logo" src="https://info.orcid.org/wp-content/uploads/2019/11/orcid_16x16.png" width="16" height="16" /></a>, Emory University</p>
```

See Codepen snippet: https://codepen.io/eporter23/pen/MWdNMbw

<img width="554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXl3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--808fda8124a1584a6e9c15d48d0d21e7aba4b756/Screenshot%202024-07-03%20at%2012.20.10%E2%80%AFPM.png" alt="Screenshot 2024-07-03 at 12.20.10 PM.png" />

- [x] **emory_content_type**

We have a local vocabulary with ids as URIs, but the term/label as a string.
For this field, we want the ability to display only the term and not the raw URI value. This is similar to how Creative Commons Licenses and Rightsstatement.org values are presented in Hyrax.

Example: 
id: http://id.loc.gov/vocabulary/resourceTypes/txt (this is what currently displays on the View Work page)
term: **Text** (this is what we want to display on the View Work page)

**Comment by alexBLR** [comment]
<img width="1036" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkxZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7045a4ea7c64f299feaa116294f6b290ed7aaa28/Screen%20Shot%202024-07-12%20at%202.19.31%20PM.png" alt="Screen Shot 2024-07-12 at 2.19.31 PM.png" />
<img width="1092" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlhZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--723a633a9bd0509bbdab3726a1bbb4dcbf3c50e3/Screen%20Shot%202024-07-12%20at%201.26.49%20PM.png" alt="Screen Shot 2024-07-12 at 1.26.49 PM.png" />

**Comment by eporter23** [comment]
Looks great @alexBLR !
