### ISSUE TITLE
KeyError in Hyrax::Publications#show when viewing a Bulkrax-imported work

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#377]
During the recorded demo today, I ran a Bulkrax import which appeared to have completed successfully. When navigating back to the imported work, I get the following error:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUtmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e65a6e0dc533b7d1e17c16a3be26f5638a770ba/Screenshot%202024-06-28%20at%2012.25.23%E2%80%AFPM.png" alt="Screenshot 2024-06-28 at 12.25.23 PM.png" />

**Comment by abelemlih** [comment]
PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/379

**Comment by eporter23** [comment]
I ran a new Bulkrax import today and this error did not occur. Thanks!
