### ISSUE TITLE
Non admin deposits no longer go into review workflow by default

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#378]
**Describe the bug**
This behavior has shown up as of 6/28/24 after work done in #295 was tested and accepted. If a non-Admin user deposits a work, while the Relationships tab is not shown, their deposits do not go into any Admin Set nor do they get assigned to In Review status. I tested this in arch twice today but will also check to see if the behavior occurs in test.

**To Reproduce**
1. Login as Basic User in the arch environment
2. Deposit a new work, add all required metadata, and add a Primary Content file
3. Click the assent to deposit agreement and save the work
4. View the work and note that it does not go into Review and Approve, and the Relations section of the View Work page is blank

These 2 works created today in arch as basic_user show the same behavior:

https://oe24-arch.libraries.emory.edu/concern/publications/450412f3-fcfb-40dc-9a3c-4a64b4808a85?locale=en
https://oe24-arch.libraries.emory.edu/concern/publications/be3ad596-4398-4ce1-8ab6-55b22561fff2?locale=en

Additonal example replicated in test:
https://oe24-test.libraries.emory.edu/concern/publications/530af6ae-8296-4a8f-9022-7595b864e8be?locale=en

**Expected behavior**
When a non-Admin user deposits a work, it should be assigned to the OpenEmory with Deposit Workflow Admin Set and should also be assigned to the OpenEmory collection.
A work should always be assigned to an Admin Set.

**Screenshots**
In the below image, you can see that basic_user has just deposited a work and it is not assigned to workflow.

<img width="1887" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVNmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4e7e2e3e03ef9820176c29aecff55759422e9b9/Screenshot%202024-06-28%20at%201.05.19%E2%80%AFPM.png" alt="Screenshot 2024-06-28 at 1.05.19 PM.png" />

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome

**Comment by bwatson78** [comment]
This is because the default admin set and collection will need to be set as Rails ENVs after they have been created and I forget to advise you of how this will work exactly.

**Comment by eporter23** [comment]
Thanks @bwatson78 - working as expected in test now. I'm moving this into Accept before closing it, in case we want to document any steps that we need to remember when we wipe out environments.
