### ISSUE TITLE
Submit ServiceNow Ticket for Security Review

### ISSUE THREAD

**Issue by tmill29** [emory-libraries/dlp-selfdeposit#38]
- [x] Beth will schedule a working session with Collin Brittle and Emily 

- [x] Submit servicenow ticket

[Link to servicenow ticket 
](https://emory.service-now.com/sp?id=sc_cat_item&sys_id=13b886852b70f100427d2ca119da1536&sysparm_category=4e5351bf985fc940593bf372f0e9a923)

Prior Samvera/Hyrax security forms
[Curate](https://emory.sharepoint.com/:w:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/02%20Project%20Archive/DLP_%20Curation%20and%20Discovery/Scrum%20Team/LITS%20Review%20Processes/Security%20Review/Curate-Security%20Review%20Intake%20Answers.docx?d=w66ceaf98c34c441f9c61a06a4e6a5e41&csf=1&web=1&e=hgrl58)
[ETDs ](https://emory.sharepoint.com/:b:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/02%20Project%20Archive/ETD%20Rewrite/Project%20Management/ART_Security%20Review%20Docs/FW_%20SUBMITTED_%20Request%20REQ50313%20%20has%20been%20submitted.pdf?csf=1&web=1&e=rXiVWa)

**Comment by eporter23** [comment]
[ServiceNow Request submitted](https://emory.service-now.com/sp?id=ticket&table=sc_req_item&sys_id=7b532c1f1b9c4a9462e42fc42a4bcbea&view=sp) on 2/16/24. A PDF copy of our entries will also be added to the project folder.
