### ISSUE TITLE
Preliminary Facets (Hyrax Sidebar in Search Results)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#383]
To discuss: do facet headings need to be exactly the same as the field display labels? These are still in review in some cases.

For our preliminary facets, we have identified the following as desired facets. 
Please generate the following facets, in this order:

- [x] **Author** (listed as lastname, firstname) - see related work in #369
- [x] **Date** (4 digit year only) - see related work in #369
- [x] **Journal or Parent Publication Title**  (`parent_title`)
- [x] **Type** (`content_genres`)
- [x] **Publication Version**  (`publisher_version`)
- [x] **Keyword** (keep existing Hyrax facet as is)

Additionally, we want to suppress or remove the following default Hyrax facets:

- [x] Subject (because we won't have much data to populate it)
- [x] Collections (because for launch, we will only have one Collection)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/404

**Comment by eporter23** [comment]
Looks good! I'm seeing something in 2 of the facets where a blank entry is showing results (I've also noticed in SOLR that we have a lot of fields which are blank if not explicitly populated). Is this something we can resolve through this ticket or is a new one needed? See the Journal or Parent Publication Title and Publisher Version facets: 

<img width="462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWpxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74d93d34612f6f5e7579f69f46da7666d6ad67bb/Screenshot%202024-07-17%20at%201.30.32%E2%80%AFPM.png" alt="Screenshot 2024-07-17 at 1.30.32 PM.png" />

**Comment by eporter23** [comment]
Specific to the Publisher Version facet, the heading label should be "Publication Version". We have this change in place on the Work form already and I have also added it to the pt.2 ticket for metadata display labels for the View Work page.

**Comment by bwatson78** [comment]
Since this would involve overriding the partial that delivers the facets, can you create a new ticket for this issue? For the label change, I'll add it to the other ticket I have to adjust.

**Comment by eporter23** [comment]
Looks great @bwatson78 - I also see that you resolved the issue with the blank entries showing up, so feel free to increase the estimate on this one if needed.
