### ISSUE TITLE
Generate a report of withdrawn records' review notes

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#384]
As part of our migration work, we do not want to migrate/reingest works that exist in Fedora 3 which have been withdrawn, which can occur for a variety of reasons. The SCO team has requested that we generate report of these records so we can avoid accidentally re-ingesting these in the future.

The SOLR index for legacy OpenEmory data contains a flag to indicate if a work has been withdrawn but does not contain the circumstances of why a given record may have been withdrawn. While I have been able to [export a CSV file from SOLR](https://emory.sharepoint.com/:x:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/01%20Active%20Project/OpenEmory%20Phase%202/02%20Planning%20and%20Execution/02%20Technical%20Documentation,%20Drawings%20%26%20Diagrams/Migration%20Planning/withdrawnrecords-extra-dataSOLR.csv?d=wa3d04127b22d497eadd43334d9663e04&csf=1&web=1&e=Ee12bh) to identify which records have "withdrawn" status, the details of why a record was withdrawn seem to be stored in the provenanceMetadata XML files only (see example below).

For this ticket, we should identify and implement an option to generate a report (CSV etc.) that provides the following, in order to supplement the report already generated from SOLR:
- [x] PID for the work
- [x] Preservation event data that documents the circumstances for why a record was withdrawn

Example from provenanceMetadata: 

> <p:event>
> <p:eventIdentifier>
> <p:eventIdentifierType>local</p:eventIdentifierType>
> <p:eventIdentifierValue>emory:pmrpz.ev007</p:eventIdentifierValue>
> </p:eventIdentifier>
> <p:eventType>withdraw</p:eventType>
> <p:eventDateTime>2015-09-10T11:03:03.855107</p:eventDateTime>
> <p:eventDetail>Withdrawn by abyoung: Author request 2015/09/10</p:eventDetail>

**Comment by alexBLR** [comment]
@eporter23 Here is the updated spreadsheet: https://emory-my.sharepoint.com/:x:/g/personal/azotov_emory_edu/EbOkkWhQpb5OgLy4PctxX5UB5abwS9ridL93G4QWQGutpQ?e=mS1t0W

**Comment by eporter23** [comment]
I checked a couple of the PIDs that didn't have any withdraw reason entries and they all came back with "no path in db registry" in Fedora 3 prod. I'm guessing with that message, it means the objects aren't there anymore!

**Comment by alexBLR** [comment]
Yes, you are correct. @eporter23
