### ISSUE TITLE
Metadata transforms, pt 3

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#386]
The following fields also need to be extracted from descMetadata. See notes in the [Metadata Implementation worksheet](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit?gid=714216589#gid=714216589&fvid=1424344959) for xpath and other notes.

- [x] grant_information 
- [x] internal_rights_note 

Fields to skip and manually correct:
- sponsor - this seems to be mixed in with Publisher, so we need to figure out what legacy OE does to separate them in display. Sponsor as its own field only seems to be provided in the deposit form for Reports.

The remaining 2 fields have been moved to a separate ticket #398.

**Comment by eporter23** [comment]
For the sponsor field, I confirmed that this is only present for Reports. When populated and stored in MODS, this is stored in mods:publisher which also can result in there being 2 mods:publisher entries.

**Comment by eporter23** [comment]
To do: determine best option to extract and identify PubMed IDs.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/406

**Comment by eporter23** [comment]
Moving this into test, I will provide a few more IDs to work from.

**Comment by eporter23** [comment]
Looks great!
