### ISSUE TITLE
Bulkrax batching process

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#394]
In team discussions on 7/3, the following needs to be fleshed out related to how we will generate batches of exports to transform for ingest via Bulkrax. To be determined: whether or not we should run the export and CSV generation at the same time, or if these should be run independently.

We anticipate needing to ingest ~32,000 works and ~300,000 files for OpenEmory.

As high level requirements:

- [ ] For Bulkrax, we may want to constrain importers to 200 objects at a time for performance reasons
- [ ] We need to be able to export batches based on a set of specific Fedora 3 ids
In some cases, we will also need to manually remediate known issues with certain types of records whose MODS files do not follow expected patterns, embargoed records, etc. We also do not want to process certain IDs which are withdrawn or do not contain content files.
- [ ] We need a solution that will not only generate the CSV file, but also structure individual objects and their files into a package usable by Bulkrax
- [ ] We need a process to copy the exported files/packages to the Self Deposit Hyrax server so that they are accessible to Bulkrax

As a starting point, we could investigate a subset of the[ Sample Objects for Migration IDs](https://docs.google.com/spreadsheets/d/1qLzdhhOIXj9ebPAS58qWpWLUD8SMXGeIjR9re0qTfMQ/edit?gid=0#gid=0) (but omitting Reports, Embargoes, and Withdrawn records).

**Comment by eporter23** [comment]
On 7/11, we discussed feasibility of whether or not we can streamline the step of the file copy process with EFS.

**Comment by bwatson78** [comment]
Proposed Workflow:

1. We create a folder inside of `/mnt/efs` called `current_batch` that would be the location that we run the import script.
2. We run the script here using either a string of PIDs joined together by commas (fine for smaller batches) or the location of a CVS that contains a list of IDs (**revision necessary**; this would be the preferable way to process larger batches).
3. The script would still build the folder structure using the PIDs for folder names, but would not do so if any record lacks a binary file (**revision necessary**).
4. If the PID lacks binary files, the script retains the PID number in a separate variable, which would then be used to create a report that would save to the same folder at the end of the processing (**revision necessary**; The report could be in either CSV or text--dealer's choice.)
5. If the PID exhibits binaries, the script retains the PID number along with its associated filenames in another variable, that is then used to build a separate report CSV file that is also saved to the same folder at the end of processing (**revision necessary**).

**End Result Of Import Script**: Folders for PIDs that contain binaries, XMLs (one per PID) used by the script to extract the files, one report document that details the PIDs without binaries, and a CSV report that contains the filenames related to the PIDs.

MODS Extraction Script Workflow:

1. The script would be processed anywhere with access to the EFS mount.
2. It would take in one require variable: the full path to the CSV report that contains the PIDs related to their filenames (**revision necessary**).
3. It would also accept an optional variable called `local` that would switch the processing away from the hard coded EFS location to the specified local path of a folder containing the PID files (done for local testing only; **revision necessary**).
3. The script would locate the `descMetadata.xml` files utilizing the PID info in the report and the hard-coded location of the mount for the EFS folder (**revision necessary**).
4. The script would then process the XML for the necessary metadata and use the CSV report to attach each PID's file list to the return CSV related line (**revision necessary**).
5. The script would then return a CSV file (named using the current date and time) to the same folder the script was ran from (**revision necessary**).
6. The only necessary human intervention (at this moment) would involve the creation of the file labels to be passed to the Bulkrax Importer.

**Comment by bwatson78** [comment]
Note: The current estimate covers the revisions listed above. That means I would re-estimate if the proposed workflow is altered.

**Comment by bwatson78** [comment]
Labels: I know that you de-scoped the labels portion of Bulkrax pt 3 because we needed to revise the logic.
`...any more automation`: I think that should be a Zoom/huddle meeting to drill down on what you're asking there.
`...omitting PIDs that have no content datastream`: This is more of me coding a built-in rescue so that the script doesn't stop dead in its tracks if it encounters such a record.
`I'm assuming I would generate a CSV of PIDs`: That's right.

**Comment by eporter23** [comment]
Discussed the above with @bwatson78 and we want to add the file labels and file names conventions to this ticket. As an example of a reference object, please see this [manually created worksheet for a recent Bulkrax import.](https://docs.google.com/spreadsheets/d/1sdPKWm4dmW-Dr1HeJdnr9gzc6Qz-QTj0MGHl3lPCqFs/edit?gid=1846950359#gid=1846950359) This CSV template does not reflect all recent changes, but please note the file and file_labels columns.

When we encounter binary datastreams' files that include spaces or overly long filenames, we should adjust them by adding underscores in the filenames. If we run into character limits on the original filenames, we should truncate them to the limit that is required by Bulkrax/Hyrax/etc.

**Comment by bwatson78** [comment]
PR made (covers the import script): https://github.com/emory-libraries/dlp-selfdeposit/pull/445

**Comment by bwatson78** [comment]
Another PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/453

**Comment by bwatson78** [comment]
Those PRs are merged.

**Comment by eporter23** [comment]
Additional tickets - create a readme file, testing at larger scale on a larger set of PIDs
