### ISSUE TITLE
Shibboleth pre-work

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#40]
As pre-work to getting our Shibboleth authentication in place, the following tasks were identified on 2/15/24:

- [x] Pull down data to review attributes in advance if we are able to

**Comment by eporter23** [comment]
As pre-work to getting our Shibboleth authentication in place, the following tasks were identified on 2/15/24:

- [ ] Pull down data to review attributes in advance if we are able to 
- [ ] Identify attributes that are needed for OpenEmory, based on what attributes we have access to 
- [ ] Review Shibboleth integration options for Hyrax

**Comment by tmill29** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DLP-Self-Deposit-65a7f6937b42b04b7bc5d018/issues/emory-libraries/dlp-selfdeposit/40?planning-poker) with Zenhub @kbowaterskelly @jcrompton42

**Comment by kbowaterskelly** [comment]
<afp:PermitValueRule id="eduPersonAffiliationValues" xsi:type="OR">
        <Rule xsi:type="AttributeValueString" value="faculty"/>
        <Rule xsi:type="AttributeValueString" value="student"/>
        <Rule xsi:type="AttributeValueString" value="staff"/>
        <Rule xsi:type="AttributeValueString" value="alum"/>
        <Rule xsi:type="AttributeValueString" value="member"/>
        <Rule xsi:type="AttributeValueString" value="affiliate"/>
        <Rule xsi:type="AttributeValueString" value="employee"/>
        <Rule xsi:type="AttributeValueString" value="library-walk-in"/>
    </afp:PermitValueRule>

https://login.emory.edu/client-config/attribute-map.xml



<Attribute id="companyAccount" name="urn:mace:dir:attribute-def:companyAccount"/>
<Attribute id="companyAccount" name="urn:oid:1.3.6.1.4.1.5524.1.38"/>
<Attribute aliases="USERNAME" id="remoteuser" name="urn:mace:dir:attribute-def:REMOTE_USER"/>
<Attribute aliases="USERNAME" id="remoteuser" name="urn:x-emory:remote_user"/>

<Attribute aliases="AUTHENTICATE_UID" id="uid" name="urn:mace:dir:attribute-def:uid"/>
<Attribute aliases="AUTHENTICATE_UID" id="uid" name="urn:oid:0.9.2342.19200300.100.1.1"/>
<Attribute aliases="AUTHENTICATE_MAIL" id="mail" name="urn:mace:dir:attribute-def:mail"/>
<Attribute aliases="AUTHENTICATE_MAIL" id="mail" name="urn:oid:0.9.2342.19200300.100.1.3"/>
<Attribute aliases="AUTHENTICATE_ORGANIZATIONALSTATUS" id="organizationalStatus" name="urn:mace:dir:attribute-def:organizationalStatus"/>
<Attribute aliases="AUTHENTICATE_ORGANIZATIONALSTATUS" id="organizationalStatus" name="urn:oid:0.9.2342.19200300.100.1.45"/>

<Attribute id="uidNumber" name="urn:mace:dir:attribute-def:uidNumber"/>
<Attribute id="uidNumber" name="urn:oid:1.3.6.1.1.1.1.0"/>
<Attribute id="gidNumber" name="urn:mace:dir:attribute-def:gidNumber"/>
<Attribute id="gidNumber" name="urn:oid:1.3.6.1.1.1.1.1"/>
<Attribute id="homeDirectory" name="urn:mace:dir:attribute-def:homeDirectory"/>
<Attribute id="homeDirectory" name="urn:oid:1.3.6.1.1.1.1.3"/>
<Attribute id="loginShell" name="urn:mace:dir:attribute-def:loginShell"/>
<Attribute id="loginShell" name="urn:oid:1.3.6.1.1.1.1.4"/>

<Attribute id="suppressinfo" name="urn:mace:dir:attribute-def:suppressinfo"/>
<Attribute id="suppressinfo" name="urn:oid:1.3.6.1.4.1.5524.1.4"/>
<Attribute id="saemplid" name="urn:mace:dir:attribute-def:saemplid"/>
<Attribute id="saemplid" name="urn:oid:1.3.6.1.4.1.5524.1.8"/>
<Attribute id="hremplid" name="urn:mace:dir:attribute-def:hremplid"/>
<Attribute id="hremplid" name="urn:oid:1.3.6.1.4.1.5524.1.9"/>
<Attribute id="fullName" name="urn:mace:dir:attribute-def:fullName"/>
<Attribute id="fullName" name="urn:oid:1.3.6.1.4.1.5524.1.30"/>

<Attribute id="eduPersonAffiliation" name="urn:mace:dir:attribute-def:eduPersonAffiliation"/>
<Attribute id="eduPersonAffiliation" name="urn:oid:1.3.6.1.4.1.5923.1.1.1.1"/>
<Attribute id="eduPersonNickname" name="urn:mace:dir:attribute-def:eduPersonNickname"/>
<Attribute id="eduPersonNickname" name="urn:oid:1.3.6.1.4.1.5923.1.1.1.2"/>
<Attribute id="eduPersonOrgDN" name="urn:mace:dir:attribute-def:eduPersonOrgDN"/>
<Attribute id="eduPersonOrgDN" name="urn:oid:1.3.6.1.4.1.5923.1.1.1.3"/>
<Attribute id="eduPersonOrgUnitDN" name="urn:mace:dir:attribute-def:eduPersonOrgUnitDN"/>
<Attribute id="eduPersonOrgUnitDN" name="urn:oid:1.3.6.1.4.1.5923.1.1.1.4"/>
<Attribute id="eduPersonPrimaryAffiliation" name="urn:mace:dir:attribute-def:eduPersonPrimaryAffiliation"/>
<Attribute id="eduPersonPrimaryAffiliation" name="urn:oid:1.3.6.1.4.1.5923.1.1.1.5"/>
<Attribute id="eduPersonPrincipalName" name="urn:mace:dir:attribute-def:eduPersonPrincipalName"/>
<Attribute id="eduPersonPrincipalName" name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6"/>
<Attribute id="eppn" name="urn:mace:dir:attribute-def:eduPersonPrincipalName"/>
<Attribute id="eppn" name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6"/>
<Attribute id="eduPersonEntitlement" name="urn:mace:dir:attribute-def:eduPersonEntitlement"/>
<Attribute id="eduPersonEntitlement" name="urn:oid:1.3.6.1.4.1.5923.1.1.1.7"/>
<Attribute id="eduPersonPrimaryOrgUnitDN" name="urn:mace:dir:attribute-def:eduPersonPrimaryOrgUnitDN"/>
<Attribute id="eduPersonPrimaryOrgUnitDN" name="urn:oid:1.3.6.1.4.1.5923.1.1.1.8"/>
<Attribute id="eduPersonScopedAffiliation" name="urn:mace:dir:attribute-def:eduPersonScopedAffiliation"/>
<Attribute id="eduPersonScopedAffiliation" name="urn:oid:1.3.6.1.4.1.5923.1.1.1.9"/>

<Attribute id="academiccareer" name="urn:oid:1.3.6.1.4.1.5524.1.13"/>

<Attribute id="eduPersonTargetedID" name="urn:mace:dir:attribute-def:eduPersonTargetedID">
<AttributeDecoder defaultQualifiers="true" formatter="$NameQualifier!$SPNameQualifier!$Name" xsi:type="NameIDAttributeDecoder"/>
</Attribute>
<Attribute id="eduPersonTargetedID" name="urn:oid:1.3.6.1.4.1.5923.1.1.1.10">
<AttributeDecoder defaultQualifiers="true" formatter="$NameQualifier!$SPNameQualifier!$Name" xsi:type="NameIDAttributeDecoder"/>
</Attribute>


<Attribute id="departmentNumber" name="urn:mace:dir:attribute-def:departmentNumber" uid="AUTHENTICATE_DEPARTMENTNUMBER"/>
<Attribute id="departmentNumber" name="urn:oid:2.16.840.1.113730.3.1.2" uid="AUTHENTICATE_DEPARTMENTNUMBER"/>
<Attribute id="employeeNumber" name="urn:mace:dir:attribute-def:employeeNumber"/>
<Attribute id="employeeNumber" name="urn:oid:2.16.840.1.113730.3.1.3"/>
<Attribute id="employeeType" name="urn:mace:dir:attribute-def:employeeType"/>
<Attribute id="employeeType" name="urn:oid:2.16.840.1.113730.3.1.4"/>
<Attribute id="mailForwardingAddress" name="urn:mace:dir:attribute-def:mailForwardingAddress"/>
<Attribute id="mailForwardingAddress" name="urn:oid:2.16.840.1.113730.3.1.17"/>
<Attribute id="displayName" name="urn:mace:dir:attribute-def:displayName"/>
<Attribute id="displayName" name="urn:oid:2.16.840.1.113730.3.1.241"/>

<Attribute aliases="AUTHENTICATE_CN" id="cn" name="urn:mace:dir:attribute-def:cn"/>
<Attribute aliases="AUTHENTICATE_CN" id="cn" name="urn:oid:2.5.4.3"/>
<Attribute aliases="AUTHENTICATE_SN" id="sn" name="urn:mace:dir:attribute-def:sn"/>
<Attribute aliases="AUTHENTICATE_SN" id="sn" name="urn:oid:2.5.4.4"/>
<Attribute aliases="AUTHENTICATE_SERIALNUMBER" id="serialNumber" name="urn:mace:dir:attribute-def:serialNumber"/>
<Attribute aliases="AUTHENTICATE_SERIALNUMBER" id="serialNumber" name="urn:oid:2.5.4.5"/>
<Attribute id="ppid" name="urn:mace:dir:attribute-def:serialNumber"/>
<Attribute id="ppid" name="urn:oid:2.5.4.5"/>
<Attribute id="o" name="urn:mace:dir:attribute-def:o"/>
<Attribute id="o" name="urn:oid:2.5.4.10"/>
<Attribute id="ou" name="urn:mace:dir:attribute-def:ou"/>
<Attribute id="ou" name="urn:oid:2.5.4.11"/>
<Attribute id="title" name="urn:mace:dir:attribute-def:title"/>
<Attribute id="title" name="urn:oid:2.5.4.12"/>
<Attribute id="description" name="urn:mace:dir:attribute-def:description"/>
<Attribute id="description" name="urn:oid:2.5.4.13"/>
<Attribute id="businessCategory" name="urn:mace:dir:attribute-def:businessCategory"/>
<Attribute id="businessCategory" name="urn:oid:2.5.4.15"/>
<Attribute id="postalAddress" name="urn:mace:dir:attribute-def:postalAddress"/>
<Attribute id="postalAddress" name="urn:oid:2.5.4.16"/>
<Attribute aliases="AUTHENTICATE_TELEPHONENUMBER" id="telephoneNumber" name="urn:mace:dir:attribute-def:telephoneNumber"/>
<Attribute aliases="AUTHENTICATE_TELEPHONENUMBER" id="telephoneNumber" name="urn:oid:2.5.4.20"/>
<Attribute aliases="AUTHENTICATE_GIVENNAME" id="givenName" name="urn:mace:dir:attribute-def:givenName"/>
<Attribute aliases="AUTHENTICATE_GIVENNAME" id="givenName" name="urn:oid:2.5.4.42"/>
<Attribute id="initials" name="urn:mace:dir:attribute-def:initials"/>
<Attribute id="initials" name="urn:oid:2.5.4.43"/>
<Attribute id="isMemberOf" name="urn:mace:dir:attribute-def:isMemberOf"/>
<Attribute id="isMemberOf" name="urn:oid:1.3.6.1.4.1.5923.1.5.1.1"/>
</Attributes>

**Comment by eporter23** [comment]
Thanks for these files @kbowaterskelly - do you happen to know what the comments in the attributes file for Netscape, X500, NIS, Emory mean?

**Comment by eporter23** [comment]
We split this ticket out further because different teams need to weigh in on it.
