### ISSUE TITLE
Configure metadata for OpenEmory work type

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#41]
As we set up the OpenEmory work type, we need to configure the metadata fields for this type.

Our goals are to 

- [x] reuse existing Hyrax fields whenever possible
- [x] align to Curate's metadata as closely as we can, for greater interoperability in the future
- [x] ensure that these fields can be stored in SOLR through Valkyrie

[This filtered view](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589&fvid=1424344959) shows a subset of Hyrax and Curate fields that are immediately applicable to OpenEmory content, and whether they are custom fields or Hyrax fields (noted in the Implemented - Model column).
Fields that are marked as TBD will be addressed in separate tickets.

**Comment by bwatson78** [comment]
These fields have been moved to `Publication`. This work has been deployed to Arch and can be tested.

**Comment by eporter23** [comment]
Looks great @bwatson78 - I did a first pass to check to see if the fields were present in the form (haven't yet tested populating and saving them). I did notice Library/holding_repository doesn't seem to be there, but maybe it's not in place yet since there were still some TBD fields? There are also some other fields which I assume are from Hyrax that we don't need, but we can handle those in future tickets.

**Comment by bwatson78** [comment]
@eporter23 I mapped the label of `holding_repository` to Library, like it is in Curate. If that's not Kosher, let me know.

**Comment by eporter23** [comment]
For testing the Publication work type, we currently have 2 sets of fields in place: https://github.com/emory-libraries/dlp-selfdeposit/blob/main/config/metadata/emory_basic_metadata.yaml and https://github.com/emory-libraries/dlp-selfdeposit/blob/main/config/metadata/publication_metadata.yaml.

**Comment by eporter23** [comment]
@bwatson78 I went through the fields again and noticed that System of Record ID isn't there. Can we add that one also? I realize it had a TBD note for the MODS mapping, but we do want that as a field and in the form.

**Comment by bwatson78** [comment]
Working on that now.

**Comment by bwatson78** [comment]
`system_of_record_ID` PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/100

**Comment by eporter23** [comment]
Looks great, thanks!
