### ISSUE TITLE
Metadata fields' display labels pt.2

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#410]
This ticket follows work started in #197.

The following fields should have their display labels adjusted on the Work form and the View Work page:

`creator` **Authors**
`date_issued ` **Date**
`page_range_start ` **Start Page**
`page_range_end ` **End Page**
`place_of_production ` **Place of Publication or Presentation**
`publisher_version` **Publication Version**
`sponsor ` **Sponsor**
`grant_agencies ` **Grant/Funding Agency**
`grant_information ` **Grant/Funding Information**
`related_datasets ` **Supplemental Material (URL)**

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/420

**Comment by eporter23** [comment]
Thanks @bwatson78 !
