### ISSUE TITLE
Suppress sponsor field from Work form

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#411]
For this ticket, we want to ensure that the sponsor field exists for migration and display purposes, but will not be shown to depositors or Admins when using the Work form to create or edit.

Since sponsor may overlap with funder, and we can only find a handful of legacy records that have this populated, we want to minimize confusion and data entry for depositors. 

- [x] Retain the configured field in the model
- [x] Retain the field in the View Work display if populated
- [x] Remove the field from the Create/Edit work form

**Comment by maxdmayhew** [comment]
be sure to check removing from rspec

**Comment by eporter23** [comment]
Thanks @alexBLR looks good!
