### ISSUE TITLE
Update display labels in form validation models to match form input labels

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#419]
As we have made updates to the display labels on the form entries, we also need to make sure the modal windows that display during validation errors are showing the updated labels.

See #410 and #197 for recent metadata label changes.

**Comment by CB987** [comment]
6/6 modal validation messages updated.
<img width="994" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0lQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b656c5520a5d27d4c7344a9ed2c0c414213c9743/Screenshot%202024-07-25%20at%205.50.15%E2%80%AFPM.png" alt="Screenshot 2024-07-25 at 5.50.15 PM.png" />
<img width="980" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2NQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fda23deee11751d9ed44a262df44a3dcf6bd2bee/Screenshot%202024-07-25%20at%205.53.29%E2%80%AFPM.png" alt="Screenshot 2024-07-25 at 5.53.29 PM.png" />

**Comment by eporter23** [comment]
Looks good, thanks!
