### ISSUE TITLE
Implement PDF viewer for the View Work page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#421]
This ticket follows work done in #400 to assess feasibility of incorporating a PDF viewer into the Hyrax UI.

For this ticket, we want to implement findings noted and prototyped in #400.

Additional requirements:

- If a PDF fileset is set as the representative media for the work, this should load the PDF viewer instead
- If a non-PDF fileset is set as the representative media for the work, the existing application behaviors should apply (either rendering a thumbnail only, or an audio or video media player element).
- Ideally, we want to streamline this with our migration process so that we don't have to manually set the representative media for each work migrated.

**Comment by abelemlih** [comment]
In Progress. Draft PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/423

**Comment by abelemlih** [comment]
Ready for testing on Arch

**Comment by eporter23** [comment]
Thanks @abelemlih !
