### ISSUE TITLE
Bulkrax, pt.3

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#422]
For this ticket, we want to continue refinements to the CSV parsing related to required fields and FileSets.
If any of the requirements below are better suited for or are impacting our XML extraction process, please note that as part of this ticket so it can be flagged for additional work. 

**Metadata**
- [x] Resolve any ongoing issues with `content_genre` vs. `content_genres` usage related to our MODS extraction process and what the Bulkrax importer expects. The MODS extractor currently outputs `content_genres`.

Assign default values for the following fields which are always required in the new application, but were not required in the legacy system:

- [x] `publisher` : add default value of "Emory University Libraries" if no data is present. Currently if not populated, this adds `[]` to the record which triggers a KeyError when trying to view the record.
- [x] `data_classifications` : add default value of "Public" if no data is present

Adjust strings to URIs

-  [x] Convert "Text" or "text" values to the URI value used in Self Deposit's QA local vocabulary: http://id.loc.gov/vocabulary/resourceTypes/txt

**FileSets**

Assign `file_use` to FileSets using this pattern:

- [x] `content*` (Primary Content aka "Content" datastream) files should be "Primary Content"
- [x] All other FileSets should be "Supplemental Preservation"

Assign `visibility` to FileSets using this pattern:

- [x] `content*` (Primary Content aka "Content" datastream) files should be Public
- [x] All other FileSets should be Private 

**Working Mockup:**
Imported work (with FileSet visibility manually assigned after ingest): https://oe24-test.libraries.emory.edu/concern/publications/1ea97d6b-d730-4093-a109-2348c75b7bb7?locale=en
Importer: https://oe24-test.libraries.emory.edu/importers/8?locale=en
[CSV template showing file conventions](https://docs.google.com/spreadsheets/d/1sdPKWm4dmW-Dr1HeJdnr9gzc6Qz-QTj0MGHl3lPCqFs/edit?gid=1846950359#gid=1846950359)

**Comment by eporter23** [comment]
I descoped part of this ticket after we ran into some issues with exported filenames, so I will create a new ticket related to that and file_label conventions to automate for Bulkrax.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/431

**Comment by eporter23** [comment]
To test this version, remove the file_uses column. Visibility will be assigned without needing an extra column. Note: we will be making some revisions around file label conventions and filenames as part of the batching work.
