### ISSUE TITLE
Date Uploaded/Date Added missing from various application views

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#433]
When navigating the application, there are multiple instances of the Date Uploaded field in the Hyrax display which are not populated. These are the ones I have identified so far:

View Work Page - Items list
View FileSet Page - metadata display
View Collection Page - metadata display

This also appears to be impacting the ability to sort search results by Date Uploaded. To reproduce: 

- do an empty search
- Sort by Date Uploaded descending and ascending
- Note that the results' order does not change

**Comment by eporter23** [comment]
Assuming this is deployed as of 7/31, I am still not seeing Date Uploaded being populated in the UI or in SOLR (looking for date_uploaded). I am continuing to see date_created_tesim being auto-populated such as this: 
``` "date_created_tesim":["2024-07-09T13:04:45Z"],```

**Comment by bwatson78** [comment]
@eporter23 For brand new objects created after the deploy, I am seeing Date Uploaded:
<img width="1192" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmxIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a2416b860141fa4e35ee860aa8b8cff1bda857c/Screenshot_20240809_074506.png" alt="Screenshot_20240809_074506.png" />
<img width="1264" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnBIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e38b48c9c6a194842eaa4ada4cf8798895bae4a/Screenshot_20240809_074434.png" alt="Screenshot_20240809_074434.png" />
<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnRIQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76733c2dbd230f3c32e36f8a4b6ceb693c25f525/Screenshot_20240809_074340.png" alt="Screenshot_20240809_074340.png" />

If you are referring to previous objects created not displaying Date Uploaded, that would require a remediation task that would scan all objects and assign the oldest date value found in Fedora's dc:created field (via Fedora API--only place it's available) to the date_uploaded field using Valkyrie. If that's what you're looking for--I can do that. That's basically what Rob Kaufman is requesting for the Hyrax bug fix ticket, so I could create it for both applications.

**Comment by eporter23** [comment]
@bwatson78 for the above screenshots, was this in your local environment? I'm not able to upload filesets in test or arch, so I can't replicate what you are seeing.

**Comment by eporter23** [comment]
We need to pull in the commit locally that fixed this for Hyrax.
