### ISSUE TITLE
Ensure Bulkrax imports receive all work-level preservation events at ingest

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#440]
In recent testing, 2 works created by Bulkrax do not show all the expected Preservation Events related to the ingest process. 

Bulkrax-created works are not showing 2 events that should occur at the time of ingest, while manually created works are: 

- Policy Assignment
- Validation

**Comment by eporter23** [comment]
Need to investigate Bulkrax's work creation process.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/559

**Comment by eporter23** [comment]
Looks good after the latest large ingest, thanks!
