### ISSUE TITLE
Wipe and restore ARCH to test new rake task

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#441]
This ticket follows work to create a rake task that can restore key assets identified in ticket #392.

Prior to this work, please ensure that oe24-test has the latest code deployed.

Suggested tasks as previously used in #368:

- [x] Wipe Fedora
- [x] Wipe SOLR
- [x] Wipe S3
- [x] Wipe database
- [ ] Deploy and run rake task

**Comment by eporter23** [comment]
@jcrompton42 I think this was completed but can you update this ticket to confirm?

**Comment by eporter23** [comment]
Yes, the base users are restarted on arch. But, I mainly wanted to check if we can close this out, because I think the wipe and restore work was done a few weeks back.

**Comment by jcrompton42** [comment]
It was so I think we can close it.
