### ISSUE TITLE
PDF viewer on test vs. arch

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#444]
The same PDF file was deposited in both test and arch, but it only renders in arch:

https://oe24-test.libraries.emory.edu/concern/publications/f44bc4a6-c048-4294-97fa-232c191b26b2?locale=en
In the above example, the representative media option in the Work form does not show any available options for the FileSet that is attached.
This example in Test does show representative media assigned to a PDF file, but also does not load the file within the PDF viewer:
https://oe24-test.libraries.emory.edu/concern/publications/3509fc77-9f04-44bb-a4fd-11ae6b8e4c3f?locale=en

https://oe24-arch.libraries.emory.edu/concern/publications/6ace6b51-d758-4ada-a94d-e3a1f1359e72?locale=en
In the arch example, it has the PDF viewer loaded and also shows the representative media options for the single FileSet that is attached.

**Comment by abelemlih** [comment]
@eporter23 pdf viewer rendering issues have now been resolved. This ticket is ready for testing.

**Comment by eporter23** [comment]
@abelemlih I'm now wondering if this may be a browser-specific issue. I can now load the PDFs in both arch and test now using Chrome and Firefox, but Safari 17.3 is not loading them. In Safari, the viewer element loads, but no PDF is displayed. Let me know if I should write up a separate bug ticket about this.

**Comment by eporter23** [comment]
Oddly enough the instance on Lafayette does seem to be working in safari? https://ldr.lafayette.edu/concern/publications/9019s417m

**Comment by abelemlih** [comment]
@eporter23 they use version 4.0.379, we use v4.4.168. I can update our application to use the latest version or any version you prefer.

**Comment by eporter23** [comment]
Closing this - I have created #447 to address fuller browser support.
