### ISSUE TITLE
Setup temporary users and roles for early development

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#45]
While we work on integrating Emory Shibboleth authentication, we want to allow project team users to access the deployed application. These initial temporary accounts can be deleted and recreated later once we have Shibboleth in place.

For this ticket, we want to:

- [x] Ensure basic dbauth is working
- [x] Allow project team members to sign up and register for an account

See also related ticket #54 for assigning temporary user accounts to the Admin group. Given that we don't have those in place yet, I removed that work from this ticket.

**Comment by rotated8** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DLP-Self-Deposit-65a7f6937b42b04b7bc5d018/issues/emory-libraries/dlp-selfdeposit/45?planning-poker) with Zenhub @alexBLR

**Comment by alexBLR** [comment]
I tested the basic db auth.
Basic signup works.

**Comment by eporter23** [comment]
This seems to be working, I was able to create an account using my Emory email address. It initially threw an error, which may be related to arch still needing some dependencies, but otherwise seems fine.
