### ISSUE TITLE
Hyrax::VisibilityMap error when creating new works in UI

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#450]
**Describe the bug**
When creating new works or trying to edit an existing work as of 7/30/24, the process of saving after attaching a FileSet returns a VisibilityMap error.

**To Reproduce**
1. Login as the Admin user
2. Create a new work and fill out all required metadata
3. Go to the Files tab and upload a Primary Content File
4. Save the work
5. See error (screenshot below)
6. Go to the work and see it has been created, but no FileSets are attached. Sidekiq does not show any fileset related jobs.

**Expected behavior**
FileSets should be attached without errors

**Screenshots**

<img width="1751" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFFoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79afb15bf505ecacf06a2febe0318e25102b7b1d/Screenshot%202024-07-30%20at%204.48.31%E2%80%AFPM.png" alt="Screenshot 2024-07-30 at 4.48.31 PM.png" />

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Additional context**

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/452

**Comment by eporter23** [comment]
I think this was deployed today as of 7/31, and I am no longer seeing this error, but I will write a separate bug ticket because I am still unable to create any new FileSets (on new works or existing works). The work object shows an updated modification date, and no errors appear in sidekiq, but the filesets are not being attached.

**Comment by bwatson78** [comment]
@alexBLR I was able to see FileSets attached on my local before I merged your code for the File Uploader (#412) while I was working on this ticket. Can you check this behavior out?
