### ISSUE TITLE
Spike: enabling fulltext searching (across works) at time of ingest [placeholder]

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#458]
Having some basic full text search capabilities will be useful for self-deposit material, especially given that most of the Primary Content will be PDF.  As a time box, we will start at a 5 estimate.

We will not have separate OCR data files like we have in Curate.

To assess: is there any existing Hyrax capability to index PDFs? (there used to be, many years ago)

See also: https://github.com/samvera/hyrax/blob/59a42adfd57e8c97ceee52ae81176e5ccddcd7a6/.koppie/config/initializers/hyrax.rb#L95

**Comment by bwatson78** [comment]
Preliminary findings: Full text is extracted automatically when derivatives are created for PDFs and Office Documents.
See here: https://github.com/samvera/hyrax/blob/f77472d5fc510b656f68071a1f6a984e95d61d78/app/services/hyrax/file_set_derivatives_service.rb#L69

Continuing my search to see if they're ever used in Hyrax v5.

**Comment by bwatson78** [comment]
Example extracted text for https://oe24-test.libraries.emory.edu/concern/parent/77782c48-c061-4efd-a6df-2680e63d516e/file_sets/7c4c6359-7a6d-407b-88a9-022774dc0094:

[94-extracted_text.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3RHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0967264a57a824a050eb4237839e97aaabc959d/94-extracted_text.txt)

**Comment by bwatson78** [comment]
Hyrax v5.x and Valkyrie doesn't automatically index any field containing the FileSet's extracted text, but the FileSet itself is aware of the extracted text's content. If `fs` contains the FileSet's Valkyrie object, the text string can be accessed with `fs.extracted_text.file.read`. @eporter23 If you'd like me to start indexing the full text within the scope of this text, just let me know.

**Comment by eporter23** [comment]
@bwatson78 that is good news! I did want to ask a followup: where is the extracted text binary stored? When we were trying to diagram the Valkyrie-Fedora 6 data model, I could find FileMetadata persisted for extractedText but not the binary file itself. If we are able to index the contents of that file regardless of where it is, I am definitely interested in that, and I'm also happy to talk through whether or not we need to "preserve" that if we are able to index it.

**Comment by bwatson78** [comment]
The Extracted Text for that example above was stored at `/opt/uploads/dlp-selfdeposit/derivatives/7c/4c/63/59/-7/a6/d-/40/7b/-8/8a/9-/02/27/74/dc/00/94-extracted_text.txt` on the server.

**Comment by bwatson78** [comment]
I was able to `scp` the file to my computer.

**Comment by bwatson78** [comment]
@eporter23 Should I mirror Curate for the solr field(s)? and Should I insert the field into `All Fields`. I guess I'm asking "how far should I incorporate our Curate full-text search into SelfDeposit?"

**Comment by eporter23** [comment]
If I recall correctly, for Curate we used a SOLR field that already seemed to exist from Hyrax for full text, so I would say go with whatever seems to be Hyrax friendly? And yes, it would be great to make that searchable in the UI if that is what you mean by All Fields?

**Comment by tmill29** [comment]
Once the current import is completed @eporter23 will test.

**Comment by eporter23** [comment]
@bwatson78 - btw, do you happen to know if full text extraction is only happening on PDF files, or is it occurring for all textual files (our migrated Fedora XML files for example)?

**Comment by bwatson78** [comment]
I will push up a small PR for the label change.

As far as full text extraction is concerned, Hyrax only creates a documnet for PDFs and "Office Documents". 

```
office_mime_types: [
          'text/rtf',
          'application/msword',
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
          'application/vnd.oasis.opendocument.text',
          'application/vnd.ms-excel',
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          'application/vnd.ms-powerpoint',
          'application/vnd.openxmlformats-officedocument.presentationml.presentation'
        ],
        pdf_mime_types: ['application/pdf']
```

**Comment by eporter23** [comment]
Thanks for the label tweak @bwatson78 ! I did notice a really odd search result this morning that I'll keep an eye on to see if it occurs in other situations (which would be a separate ticket). If you do a search on "statin" and then go to page 2 and scroll down a bit, one of the results seems to show the entire full text of the article as opposed to just the first instance of a match. [Search Results on statin](https://oe24-test.libraries.emory.edu/catalog?locale=en&page=2&q=statin&search_field=all_fields)
