### ISSUE TITLE
Public search: searchable fields for Publication Works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#461]
For the public search function in the main application header, we want to make sure applicable fields can be searched.
In a separate ticket, we will look at Collection metadata to see if any adjustments need to be made.

**Fields that should be searchable:**
To discuss: In some cases, if there is a _tesi and a _ssi version - should we make both searchable?
- [x] alternate_id
- [x] content_genre
- [x] title
- [x] creator 
- [x] language
- [x] date_issued
- [x] publisher
- [x] publisher_version
- [x] parent_title
- [x] conference_name
- [x] issn
- [x] isbn
- [x] series_title
- [x] grant_agencies
- [x] grant_information
- [x] abstract
- [x] author_notes
- [x] keyword
- [x] subject
- [x] research_categories
- [x] emory_ark

**Fields that should not be searchable:**

- [ ] Any fields not noted above

**Comment by bwatson78** [comment]
@eporter23 Hyrax' out of the box `All Fields` search includes `file_format_tesim` and `all_text_timv`. As far as I can tell, most FileSet objects will have `file_format_tesim`, but `all_text_timv` doesn't show up. Do you want me to leave in both, remove them, or leave one or the other?

**Comment by eporter23** [comment]
@bwatson78 I think it's fine to leave them both in there. This also relates to a spike ticket I have related to full text search: #458 and whether or not it's "out of the box" in Hyrax anymore.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/561

**Comment by eporter23** [comment]
Tested and all is looking good.
