### ISSUE TITLE
Run the export process on a set of PIDs

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#466]
This ticket follows work in #394. We want to run the export and batching process on a larger set of pids.
The following set of 61 production PIDs contain a mix of publication types.

emory:t5nbh
emory:q4fd0
emory:rtfc8
emory:v31q2
emory:tnkj3
emory:cwkt7
emory:cwkvc
emory:tvm0d
emory:fksxq
emory:cwmr2
emory:s8jqw
emory:vgxtx
emory:vpnf0
emory:s4h1r
emory:vf508
emory:vjbj6
emory:vgwd5
emory:tgp38
emory:vjbkb
emory:vq0kn
emory:tjbdm
emory:rqd8j
emory:vq60x
emory:r9thx
emory:thgdz
emory:rw6mn
emory:vn1hb
emory:vn27b
emory:vn3gd
emory:vn28g
emory:tdmhk
emory:vdsh4
emory:rs19p
emory:vmd2m
emory:rqcsh
emory:vng45
emory:rqxmg
emory:rrwnk
emory:s6nvm
emory:vdp8v
emory:rrm3j
emory:td5xw
emory:rpff8
emory:rrkmh
emory:v2bps
emory:rhrfv
emory:rhskh
emory:s9fgp
emory:rncjd
emory:rr0z4
emory:s7k01
emory:rrtk3
emory:rp8j5
emory:rqdd3
emory:rqz72
emory:rhsbj
emory:sq5c8
emory:rjjrj
emory:vmfsm

Additional IDs for records that should/may fail, if we want to test error handling:
emory:rwwvp
emory:rhrbf

**Comment by bwatson78** [comment]
After processing the import script to bring files over to the EFS, I've sound some abnormal filenames created. I will write a bug ticket to address each issue as I find them.

**Comment by bwatson78** [comment]
For PID `rhrbf`, I cannot find a reason why that record would fail or report that it has no binaries. According to the import XML, it has two binaries that should be added to its folder (one with filename in `LABEL` and the other without, but both sporting an allowed mime type).

**Comment by eporter23** [comment]
@bwatson78 - I included emory:rhrbf in that set because it failed in our 2023 testing as well (using the Fedora 3 > 6 tools). I'll take a look at that one in more detail, too.

**Comment by bwatson78** [comment]
The vast majority of the ingest PIDs are reporting `ConnectionPool::TimeoutError - Failed to acquire a lock from Redlock due to a Redis connection timeout: Waited 5 sec, 0/5 available. If you are using Redis via `ConnectionPool` you may wish to increase the pool size.` This is pointing to our need of adjusting the pool size and timeouts for Redis, which I need to discuss with @jcrompton42 when she's available.

**Comment by jcrompton42** [comment]
I'm on it.

**Comment by jcrompton42** [comment]
I recreated the redis cluster with 3 nodes to copy our dlp redis setup. Please advise if the issue persists.

**Comment by eporter23** [comment]
Next steps on this are to wait until we have FITS running, and also preferably to have the oe24-test environment scaled up to avoid performance issues. We can manually delete the works from the prior batch in test, and then re-run the existing importer.

**Comment by bwatson78** [comment]
Changed concurrency limit to 7, and that seems to have allowed an ingest to successfully complete. @eporter23 Should we test higher numbers to find the limits?

**Comment by eporter23** [comment]
Update from 9/19 - still adjusting settings and will re-test on arch again.

**Comment by eporter23** [comment]
Main issue right now seems to involve FITS servlet. We have added some restart configs for when Tomcat is restarted. We may need to build a fileset cleanup job like we have for Curate. Best settings so far seem to be 7 or less.
