### ISSUE TITLE
Implement layout changes for the View Fileset page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#472]
This ticket follows work done in #205 to create mockups for enhancing the layout of the View FileSet page.

For this ticket, please implement the changes prototyped and discussed in the above ticket. 

As part of this work, please also make sure that the Preservation Events table is consistent between the View Work page and the View Fileset page (ensuring that the table column headings are showing the correct data values for each heading).

**Comment by CB987** [comment]
@eporter23 did you want to go with the tables being collapsible?

**Comment by CB987** [comment]
<img width="481" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzJQQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44439bb70af93b310f094c8a81a8d08226bc941d/screencapture-localhost-3000-concern-parent-79ea3004-c6ec-4d7b-8aa5-87fa91b89588-file-sets-5a54d5c9-5e4c-482e-9112-476871555eb2-2024-08-27-15_13_38.png" alt="screencapture-localhost-3000-concern-parent-79ea3004-c6ec-4d7b-8aa5-87fa91b89588-file-sets-5a54d5c9-5e4c-482e-9112-476871555eb2-2024-08-27-15_13_38.png" />

**Comment by eporter23** [comment]
@CB987 - I think we should start with the tables not being collapsed, and then we can add that later if people want it.

**Comment by CB987** [comment]
Great! Thanks.

**Comment by CB987** [comment]
work done but getting a circleCI test error, so i need to consult backend.

**Comment by CB987** [comment]
PR #[483](https://github.com/emory-libraries/dlp-selfdeposit/pull/483) -- this one is css heavy so i want Max's review.

**Comment by eporter23** [comment]
Looks great to me! Let me know if you still want @maxdmayhew to review it before we close this.

**Comment by CB987** [comment]
@eporter23  As long as there's nothing broken, any refactoring it might need can be done down the line I think, assuming that's ok with you. Thanks!

**Comment by eporter23** [comment]
Thanks, closing!
