### ISSUE TITLE
Hide Administrative Metadata from non-Admins on View Work page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#474]
For this ticket, we want to hide the display of Administrative Metadata from the View Work page, so that regular users are not seeing internal notes or irrelevant metadata entries.

These are the same fields as what we have grouped in the Create/Edit work form under the Administrative Metadata section.

- [ ] rights_statement
- [ ] emory_ark
- [ ] internal_rights_note
- [ ] staff_notes
- [ ] system_of_record_ID
- [ ] emory_content_type
- [ ] holding_repository
- [ ] institution
- [ ] data_classification
- [ ] deduplication_key

**Comment by CB987** [comment]
<img width="272" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnVnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c823f10422abb26477563cfc0af3c0394a42f3cb/admin_logged_in_metadata.png" alt="admin_logged_in_metadata.png" />
<img width="470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5dfacccc45b150d5c955545c9cdb15b31894d9f/not_logged_in_metadata.png" alt="not_logged_in_metadata.png" />

**Comment by CB987** [comment]
need to update the tests

**Comment by eporter23** [comment]
Looks great! And the content selections truly showcase this perfectly.
