### ISSUE TITLE
DC files don't need to be migrated

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#496]
As an additional refinement on the bulk-import process, we have confirmed with stakeholders that as part of our migration strategy, we do not want to migrate the "DC" datastream files. These files are less useful and less detailed than the MODS/descMetadata files and are not needed.

- [ ] Remove the DC entries from the files in the CSV generated for Bulkrax

**Comment by eporter23** [comment]
This could be addressed in the export process

**Comment by bwatson78** [comment]
@eporter23 Would addressing this only from the migration script side of things suffice, or should I also block `DC` files from the bulkrax importer?

**Comment by eporter23** [comment]
I'm thinking that blocking them from the CSV file generated for Bulkrax would be more essential than omitting them from the export, but let me know if you disagree. The long term goal is to move the files in EFS into Glacier storage so if the DC files get exported, that is fine, but we don't need to ingest them.

**Comment by eporter23** [comment]
I see no DC.xml entries in the most recent processed export CSV file, and will test this further in the next 1000 pid ingest.

**Comment by eporter23** [comment]
Based on the most recent export and ingest, this looks resolved - thanks!
