### ISSUE TITLE
Sprint 16 Styling Punchlist

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#497]
Please review the [styling punchlist](https://docs.google.com/document/d/1NdMtcLBTm7t97ewXT3KwNPYGxGgyowCrHyQ2VdKkJz0/edit#heading=h.rg8jehszi0hy) for any open items.
At the end of the sprint we will assign an estimate for time spent.

**Comment by CB987** [comment]
- item 23, 1 estimate.

**Comment by CB987** [comment]
- item 24, 2 pts.

**Comment by maxdmayhew** [comment]
- item 26, 1 point

**Comment by maxdmayhew** [comment]
item 27, 1 point 

unable to upload finished image on the google doc so here it is
<img width="1073" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGplQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63e3147594539130d7e8f92dd617507079305600/Screenshot%202024-09-17%20at%2010.34.54%E2%80%AFAM.png" alt="Screenshot 2024-09-17 at 10.34.54 AM.png" />

**Comment by eporter23** [comment]
Closing this out - I've tested most of the recently deployed items. Thanks!
