### ISSUE TITLE
Dashboard: searchbox behavior [spike]

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#498]
When logged in and navigating the Dashboard section of the UI, there seems to be a conflict between the Dashboard search and the global header search box.  In general the Dashboard search functions independently of the main public search (in a vanilla Hyrax, the Dashboard only shows the dashboard search function). We also expect that this will impact Admin users primarily, because they will have many works to navigate through compared to regular, infrequent depositor users.

Expected behavior
A user can perform a search that is contextual to the section of the interface they are interacting with (Works, Collections, etc.) and the list of assets will be limited, based on the search terms entered. This will return results (or not) with UI updates reflected in that specific section of the page only.

<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZ6Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2372e60451ca6140d1c943f162621895f17f4e7/Screenshot%202024-09-05%20at%2011.37.24%E2%80%AFAM.png" alt="Screenshot 2024-09-05 at 11.37.24 AM.png" />

Current behavior

If a user is in Dashboard > Works or Dashboard Collections and enters a search term with matches, but then also enters a term in the header search box, the Dashboard search results/filters are removed and no results are found.  

<img width="1334" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMyt6Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--474342497730a036e8ba19fc78e590b3f7ca7be8/Screenshot%202024-09-05%20at%2011.43.08%E2%80%AFAM.png" alt="Screenshot 2024-09-05 at 11.43.08 AM.png" />

Possible options

- If the 2 search functions are conflicting with each other, we could try to remove the search box from the header if a user is in the Dashboard mode.
- If we adjust the header for the Dashboard view(s) to remove the header search, we could also investigate UI conventions to return the user to the homepage, if the lack of a search box is confusing.
- If we want to try to allow both search boxes to function, we should make sure that users are taken back out to the "public" search UI to see results. This is probably even more confusing and less optimal.

**Comment by CB987** [comment]
fairly straightforward to remove the header search box for certain paths. <img width="1490" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWE0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7818eb992523778f26dda51217ad2689b76a625b/Screenshot%202024-09-06%20at%2012.22.54%E2%80%AFPM.png" alt="Screenshot 2024-09-06 at 12.22.54 PM.png" />

do we also want to remove it for /dashboard/collections/###?
<img width="1289" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVc0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--837fa1981a233d9d7f07781e45577f8226b05d7d/Screenshot%202024-09-06%20at%2012.21.56%E2%80%AFPM.png" alt="Screenshot 2024-09-06 at 12.21.56 PM.png" />

**Comment by CB987** [comment]
@eporter23 thoughts?

**Comment by eporter23** [comment]
@CB987 the above look great! I am not sure how many different dashboard/paths there are, but it may be wise to use that "return to full site search" on all of them just in case.

**Comment by CB987** [comment]
not everything under /dashboard/ has a search box in the body, so i didn't know if it would be better to call out individual pages, depending on how many there are-- just /works, /my/works, /collections, /my/collections?

**Comment by eporter23** [comment]
I just clicked around a bit and checked that, but if you enter a search it does seem to target you back to Works for some reason. So I think it would be easier to not try to figure all of that out and just reinforce to users that Dashboard search is separate from the main search. That said, I am not sure if we should take them back to the homepage or to a blank search? Such as https://oe24-test.libraries.emory.edu/catalog?locale=en&importer_id=10&search_field=all_fields&q=
