### ISSUE TITLE
Mockups for Search Results page layout [placeholder]

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#499]
For this ticket, we want to create mockups to enhance the layout of Search Results.
This ticket is also partially dependent on work to configure the metadata fields shown on the results page for each matching entry. 

Possible areas to address:

- Width of the metadata values (vs. labels): the values seem to be very constrained while there is still a lot of room to the right of the results list
- Line breaks between multi-valued fields
- Prevent word-breaks across lines

As an example of the above concerns:

<img width="1405" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3pVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45475216c9d1800a0f95e67bbaa238de303513cd/Screenshot%202024-09-13%20at%2012.49.39%E2%80%AFPM.png" alt="Screenshot 2024-09-13 at 12.49.39 PM.png" />

**Comment by CB987** [comment]
<img width="1006" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWZiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0b4b0edb8cac18a0deba3ebdca45db64b39ac54/Screenshot%202024-09-16%20at%207.46.20%E2%80%AFPM.png" alt="Screenshot 2024-09-16 at 7.46.20 PM.png" />

**Comment by CB987** [comment]
<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWpiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f6e4ef6d9ba1557f8bc34190b8c869540f04ad7/Screenshot%202024-09-16%20at%207.21.32%E2%80%AFPM.png" alt="Screenshot 2024-09-16 at 7.21.32 PM.png" />
this is pretty close to the fonts + styling of search (search doesn't have a thumbnail).

**Comment by eporter23** [comment]
@CB987 that looks great, so much better! One comment, I think I'd prefer to not use Cardo/serif on the metadata field labels. Even though that is what Library Search uses, digital.library uses Open Sans for those, and I'd like to keep those 2 repository UIs consistent where possible.

**Comment by eporter23** [comment]
@CB987 FYI, here's what the revised metadata fields enabled for display look like as of today's deployment, in case it impacts your mockups in any way <img width="1535" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMERnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d03052cb444d0c1f3bd72b533fe15c87cf1b7773/Screenshot%202024-09-17%20at%201.52.35%E2%80%AFPM.png" alt="Screenshot 2024-09-17 at 1.52.35 PM.png" />

**Comment by CB987** [comment]
perfct! thank you

**Comment by CB987** [comment]
<img width="1065" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejdzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f5bdf538f6c49eabd80fba0744d6e5db70aa231/Screenshot%202024-09-19%20at%206.34.08%E2%80%AFPM.png" alt="Screenshot 2024-09-19 at 6.34.08 PM.png" />

**Comment by CB987** [comment]
<img width="1272" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3J2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c13fd12b4178821ed02116efcea824bb1bb3d77/Screenshot%202024-09-20%20at%2012.47.33%E2%80%AFPM.png" alt="Screenshot 2024-09-20 at 12.47.33 PM.png" />
<img width="1252" 
src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzN2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da1b671653732c3d08e5ba9729fa187a6f58a33a/Screenshot%202024-09-20%20at%2012.49.05%E2%80%AFPM.png" alt="Screenshot 2024-09-20 at 12.49.05 PM.png" />
<img width="821" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeER3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35b283359ff19b76c42f68610f524a1528269f3a/screencapture-localhost-3000-catalog-2024-09-20-13_40_39.png" alt="screencapture-localhost-3000-catalog-2024-09-20-13_40_39.png" />

**Comment by CB987** [comment]
ready for your feedback @eporter23

**Comment by eporter23** [comment]
Looks great and thanks for the verbosity in sample data!
