### ISSUE TITLE
Increase CPUs for oe24-test environment for Redis/Hyrax imports

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#502]
In sprint planning today we discussed increasing the number of CPUs to a minimum of 8 in the hopes of getting closer to the defaults needed for better redis performance.

**Comment by jcrompton42** [comment]
after a discussion with Brad and Collin we decided that the CPU limit is most likely not the issue and Brad will be working with pooling connection settings on the client side and we will not do this unless it does appear to be the bottleneck.
