### ISSUE TITLE
implement dashboard search

### ISSUE THREAD

**Issue by CB987** [emory-libraries/dlp-selfdeposit#503]
implement from Dashboard: searchbox behavior [spike]#498
remove site search from header in /dashboard
provide a button to return to full search

**Comment by CB987** [comment]
implement from Dashboard: searchbox behavior [spike]#498
remove site search from header in /dashboard
provide a button to return to full search

**Comment by CB987** [comment]
<img width="1720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG0rQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90cc2ce71c2d901d191ee41406825bee67df1e08/Screenshot%202024-09-09%20at%2011.54.34%E2%80%AFAM.png" alt="Screenshot 2024-09-09 at 11.54.34 AM.png" />
any page under the /dashboard/ path has this button, which redirects to /catalog/

**Comment by CB987** [comment]
https://github.com/emory-libraries/dlp-selfdeposit/pull/504

**Comment by eporter23** [comment]
Looks great, thanks!
