### ISSUE TITLE
Facets: limit number of initial results

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#505]
For this ticket, we want to enhance the display of facets which may contain many values. This is similar to work we have done in Lux and Library search.

QUESTION: in Hyrax, if there are more values than the default set, will it then direct a user to a "More" modal window like we see in Library Search and Lux/digital.library? (If not, this ticket will need to be re-scoped)

Please adjust the default number of values displayed to 10 maximum for all facets. This will primarily impact the following:

Author
Date
Journal or Parent Publication Title
Keyword

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/562

**Comment by eporter23** [comment]
Looks good! Thanks @bwatson78
