### ISSUE TITLE
Sprint 17 Styling Punchlist

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#524]
Please review the [styling punchlist](https://docs.google.com/document/d/1NdMtcLBTm7t97ewXT3KwNPYGxGgyowCrHyQ2VdKkJz0/edit#heading=h.rg8jehszi0hy) for any open items.
At the end of the sprint we will assign an estimate for time spent.

New entries start at item 28.

**Comment by maxdmayhew** [comment]
PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/529

<img width="423" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1B2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fc2c6263d770cb4603d93a0e5b4c10d237a2500/image.png" alt="image.png" />

PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/532

<img width="798" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1R2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93912e48168c82b3648630c02cd862b5a743d35c/image.png" alt="image.png" />

**Comment by maxdmayhew** [comment]
https://github.com/emory-libraries/dlp-selfdeposit/pull/539 30 and 32, total of 1.

**Comment by CB987** [comment]
^ merged

**Comment by maxdmayhew** [comment]
PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/554

35 on punchlist
formatting for sass files
switch appropriate styles from px to rem
removed preservation_event_table.scss and moved its contents to layout.scss

**Comment by maxdmayhew** [comment]
<img width="626" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBellmQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3bb734fb383f0b1b3c6fd45df36099dd68ac32e/Screenshot%202024-10-03%20at%2012.31.47%E2%80%AFPM.png" alt="Screenshot 2024-10-03 at 12.31.47 PM.png" />

a few more minor changes to 554
<img width="684" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekVmQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--927d1369b3e54b40b462167b5577766407229e94/Screenshot%202024-10-03%20at%2012.30.26%E2%80%AFPM.png" alt="Screenshot 2024-10-03 at 12.30.26 PM.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelFmQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e7fa4c69b4af70d761b02fa6eb6e1adde8e2f92/Screenshot%202024-10-03%20at%2012.31.10%E2%80%AFPM.png" alt="Screenshot 2024-10-03 at 12.31.10 PM.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek1mQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f03d46ed2d8d5803bfc49ca25cccda975729649/Screenshot%202024-10-03%20at%2012.30.48%E2%80%AFPM.png" alt="Screenshot 2024-10-03 at 12.30.48 PM.png" />

**Comment by eporter23** [comment]
Thanks @maxdmayhew and @CB987 !
