### ISSUE TITLE
Implement layout changes for Search Results page

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#528]
This ticket follows work done in #499. For this ticket, we want to implement the changes identified in the mockup.

**Comment by CB987** [comment]
<img width="947" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS8zQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11927c6f0edb47c499c18349c272ca29d6de6984/screencapture-localhost-3000-catalog-2024-09-23-16_51_17.png" alt="screencapture-localhost-3000-catalog-2024-09-23-16_51_17.png" />

**Comment by CB987** [comment]
[PR#537](https://github.com/emory-libraries/dlp-selfdeposit/pull/537)

**Comment by eporter23** [comment]
@CB987 looks good, and I know this one has been complicated! Here is one example of where an extremely long entry is doing an awkward word-break. In looking at the term list [here](https://github.com/emory-libraries/dlp-selfdeposit/blob/main/config/authorities/licenses.yml) I _think_ this is the longest possible value. Let me know if you'd prefer that I split this out as a new ticket.

<img width="1900" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGMyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f8157d2f323a7f1954ddaa70a1f058cd1f11356/Screenshot%202024-10-09%20at%2012.49.02%E2%80%AFPM.png" alt="Screenshot 2024-10-09 at 12.49.02 PM.png" />

**Comment by eporter23** [comment]
@CB987 I'm going to close this one and add a new ticket to fix the above.
