### ISSUE TITLE
Setup groups for OpenEmory

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#53]
As we will structure OpenEmory as a Collection, we want to ensure that there are Collection-level permission groups established in Hyrax so that we can move users in and out of these groups as needed over time. Since we don't yet have Shibboleth in place, we can hold off on assigning users to the Collection groups right now.

For this ticket, we may need to review if the current state of Hyrax 5 can allow an admin user to create roles/groups in the UI, and whether assignments made in the UI will persist through deployments.

Please create the following Collection groups for Hyrax:

OE Viewer
OE Depositor
OE Manager

We also want to ensure the default Admin group is in place for the new Hyrax.

**Comment by alexBLR** [comment]
@eporter23 I am not sure we have created a collection yet

**Comment by eporter23** [comment]
@alexBLR no, we haven't. For this ticket, I was hoping we could get the group entities in place ahead of time and then assign them to the Collection that will be created later.

**Comment by eporter23** [comment]
For this ticket, we may need to review if the current state of Hyrax 5 can allow an admin user to create roles/groups in the UI.

**Comment by alexBLR** [comment]
<img width="1231" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm1yQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97674d67073dbb022f4dcccaa667e04ac01c61e4/Screen%20Shot%202024-03-04%20at%2010.01.22%20AM.png" alt="Screen Shot 2024-03-04 at 10.01.22 AM.png" />

**Comment by alexBLR** [comment]
<img width="1231" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2VyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e0d885f120a5d894bda256d674ee164fc7e44d1/Screen%20Shot%202024-03-04%20at%2010.01.22%20AM.png" alt="Screen Shot 2024-03-04 at 10.01.22 AM.png" />

**Comment by eporter23** [comment]
Thanks @alexBLR!  I was able to assign the 3 OE groups to the Default Admin Set and the initial Test Collection. Seems to have gone through okay, we will keep this open until we do our next deploy to make sure groups created in the UI persist through deploys. <img width="1099" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVMwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08aba9509d824d60e715761b5a5cc24442119441/Screenshot%202024-03-05%20at%202.21.36%E2%80%AFPM.png" alt="Screenshot 2024-03-05 at 2.21.36 PM.png" />

**Comment by eporter23** [comment]
These groups persisted through a new deployment, thanks @alexBLR !
