### ISSUE TITLE
front end clean up

### ISSUE THREAD

**Issue by maxdmayhew** [emory-libraries/dlp-selfdeposit#540]
styling clean up etc.

**Comment by maxdmayhew** [comment]
<img width="914" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkg3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d511dd32b9311e2b07e0b5bc02c60894d99ed859/Screenshot%202024-09-24%20at%203.01.46%E2%80%AFPM.png" alt="Screenshot 2024-09-24 at 3.01.46 PM.png" />
<img width="1256" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkw3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f436dd45fe3d58cd6b527aebb7de4bd323c9f02d/Screenshot%202024-09-24%20at%203.01.50%E2%80%AFPM.png" alt="Screenshot 2024-09-24 at 3.01.50 PM.png" />
<img width="976" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlA3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--236d21e8549262fe92253d29d9237f6375e0c648/Screenshot%202024-09-24%20at%203.02.09%E2%80%AFPM.png" alt="Screenshot 2024-09-24 at 3.02.09 PM.png" />
<img width="1264" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlQ3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc2634ca353da704a913b29a24b59392f682df69/Screenshot%202024-09-24%20at%203.02.18%E2%80%AFPM.png" alt="Screenshot 2024-09-24 at 3.02.18 PM.png" />

header mobile menu fix

**Comment by maxdmayhew** [comment]
<img width="1374" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0FLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b685fcbf2fa9c65ef0fa7652d6f646c89610683/Screenshot%202024-09-27%20at%203.23.24%E2%80%AFPM.png" alt="Screenshot 2024-09-27 at 3.23.24 PM.png" />

I spoke with @eporter23 about altering the look of search a bit so it is more in line with digital.

PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/546

**Comment by maxdmayhew** [comment]
<img width="775" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHdWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3d55b7a7081810777e6885b9d66becb6e1e8595/image.png" alt="image.png" />


<img width="767" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGtWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--952022455e95c3a754d72f91874744f267f7affe/image.png" alt="image.png" />

updated file upload page to use bootstrap components and emory buttons as well as got rid of the table.

PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/550

**Comment by maxdmayhew** [comment]
Once this PR is approved, I think enough work has been done in this ticket if that's okay with the team. 

Ready to be deployed/reviewed

**Comment by maxdmayhew** [comment]
Oh that's odd, it should be blue. That sounds like an easy enough change though. We can put this back into progress and I will check it out next week!

**Comment by eporter23** [comment]
@maxdmayhew no, my comment and screenshot was referring to the fact that I haven't uploaded anything yet state. So the fact that it's got a really dark grey solid status before you've uploaded is what I wanted to talk about.

**Comment by eporter23** [comment]
Closing this one and we can chat about the file upload bar in the other ticket! Thanks!
