### ISSUE TITLE
Write callback middleware for Shib

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#542]
Auth is occurring but in our normal implementation of Shibboleth the content would be determined to be "secured" or not on the same server as the application, so there needs to be some middleware to handle that transaction across our servers in this implementation.

**Comment by kbowaterskelly** [comment]
<Location /Shibboleth.sso/SAML2/POST>
    RewriteEngine On
    # Capture the RelayState parameter
    RewriteCond %{QUERY_STRING} RelayState=([^&]+) [NC]
    RewriteRule ^ - [E=RELAY_STATE:%1]

    # Route to Arch environment
    RewriteCond %{ENV:RELAY_STATE} ^https?://oe24-arch\.library\.emory\.edu [NC,OR]
    RewriteCond %{HTTP_REFERER} ^https?://oe24-arch\.library\.emory\.edu [NC]
    RewriteRule ^(.*)$ http://oe24-arch.library.emory.edu/users/saml/auth [P,L]
    # Route to Test environment
    RewriteCond %{ENV:RELAY_STATE} ^https?://oe24-test\.library\.emory\.edu [NC,OR]
    RewriteCond %{HTTP_REFERER} ^https?://oe24-test\.library\.emory\.edu [NC]
    RewriteRule ^(.*)$ http://oe24-test.library.emory.edu/users/saml/auth [P,L]
    # Route to Production environment
    RewriteCond %{ENV:RELAY_STATE} ^https?://oe24\.library\.emory\.edu [NC,OR]
    RewriteCond %{HTTP_REFERER} ^https?://oe24\.library\.emory\.edu [NC]
    RewriteRule ^(.*)$ http://oe24.library.emory.edu/users/saml/auth [P,L]
    # Default fallback if none of the above match
    ProxyPass http://oe24.library.emory.edu/users/saml/auth
    ProxyPassReverse http://oe24.library.emory.edu/users/saml/auth
</Location>

**Comment by kbowaterskelly** [comment]
I have implemented a reverse proxy and I believe I need an expected value to pass back from there

Discussed that with Zo and waiting to hear back from him today

See: https://oe24-arch.libraries.emory.edu/users/saml/auth

**Comment by eporter23** [comment]
Zo and Beth are working on some errors in the arch environment - current state is when we make a request to Shib and we login, we are returned a "get" request. Next step is to look at the referrer header but also to determine which header is needed.
