### ISSUE TITLE
Fileset processing/cleanup process

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#544]
For this ticket, we want to create a post-ingest cleanup job related to files not being characterized, etc., similar to what we built for Curate.

**Comment by bwatson78** [comment]
@alexBLR https://github.com/samvera/hyrax/blob/aeb5e3e57c113069e19fbd0c1102b3098c032fc0/app/jobs/valkyrie_characterization_job.rb

And an easy way to pull a FileSet's FileMetadata ID is, if `fs` contains the fileset, running `fs.original_file_id`.

**Comment by eporter23** [comment]
PR in draft

**Comment by eporter23** [comment]
@eporter23 will create a new ticket to test this and then close this one.

**Comment by eporter23** [comment]
Thanks Zo! Closing this because I've written up a new ticket to run the job.
