### ISSUE TITLE
Re-style fileuploader form components

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#547]
This is a placeholder ticket for work that has already been started.

**Comment by eporter23** [comment]
@maxdmayhew I wrote this up after our meeting on Friday, but please let me know if we should add more details to it because you had already been working on it.

**Comment by maxdmayhew** [comment]
https://github.com/emory-libraries/dlp-selfdeposit/pull/550

this has already been merged.

**Comment by eporter23** [comment]
@maxdmayhew I am guessing this was the work that had already been done in #375 before further revising the styling? Please let me know and we can close this.

**Comment by maxdmayhew** [comment]
https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/540

This is the ticket for the file upload styling. The upload bar should be blue instead. You can close out the other ticket and put this ticket back into progress if you would like. Sorry for the confusion on my end!

**Comment by eporter23** [comment]
@maxdmayhew reporting some odd behavior I'm seeing in Mac Chrome vs. Mac Firefox:

Chrome (doesn't seem to show your recent changes):
<img width="737" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzVaQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17aa14bb8274d72f47e21f81cbcd34ad4ee7c79f/Screenshot%202024-10-18%20at%2010.20.09%E2%80%AFAM.png" alt="Screenshot 2024-10-18 at 10.20.09 AM.png" />

**Comment by eporter23** [comment]
Mac Firefox: shows a mix of styles

<img width="985" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEZaQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f918316d6ed0782760f916797e2f2b4badcb1ab7/Screenshot%202024-10-18%20at%2010.19.07%E2%80%AFAM.png" alt="Screenshot 2024-10-18 at 10.19.07 AM.png" />

**Comment by eporter23** [comment]
@maxdmayhew Firefox is looking good now, but I am still seeing the dark gray color on the un-uploaded status bar in Mac safari and Mac Chrome: 

<img width="829" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTZFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b4b384517b8047df0ccf1013010f9a2289a4be2/Screenshot%202024-10-30%20at%2010.10.31%E2%80%AFAM.png" alt="Screenshot 2024-10-30 at 10.10.31 AM.png" />

**Comment by eporter23** [comment]
I'm going to close this ticket and potentially create a bug ticket for it, since we have more important tickets coming up.
