### ISSUE TITLE
Implement header styling and EUL elements

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#55]
Please refer to the mockup in #29. We should implement the second version linked in the comments.

The header should include links to:

Home: / (Standard Hyrax application navigation link)
About: /about (Standard Hyrax application navigation link)
Help: /help (Standard Hyrax application navigation link)
Contact: /contact (Standard Hyrax application navigation link)

The header should also include required Emory/Libraries elements and link conventions. If the conventions are not well established across applications, please default to:

Emory Shield: / (root of Hyrax application)
Emory University: emory.edu
Emory Libraries:  libraries.emory.edu

**Comment by CB987** [comment]
<img width="609" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0xVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24329d207bef7a43dc602c65d5a94e5fa881a4b0/Screenshot%202024-03-12%20at%203.37.51%E2%80%AFPM.png" alt="Screenshot 2024-03-12 at 3.37.51 PM.png" />

**Comment by eporter23** [comment]
Thanks @CB987! I think this looks good to go for deploying and testing. I know this was a monster ticket, so please feel free to increase the estimate if you need to.

**Comment by eporter23** [comment]
Note: there are some variants in different views in the app.

**Comment by eporter23** [comment]
@CB987 thanks for all the great work on this! I think this is good to close. I will write up some new tickets about how we want to handle the header on different page types once I track down how many variations of them there.
