### ISSUE TITLE
ORCID: form input validation

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#555]
Add a custom input validation rule that checks for a valid, correctly formatted ORCID id.

This ticket follows work to build out the ORCID input field on the form and [display it as a hyperlink](https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/376), but these both expect certain formatting conventions.

Desired behavior:

- A user should either be allowed to input the ORCID id without the domain, but include the hyphens.
- If a user enters a full URL for their ORCID ID, we should either trim that value to the ID only, or prompt the user to enter only the ID component.

Examples of a correctly formatted ID component:

ID component only: 16 digits separated by 3 hyphens
`0000-0002-2093-5650`

Fully qualified ORCID ID URL: starts with https://orcid.org/, followed with the ID as formatted above
`https://orcid.org/0000-0002-2093-5650`

Unwa

**Comment by maxdmayhew** [comment]
Going to make this an overestimate of 8 since code-climate gave me a bit of a fuss last time I worked on a javascript ticket.

**Comment by maxdmayhew** [comment]
What would you like for the error message to be? @eporter23

**Comment by eporter23** [comment]
@maxdmayhew first pass for an error message: "Please enter either the full ORCID URL to your profile or only the ID section of your ORCID id, starting after https://orcid.org/."

**Comment by maxdmayhew** [comment]
There’s a bug for the ORCID ID. It’s pretty weird. If you add an ORCID ID like https://orcid.org/0000-0002-2093-5650 it will like move the ORCID ID to the institution field when you try and edit the same publication again. It also doesn’t render the little ORCID ID logo on the publication listing page.

**Comment by maxdmayhew** [comment]
Spoke with @eporter23, going to use the standard XXXX-XXXX-XXXX-XXXX ORCID ID format for now.

I do need the verbiage for what the error message should say though!

**Comment by eporter23** [comment]
"Please enter only the ID section of your ORCID id, starting after https://orcid.org/"

**Comment by eporter23** [comment]
I think this has been deployed, but I am not seeing any validation prompts. Let me know if this has not yet been deployed. <img width="1264" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUNlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f979e3045cd7760269d52948f4411cb167eb66e2/Screenshot%202024-11-06%20at%2012.57.48%E2%80%AFPM.png" alt="Screenshot 2024-11-06 at 12.57.48 PM.png" />

<img width="1180" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUtlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3a2fb2ad1937b6352cafb25e2ee31122d86f11c/Screenshot%202024-11-06%20at%2012.58.04%E2%80%AFPM.png" alt="Screenshot 2024-11-06 at 12.58.04 PM.png" />

**Comment by maxdmayhew** [comment]
this is a bigger issue, the script does not account for multi-valued fields. It let you load because the first author doesn't have an ORCID ID so it doesn't check it. Its only validating for the first author.

We need to make a new ticket as I'll need to account for this for all multi-valued fields. I am so sorry. This is totally my fault.

**Comment by eporter23** [comment]
Yes, I'll work on that and double check for any other fields that may be impacted.

**Comment by eporter23** [comment]
Thanks @maxdmayhew - looks good so far when testing against the ID-only format validation! And I will work on the followup ticket.
