### ISSUE TITLE
Sprint 19-20 Styling Punchlist

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#557]
Please see the [running punchlist](https://docs.google.com/document/d/1NdMtcLBTm7t97ewXT3KwNPYGxGgyowCrHyQ2VdKkJz0/edit#heading=h.rg8jehszi0hy) document for additional entries.

We will estimate this as work as is completed.

**Comment by CB987** [comment]
i have a [PR](https://github.com/emory-libraries/dlp-selfdeposit/pull/615) with items 36-39 ready for when max is back.
so far 8.

**Comment by eporter23** [comment]
The broken image issue probably merits a bug ticket.

**Comment by eporter23** [comment]
@CB987 thanks! 36 looks good. I'm having a little trouble testing 38 due to a strange bug which I filed a ticket for. 39 looks good too!

**Comment by eporter23** [comment]
I was able to manually locate a work that was still under review. Looks great! <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHlvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--638cf42abd7c08e6a04991dbae3200ef96be8214/Screenshot%202024-11-08%20at%2010.53.56%E2%80%AFAM.png" alt="Screenshot 2024-11-08 at 10.53.56 AM.png" />
