### ISSUE TITLE
Implement footer styling and EUL elements

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#56]
Please refer to the footer mockup in #29 for more detail.

The footer should include links to:

- [x] About OpenEmory: /about 
- [x] Help and Deposit Instructions: /help
- [x] Contact Us: /contact
- [x] Open Access Policy: https://libraries.emory.edu/research/open-access-publishing/emory-repositories-policies/about (open in new tab)

The footer should also include:

- [x] Required Emory/Libraries elements
- [ ] Samvera software statement
- [ ] Version of OpenEmory/Hyrax currently deployed and date (see [Curate](https://curate.library.emory.edu) for an example)

**Comment by maxdmayhew** [comment]
<img width="1267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHkxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e36a00549168ab9906d8c43efa740380d96bdab/Screenshot%202024-03-05%20at%203.33.11%20PM.png" alt="Screenshot 2024-03-05 at 3.33.11 PM.png" />

the open access policy link is hardcoded for the time being and does not work but it's there in spirt. 🦅
