### ISSUE TITLE
Dashboard: Resource Types Chart

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#575]
Hyrax provides a basic dashboard with 3 graphs. One of these, Resource Types, assumes that we are using the default Hyrax resource types metadata field, and since we don't use that field, it just shows 100% "unknown".

For this ticket, we want to try to revise the graph to pull from our locally defined content_genre field (Article, Book, etc.). 

- [x] Change the chart heading to say "Publication Type" instead of "Resource Type"
- [x] Try to reconnect the existing chart behavior to full from `content_genre` 
- [x] If we can't get the chart to work as expected, please suppress it from display

Expected behavior:

In https://pg.nurax.samvera.org/dashboard?locale=en if you log in as administrator, you can navigate to the charts view and then see a breakdown of different types. Mousing over the chart will change the display to show counts of each type.

<img width="694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXRPQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8610fee314d449f59e9f841d02838154d4d9f71/Screenshot%202024-10-16%20at%208.56.45%E2%80%AFAM.png" alt="Screenshot 2024-10-16 at 8.56.45 AM.png" />

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/582

**Comment by eporter23** [comment]
Looks great @bwatson78 - these counts correlate with our facet counts (there are some content_genres that need manual cleanup but I'm aware of those).
