### ISSUE TITLE
Unwanted blank second entries on certain fields when editing in the form: spike ticket

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#576]
This may be a default Hyrax behavior or bug, but in order to have a more user friendly form for depositors, we should investigate if the following can be addressed. This also relates to the issue described in #569.

When a user edits an existing work, a blank entry with a "remove" button appears even if they have not entered anything or clicked the Add Another link beneath it.
This behavior applies to certain fields that Hyrax defaults to being multivalued, but we locally define as single valued.

Title
Publisher
Copyright Statement

This behavior also applies to all other non-required, multivalued fields such as:
Final Published Version
Grant/Funding Information

**Comment by eporter23** [comment]
Discussion: we need to strategize how to address this because it involves persistence behaviors as well as view/display behaviors as well as the form input behaviors.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/593

**Comment by eporter23** [comment]
To test, go through the originally documented Edit steps and save a change. The UI doesn't change.

**Comment by eporter23** [comment]
To do: Emily will provide a set of ~100 IDs and send to Brad to be run on oe24-test

**Comment by eporter23** [comment]
I repeated the steps to trigger this issue as noted in #569 but it is still recurring. <img width="1688" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkNlQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--930607357df52916e6d7e2fd751da78022e4c80d/Screenshot%202024-11-06%20at%201.09.24%E2%80%AFPM.png" alt="Screenshot 2024-11-06 at 1.09.24 PM.png" />

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/620

**Comment by eporter23** [comment]
This appears to be resolved. Thanks!
