### ISSUE TITLE
Dashboard growth widget [spike]

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#578]
For this ticket, we want to investigate what the expected behavior for the Dashboard Growth widget is, and whether or not it is functional in Hyrax 5. Historically, this widget has shown the daily/incremental growth of new additions (it is not a cumulative report). 
To access this widget, login as Admin, then navigate to the main Dashboard page, e.g. https://oe24-test.libraries.emory.edu/dashboard?locale=en 

For this ticket, please:

- [x] Review the current behavior in Curate vs. Hyrax 5
- [x] Document findings about whether the Hyrax 5 element is functioning as intended (only showing 10 per day maximum)
- [x] Document anticipated work to either fix this element, or suppress it from display

Current Behavior: Curate

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnFFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--875994edad7a78e2a4f6b6384f3a249a8a6adaab/Screenshot%202024-10-30%20at%2010.17.49%E2%80%AFAM.png" alt="Screenshot 2024-10-30 at 10.17.49 AM.png" />

Current behavior: Self Deposit
While we loaded 1000 works in the past week, we only see a maximum of 10 reported.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ced83d0a0b43e9ae0ac0b3e61bf356ded8a9271/Screenshot%202024-10-30%20at%2010.21.53%E2%80%AFAM.png" alt="Screenshot 2024-10-30 at 10.21.53 AM.png" />

Current Behavior: Nurax.pg
NOTE: it is unclear if nurax.pg has had any recent activity, but it is showing the same cutoff at 10 works total.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--401a3f76e893ff837d82269c188698a2303de267/Screenshot%202024-10-30%20at%2010.22.54%E2%80%AFAM.png" alt="Screenshot 2024-10-30 at 10.22.54 AM.png" />

Expected behavior:
We should see more than 10 results a day when activity is known to have occurred.

**Comment by bwatson78** [comment]
Preliminary Findings: The search used to find the amount of objects over time is being limited to 10. Since the search is a new class instituted for Valkyrie, I will attempt to override that class and delimit the object list.

**Comment by bwatson78** [comment]
After some tinkering, I've found that the query that the new Valkyrie search service performs doesn't actually limit its response to just the Works, but returns all of the objects within the Solr directory. @eporter23 My instincts are to remove this graph from view, confirm the behavior in Koppie, and report my findings to the Hyrax issue list. What do you feel?

**Comment by eporter23** [comment]
I think that is fine. I'm normally tracking start and end counts on Works, FileSets, and Collection members after each ingest run and this graph isn't super helpful anyway.

**Comment by bwatson78** [comment]
Hyrax-specific bug reported: https://github.com/samvera/hyrax/issues/6974

**Comment by eporter23** [comment]
Basing this on arch where we have some data, all looks good.
