### ISSUE TITLE
Dashboard search: configure searchable fields

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#579]
This ticket involves making a first pass as a set searchable fields related to administrative activities in the Hyrax dashboard. These fields should be configured for the Dashboard > Works > search box.

<img width="1786" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGVGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--172c70c94812608a15862a68d4ea281b14cc5fe2/Screenshot%202024-10-30%20at%2012.22.04%E2%80%AFPM.png" alt="Screenshot 2024-10-30 at 12.22.04 PM.png" />

NOTE: this ticket assumes that we can configure a different set of searchable fields vs. what is configured for the main public search option. This was the case for Curate, but please report back if this is not configurable as expected.

- [x] Title (`title`)
- [x] IDs (`id`, `deduplication_key`, `system_of_record_ID`, and new equivalent to `alternate_id` when implemented)
- [x] Final published version (in case admins need to search by DOI) (`final_published_versions`)
- [x] Publisher (`publisher`)
- [x] Grant/Funding Information (`grant_agencies`, `grant_information`)
- [x] Authors (`creator`)

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/618

**Comment by eporter23** [comment]
Looks great so far! The only thing I can't test yet is `alternate_id`, so I'll wait until we get that settled.

**Comment by bwatson78** [comment]
Object with id `024fa302-7f3c-4e8f-aefb-53056c81989a` has an `emory_persistent_id` of `310jsxksqt-emory`--you can test that.

**Comment by eporter23** [comment]
Thanks - that one checks out.

**Comment by eporter23** [comment]
I'll go ahead and close this one since I have been able to test out a few of the alternate_ids on recently uploaded works. Thanks!
