### ISSUE TITLE
Dashboard > Works: filter by Collection

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#584]
In previous versions of Hyrax (such as we use for Curate), there used to be a Collection filter in the Dashboard > Works UI. This no longer appears to be offered in Hyrax 5. As we are doing migration of data, it will be very helpful to be able to use this type of filter in the Self Deposit UI to be able to see works that have ingested, but are not assigned to a Collection.

**Comment by eporter23** [comment]
Comment on my original description above, the standard Hyrax Works > Collection filter in the Dashboard does not show an "Unassigned" value. If it is possible to add this, that would assist with the problem. If it is not possible, it will still be helpful to filter works by Collection, because SCO does anticipate having some one-off thematic collections in addition to the primary OpenEmory collection assignment.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/593

**Comment by eporter23** [comment]
@bwatson78 - assuming this was deployed yesterday, I am not seeing any new filters in the Dashboard > Works UI? 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--020db1a12895a847a4a9168858ed4cc0fb07c09e/Screenshot%202024-10-30%20at%2010.30.58%E2%80%AFAM.png" alt="Screenshot 2024-10-30 at 10.30.58 AM.png" />

**Comment by bwatson78** [comment]
@eporter23 My apologies--I forgot to add that a full reindex needs to happen. If you just want proof that this would work, I'd recommend updating any one work and you should then see the Collection option there.

**Comment by eporter23** [comment]
Oh, gotcha! No worries, I'll make a few updates to works to test it further.

**Comment by eporter23** [comment]
Edited 2 works, and I can now see the filter showing 2 works. Thanks!
