### ISSUE TITLE
Optimize Fedora server disk space (logging etc.)

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#592]
After doing several large ingest batches, we are finding that the Fedora tomcat server disk space is filled up and we have identified this is caused by log files.

For this ticket we want to optimize the disk space needed to run large imports.

Ideas discussed in slack:
Optimize log rotation
Look at increasing default sizes of application disk space (default is 8GB)

Please make the recommended adjustments in all of our active environments: 

- [x] fedora-depo-arch
- [x] fedora-depo-test
- [x] fedora-depo-perf

**Comment by jcrompton42** [comment]
all our environments have more space, and ansible has been updated with default size of 30G specified for fedora instances and more restrictive logging rules in tomcat. 

PR https://github.com/emory-libraries/dlp-selfdeposit/pull/594

**Comment by eporter23** [comment]
Thanks @jcrompton42 ! I just got out of the Hyrax-Fedora 6 working group and I mentioned our Tomcat logging and disk space issues, and folks mentioned checking the logging level (so it's not super verbose), doing log rotation, and increasing the disk space just in case. So it sounds like we are doing all the right things!

**Comment by jcrompton42** [comment]
Checked on this and the number of logs being kept by fedora has been reduced. Closing.
