### ISSUE TITLE
Implement workaround for alternate_id

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#607]
This ticket follows previous work to implement Valkyrie alternate_id scheme using our own NOID scheme. We also learned when doing so, that the Valkyrie alternate_id creates an extra Fedora resource for each ID minted. 

For this ticket, we want to build on lessons learned in earlier tickets, and implement the findings from #541.

- [x] Continue to use our local ID scheme as currently minted
- [x] Create a new attribute that can be used on Collections, Works, FileSets
- [x] Adjust our persistent URL implementation to use the new attribute value for Collections and Works
- [x] Adjust indexing and search configurations that previously used alternate_id (#461 for searchable fields configuration)

Note: at this time, we do not need to present persistent URLs in the UI for FileSets, but we do want to continue minting and storing the local NOID ID for them.

TBD: do we need to spend any time remediating existing Collections and Works that use the older alternate_id implementation? Could we also write a rake task to do a cleanup on the older IDs to move them to the new attribute?

**Comment by bwatson78** [comment]
PR made: #616

**Comment by eporter23** [comment]
A rake task was also added. Once this is deployed we will run the rake task and then test the transfer functionality.

**Comment by eporter23** [comment]
The rake task now reindexes pre-existing objects including FileSets - this work is still in progress.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/622

**Comment by eporter23** [comment]
I created a new work and captured its alternate ID. This is working well with the new Dashboard search, but doesn't seem to be entirely functional in the main Public Search. 
Example: 733rv15dz5-emory
https://oe24-test.libraries.emory.edu/purl/733rv15dz5-emory
Search for 733rv15dz5-emory: https://oe24-test.libraries.emory.edu/catalog?locale=en&search_field=all_fields&q=733rv15dz5-emory

**Comment by bwatson78** [comment]
It's in the search return, but since the id contains emory as a substring, we might need to weight that particular field so that it comes first. 

I'll do that with my next PR, since I've run into some unexpected kinks in my remediation process. I'm going to iron those out and run the remediation manually (step by step).

**Comment by bwatson78** [comment]
More reliable remediation rake task running now.

**Comment by eporter23** [comment]
Testing this in oe24-arch, if I select a persistent ID and then enter it into the public search box, the application starts looping and will not either load or return an error.  Example: `904dncjszc-emory`

Other search terms work fine. The Dashboard > Works search box does find a match for the above ID.

**Comment by eporter23** [comment]
This may be testable in oe24-test now.

**Comment by eporter23** [comment]
This looks good. I've tested it on a few works and see no application lag and the first match by relevance is the specified ID.
