### ISSUE TITLE
Add controlled terms/vocabs to metadata fields

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#61]
Following on other work to configure the Hyrax "Publication" Work Type, we need to configure selected fields to use controlled terms.

As reference, we are working from the same [Metadata Implementation - Objects worksheet](https://docs.google.com/spreadsheets/d/1Z0ebRLaPa4bEJayvTiqwU4ulFglWrpQPgVX6r6v29uY/edit#gid=714216589).

Please re-use the controlled vocabulary configurations already established in Curate for the following:

- [x] holding_repository
- [x] institution
- [x] content_type (emory_content_type)
- [x] primary_language
- [x] publisher_version
- [x] place_of_production
- [x] sponsor
- [x] grant_agencies
- [x] rights_statement
- [x] data_classifications

Please modify the following fields for OpenEmory specifically:
- [x] content_genres: 
For this field, we want to create a new local term list that includes:

- Article
- Book
- Book Chapter
- Conference Paper
- Poster
- Presentation
- Report

**Comment by bwatson78** [comment]
@eporter23 Current licenses: https://github.com/emory-libraries/dlp-selfdeposit/blob/main/config/authorities/licenses.yml

**Comment by eporter23** [comment]
Thanks @bwatson78! I can look at this in more depth and update the ticket about which ones should be "active" or not.

**Comment by bwatson78** [comment]
I'm noticing locally that the autocomplete processing isn't working. I've confirmed the same at https://fedora-depo-arch.libraries.emory.edu/concern/publications/new?locale=en and also https://pg.nurax.samvera.org/concern/generic_works/new?locale=en. That makes this behavior a Hyrax bug, so I'll report it as an issue with Samvera and link it to one of our own Zenhub tickets.

**Comment by bwatson78** [comment]
`holding_repository` PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/67

**Comment by bwatson78** [comment]
`institution` PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/69

**Comment by bwatson78** [comment]
Bug ticket: https://github.com/emory-libraries/dlp-selfdeposit/issues/68

**Comment by bwatson78** [comment]
`emory_content _type` PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/70

**Comment by bwatson78** [comment]
`primary_language` PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/71

**Comment by bwatson78** [comment]
`publisher_version` PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/72

**Comment by bwatson78** [comment]
`place_of_production` PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/73

**Comment by bwatson78** [comment]
`grant_agencies` PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/75

**Comment by bwatson78** [comment]
`rights_statement` PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/76

**Comment by bwatson78** [comment]
`data_classifications` PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/84

**Comment by bwatson78** [comment]
`content_genres` PR: https://github.com/emory-libraries/dlp-selfdeposit/pull/85

**Comment by eporter23** [comment]
Looks great @bwatson78 - I tested all the non-QA local terms. I also noted in the separate bug ticket which fields are impacted by the QA bug.
