### ISSUE TITLE
Re-export and load small set of mixed Publication Types into oe24-arch

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#634]
Backend:

- [x] Re-export and reprocess the set of 59 PIDs from #466
- [x] Send the CSV file to Emily

Emily:

- [ ] Verify these PIDs do not overlap with any PIDs in the larger 1000 batch jobs
- [x] Re-ingest the set of 59 PIDs so that we can have a greater variety of material

**Comment by bwatson78** [comment]
The errors are tied to the changes to default values in publisher. https://eulcoreservices.slack.com/archives/GA9R6ADNH/p1731683642304159?thread_ts=1731682515.034879&cid=GA9R6ADNH

**Comment by bwatson78** [comment]
PR to revert changes: https://github.com/emory-libraries/dlp-selfdeposit/pull/644
