### ISSUE TITLE
Generate preliminary report for number of works and data streams/files to migrate

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#64]
As pre-work to our full migration, we need to identify general Quality Assurance metrics to verify if our end-state is successful.

Using Fedora and/or SOLR, we want to be able to generate a summary report that indicates:

- Total number of "works" in the OpenEmory Collection
- Total number of binary files attached to OpenEmory works (all data streams plus the Fedora 3 AUDIT file)

This data will help us to verify that all expected files have been migrated.

Note: for this ticket, we want to focus on how to retrieve this data. We would need to generate these counts as several points during our ongoing migration work.

**Comment by alexBLR** [comment]
@eporter23 
There are 38642 "works" in the OpenEmory collection (active, inactive, with/without binaries)
There are 32796 "works" with binaries attached to them that are active in fedora.
There are 32796 binaries.

**Comment by eporter23** [comment]
Thank you @alexBLR - this is really helpful and I'm glad you added the context of "active" state in Fedora. I had a question regarding the total number of binaries - does your number refer to the "content" data stream only? I am also looking for the total number of files, as in the number we would expect if we export a file for each datastream per OpenEmory work.  So I'd expect that to be anywhere from 5-10 files per work?

**Comment by alexBLR** [comment]
Here is the stats for each datastream:
SYMPLECTIC-ATOM - 32,661
descMetadata - 34,054
DC - 34,055
Content - 32,797
SYMPLECTIC-LICENCE - 32,649
provenanceMetadata - 32,982
RELS-EXT - 34,055

**Comment by eporter23** [comment]
Thanks @alexBLR this is great. I also did a quick SOLR query on `dsids:bin*` to try to get a sense of how many of the binary version datastreams (like binf5310cf8-f260-4998-aac7-25715064dda8 etc.) there are and will add that to the list also. As of today that query came back as 33,407, which seems similar to the other numbers you've gotten above.
