### ISSUE TITLE
Add a page for monitoring queue latency

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/dlp-selfdeposit#640]
The Sidekiq wiki describes how to create a route that reports queue latency [here](https://github.com/sidekiq/sidekiq/wiki/Monitoring#monitoring-queue-latency). Queue latency is a metric useful for [managing autoscaling](https://github.com/sidekiq/sidekiq/wiki/Scaling-Sidekiq#autoscale-your-sidekiq-containers).

This ticket is complete when:
- [x] OE2 has a public route that reports queue latency
- [x] The latency reported covers all queues

**Comment by bwatson78** [comment]
@rotated8 The code you pointed to reports back either `OK` or `UHOH`. I'm guessing you would rather have the current latency in seconds?

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/647

**Comment by eporter23** [comment]
See Brad's link in the description above for testing.

**Comment by eporter23** [comment]
Closing this because I am not sure if any further testing is needed.
