### ISSUE TITLE
Argument Error when viewing Notifications page on arch

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#65]
**Describe the bug**
When logged in with the default Admin user on arch, the Statistics page returns an error: `ArgumentError in Hyrax::NotificationsController#index`

**To Reproduce**
1. Login as Admin user (admin@example.com)
2. Go to the Dashboard
3. Click on Activity > Your Activity
4. Click on Notifications
5. See error message

**Expected behavior**

See Notifications screen without errors. Reference from Nurax: https://pg.nurax.samvera.org/notifications?locale=en

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abelemlih** [comment]
There is an issue with the Redis configuration on Arch that I am currently investigating. Once Redis is configured properly, this issue will be resolved.

**Comment by abelemlih** [comment]
@eporter23 Redis is now fixed on Arch and this ticket is ready for testing

**Comment by eporter23** [comment]
Thanks, I am no longer seeing the error!
