### ISSUE TITLE
Unable to access the OpenEmory Collection in oe24-arch

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#653]
After a rebuild of the arch environment, we recently loaded a set of 59 works. 

While we can see references to the OpenEmory collection object in arch, attempting to view it does not function.

Steps to reproduce:

Login as Admin
Go to the homepage
Under Explore Collections > click on the OpenEmory collection
Observe that the application does not open the Collection View page and also does not return an error. 

This behavior also occurs when attempting to view the Collection through the Dashboard > Collections view. 

NOTE:
This behavior was not occurring in oe24-test, but we have also rebuilt that environment this week and it contains no data yet.

**Comment by bwatson78** [comment]
This issue doesn't occur when the Collection is created through the UI.

**Comment by bwatson78** [comment]
Both Arch and Test's Collections have been recreated through the UI and are ready for testing.
