### ISSUE TITLE
PDF viewer does not render correctly in oe24-arch and oe24-test

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#654]
After a recent rebuild and re-load of 59 works into oe24-arch and oe24-test, the PDF viewer no longer renders the content.

Example:
https://oe24-arch.libraries.emory.edu/concern/publications/37cff389-06f3-4a4b-8c64-68aca6f70675?locale=en

<img width="1125" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXpUQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb0e8430b5483498e1460b8aaffccbc0ddc02dc5/Screenshot%202024-11-20%20at%209.53.27%E2%80%AFAM.png" alt="Screenshot 2024-11-20 at 9.53.27 AM.png" />

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/666

Eek, run for the hills!

**Comment by eporter23** [comment]
Closing this, but we'll need to apply the changes to arch, too.
