### ISSUE TITLE
QA Authorities like "languages" and "names" are not auto-populating in the forms.

### ISSUE THREAD

**Issue by bwatson78** [emory-libraries/dlp-selfdeposit#68]
### Descriptive summary

QA Authorities like "languages" and "names" are not auto-populating in the forms.

### Steps to reproduce the behavior in User Interface (UI)

1. In Selfdeposit, log in and choose Dashboard from the username's pull down menu (upper-right of the screen).
2. Click on Works (middle left) and select Add New Work (upper right).
3. Choose the type of Publication and click Add Work.
4. Expand Additional Fields and locate Languages. Start typing `Eng` for `English`.

### Actual behavior (include screenshots if available)

https://github.com/samvera/hyrax/assets/18330149/a88bf7b0-8d1a-4f23-ae9a-b3fa1e6e60e4

### Acceptance Criteria/Expected Behavior

A selection box with multiple options appears when typing a few characters.

### Rationale (for feature request only)

Autocomplete has been a standard form feature for multiple versions of Hyrax.

This same bug has been filed with Samvera [here.](https://github.com/samvera/hyrax/issues/6734)

This bug impacts the following QA lookup fields for OpenEmory Publications:

- holding_repository
- institution
- primary_language
- place_of_production
- sponsor
- grant_agencies

**Comment by eporter23** [comment]
I will also review the QA-driven lookup fields to determine urgency for the resolution.

**Comment by eporter23** [comment]
@abelemlih I tested all the fields I noted in the ticket description and all seem to be working now. I will close this ticket and write another one if we see more issues.
