### ISSUE TITLE
Add Preservation Events to FileSets

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#79]
Please see the linked Epic for more information.

This document shows the original specs used to build out the [Preservation Events for FileSets in Curate](https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#heading=h.gmtyknf6fiiy).

Note: in our Curate model implementation, we changed the Hyrax default "original file" PDCM use to "preservation master file". We may need to discuss approaches to this, since "preservation master file" is deprecated.

For this ticket, we will focus on:

- [ ] File submission
- [ ] Characterization

Virus scanning, fixity checking, and message digest calculation will be separate tickets because the functionality isn't in place yet.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/164/files
More to come.

**Comment by bwatson78** [comment]
Skipping Virus Check event because it isn't implemented in the current version of Hyrax.

**Comment by bwatson78** [comment]
Also skipping Fixity Check event because it also isn't implemented in Hyrax v5.

**Comment by bwatson78** [comment]
Made [new issue](Message Digest Calculation (aka Checksum Generation)) for Message Digest Calculation (aka Checksum Generation) because that work includes the actual digestion of the SHAs as well.

**Comment by bwatson78** [comment]
Final PR for this ticket: https://github.com/emory-libraries/dlp-selfdeposit/pull/177

**Comment by eporter23** [comment]
For Characterization, can we add a version number for FITS Servlet? In Curate, we track the version of FITS used.

**Comment by eporter23** [comment]
For File submission, is it possible to remove the Hyrax upload file path component and just record the filename? Example: ```
http://metadata.emory.edu/vocab/cor-terms# eventDetails
/opt/uploads/hyrax/uploaded_file/file/25/critters_April_2024.png submitted for preservation storage
```
Preferably this would just be `critters_April_2024.png submitted for preservation storage`

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/196

**Comment by eporter23** [comment]
Looks good!
