### ISSUE TITLE
Add Preservation Events to Works

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#80]
Please see the linked Epic for more information.

This document includes the original specs for creating [Preservation Events at the Work-level.](https://docs.google.com/document/d/1O_Ut_j8ZAf9WdMGOUNwreM-WVEZ04rKictnUWg3-BLA/edit#heading=h.aixckuzec1ze)

Work-level Events to Generate:
- [x] Validation
- [x] Policy Assignment
- [x] Modification

**Comment by eporter23** [comment]
@bwatson78 I saw your comment on the specs document above. I think we added the Modification Event later, here is that work ticket from Curate: https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/gh/emory-libraries/dlp-curate/1487

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/145

**Comment by eporter23** [comment]
@bwatson78 can you advise on how to test this? If I create a new Work in arch, can I then go to Fedora and see a preservation event?

**Comment by bwatson78** [comment]
@eporter23 I'd say the best way to test this would be to locate the Publication in Fedora by ID, ensure that the field preservation_event_ids is present, and that it's populated by IDs. Then cross reference those IDs with the root list and see if those corresponding objects are properly formed.

**Comment by eporter23** [comment]
These look good @bwatson78 ! Question: for softwareVersion it is currently saying "SelfDeposit pre". Perhaps we should call it "SelfDeposit v.1" for now if we have to hard-code something there?

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/196

**Comment by eporter23** [comment]
Looks good!
