### ISSUE TITLE
Extract and persist additional FITS metadata for FileSets

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#82]
For this ticket, we would like to retain and store more of the FITS metadata than Hyrax currently does. This is a modification we already made in Curate and ideally we would use the same customizations.

[This epic from Curate](https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/gh/emory-libraries/dlp-curate/208) includes some of the tickets related to the work.

[This PR](https://github.com/emory-libraries/dlp-curate/pull/299) also seems to include some information about changes we made to add more technical metadata beyond what Hyrax retains from FITS. 

DROID may also be needed to get some of these properties. [See prior Curate ticket](https://app.zenhub.com/workspaces/digital-library-project-5bf484ae4b5806bc2bf6875b/issues/gh/emory-libraries/dlp-curate/573) related to this.

Note: in our Curate model implementation, we changed the default "original file" PDCM use to "preservation master file". We may need to discuss approaches to this, since "preservation master file" is deprecated.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/226

**Comment by eporter23** [comment]
Looks great @alexBLR ! I uploaded a PNG, an RTF, and a Word doc and can see great examples of the extended technical metadata in both Fedora and SOLR. I may also write a separate ticket to look at some of the predicates being used for Fedora (http://example.com/predicate/character_count etc.) but we can tackle that later.
