### ISSUE TITLE
Hyrax: AWS-VPN access for project team

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#86]
To ensure the current project team can preview and test, we need to ensure that all members can access the Hyrax installation on arch as well as test and production while in development. This may require submitting tickets to OIT to ensure that AWS access has been granted.

**Comment by eporter23** [comment]
To do for Emily: send net ids to Collin by email

**Comment by rotated8** [comment]
All have been added by OIT

**Comment by eporter23** [comment]
Confirmed with SCO that they can all reach it once logged into VPN.
