### ISSUE TITLE
Assign form default values for selected fields

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#89]
Certain fields in the Publication work form should default to an initial value, but should also still be editable/changeable in the form.

Institution: "Emory University"
Holding Repository (holding_repository): "Emory University. Library" 
Format (emory_content_type): "Text"
Rights Status (rights_statements): "In Copyright"
Data Classifications: "Public"

Note: Institution and Holding Repository may be partially blocked by the QA auto-population bug #68.

**Comment by eporter23** [comment]
I'm removing the rights statement/note for now, until I determine if that should be auto-generated if a user does not enter one.

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/111

**Comment by eporter23** [comment]
Tested and looks good @bwatson78
