### ISSUE TITLE
Styling punchlist

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#90]
Please see this [running list of CSS/styling fixes](https://docs.google.com/document/d/1NdMtcLBTm7t97ewXT3KwNPYGxGgyowCrHyQ2VdKkJz0/edit?usp=sharing).

**Comment by eporter23** [comment]
Recommendation is to prioritize this also. This would be a good pickup point for work if other work is not yet identified for OpenEmory.

**Comment by CB987** [comment]
i'm putting screenshots of finished items into the same document linked above

**Comment by CB987** [comment]
First 10 items, [PR#424](https://github.com/emory-libraries/dlp-selfdeposit/pull/424).

**Comment by eporter23** [comment]
Great stuff @CB987 ! I'll leave this ticket open until we deploy to oe-test, but oe-arch looks really good. P.S. I did add a few new things to the punch-list for the next round of work.
