### ISSUE TITLE
Add application version information to the footer

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#91]
The footer element should include the Self Deposit application version and last deployment date. 

Example from Lux:
Version v1.6.2 updated 26 September 2023

Example from Library Search:
Version v1.11.1 updated 06 February 2024

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2EvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b83988539239501b18cc7d3ad03f230d2015d5f/Screenshot%202024-03-07%20at%208.43.07%E2%80%AFAM.png" alt="Screenshot 2024-03-07 at 8.43.07 AM.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2UvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb053fb262763fa4083b714c00527068ad3417e5/Screenshot%202024-03-07%20at%208.43.18%E2%80%AFAM.png" alt="Screenshot 2024-03-07 at 8.43.18 AM.png" />

**Comment by abelemlih** [comment]
@eporter23 Changes to implement footer version have been merged to `main`, and the version will appear as shown below:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUxIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9ddaa6b7b3b3eb122ef210cefb8884290467def/Screenshot%202024-03-08%20at%2012.39.51%E2%80%AFPM.png" alt="Screenshot 2024-03-08 at 12.39.51 PM.png" />

For the time being, in addition to the branch/tag, I also append the first 7 characters of the commit message, so it helps us identify exactly which commit is deployed. At the moment, we do not have a specific tag and we keep deploying main, so knowing which commit was deployed is helpful. I can remove that once we start deploying specific versions.

**Comment by eporter23** [comment]
Thanks @abelemlih , this will be really helpful for testing and keeping track of deployments!
