### ISSUE TITLE
Identify optimal Shibboleth attributes for OpenEmory

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#96]
While we may not be able to utilize all desirable attributes in Hyrax, we should identify the ones we think we may want to minimize repeat requests to the ID management team.

We anticipate we will want the user's name, primary unit, primary department, status (faculty, staff, student, affiliate, etc.) network ID and email.

Work notes:
I am not able to find much documentation regarding different variants of Shibboleth attributes (eduPerson, Emory, etc.) available to us. I also referenced "attributes" in the epic which we have previously used. 

To simplify this process, I am going to refer to what are hopefully commonly understood directory attributes which we may want to utilize if possible. Below uses my public directory data as an example (with some values omitted), using the public directory display labels. 

1. Name: Emily K. Porter (first, last, middle initial)
2. Preferred Name (if separate/distinct from Name)
2. Title :	 Digital Repository Program Manager
3. School/Division :	 Emory University Libraries
4. Department :	 EUL: Digital Product Strategy
5. Type (eduPersonAffiliationValues) :	 Faculty
6. netid
7. PPID/PUID (public directory key): P1952035
8. Emory email address

For 1 above, we may need to use all 3 name elements to disambiguate names if needed
For 2 above, we may want this in case a user has a different preferred name, in the event that their directory name does not reflect the preferred name from HR data
For 3, this should reflect the major School or Business Unit the person is affiliated with
For 4, this should reflect their primary department within their School/Unit
For 5, this should indicate their primary "status" as faculty, staff, student, alumni, affiliate, etc.
For 6, this should be the person's network ID
For 7, this should be the public directory ID key
For 8, this should be the active Emory email address on file for the user

**Comment by eporter23** [comment]
Consider if other attributes may be need in the future, as we may re-use this for other applications in the future

**Comment by kbowaterskelly** [comment]
This looks good to me. When we are ready with a tentative list of desired attributes, I can submit a request to have them evaluated by the shibboleth person(s) and double check to make sure all of the desired attributed are available, or if similar attributes need to be substituted, etc.
