### ISSUE TITLE
Review Shibboleth integration options for Hyrax

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#97]
For this ticket, we will assess Shibboleth/SAML integration options for Hyrax.  Preference is to use a SAML library instead of Shibboleth, and this could help us with other apps such as Library Search.

**Comment by bwatson78** [comment]
We should also consider `https://github.com/apokalipto/devise_saml_authenticatable`, which still utilizes `ruby-saml`, but abstracts most of the necessary setup away knowing that devise is being used for authentication.
